HyperspaceExplorer: XQGLWidget Class Reference
XQGLWidget Class Reference
[User Interface]
#include <XQGLWidget.H>
Public Slots
void ViewPos (double, double, double)
void ViewPos (double)
Public Member Functions
XQGLWidget (QWidget *=0)
bool SetDrawObject (GLObject *obj)
bool SetDrawObject (GLuint list)
void SetBackgroundColor (const VecMath::Vector< 4 > &RGBA)
void SetBackgroundColor (float R, float G, float B, float A)
bool & getColors ()
bool & getShade ()
bool & getFog ()
bool & getLight ()
bool & getTransparent ()
Protected Slots
void Rotate ()
void Help ()
void SetAlpha (int)
void Left ()
void Right ()
void Up ()
void Down ()
void SLeft ()
void SRight ()
void SUp ()
void SDown ()
void CALeft ()
void CARight ()
void CAUp ()
void CADown ()
void Plus ()
void Minus ()
void A ()
void about ()
void aboutQt ()
Protected Member Functions
void initializeGL (void)
void paintGL (void)
void resizeGL (int, int)
void Draw (void)
void mousePressEvent (QMouseEvent *)
void mouseReleaseEvent (QMouseEvent *)
void mouseMoveEvent (QMouseEvent *)
void SetupDepthCue (float, float)
void InitLight (void)
void InitShade (void)
void InitFog (void)
void InitTransparence (void)
Private Attributes
GLObject * DrawObject
double R
viewpoint distance
double psi
rotation about x-axis
double theta
rotation about y-axis
double phi
rotation about z-axis
VecMath::Vector< 4 > Background
GLfloat Alpha
bool light
bool fog
bool transparent
bool shade
bool colors
int xpressed
int ypressed
Detailed Description
class XQGLWidget: implements a QGLWidget
Constructor & Destructor Documentation
XQGLWidget::XQGLWidget (QWidget * parent = 0)
XQGLWidget constructor; does a lot of initialization to (usually sensible) hardcoded default values, creates the menus and accelerators
Parameters:
parent parent QWidget, defaults to NULL
name name, defaulting to ""
Member Function Documentation
void XQGLWidget::ViewPos (double psi_, double theta_, double phi_) [slot]
ViewPos (psi, theta, phi) called any time the viewing angle is changed on the command widget
References phi, psi, and theta.
void XQGLWidget::ViewPos (double R_) [slot]
called any time the viewing distance is changed on the command widget
References R, and resizeGL().
bool& XQGLWidget::getColors () [inline]
Returns:
whether to use colors in rendering or not
Referenced by C4DView::Colors().
bool& XQGLWidget::getShade () [inline]
Returns:
whether to use shading in rendering or not
Referenced by C4DView::Shade().
bool& XQGLWidget::getFog () [inline]
Returns:
whether to use depth cue/fog in rendering or not
Referenced by C4DView::Fog().
bool& XQGLWidget::getLight () [inline]
Returns:
whether to use lighting in rendering or not
bool& XQGLWidget::getTransparent () [inline]
Returns:
whether to use transparence/line antialiasing or not
Referenced by C4DView::Transparent().
void XQGLWidget::SetAlpha (int a) [protected, slot]
changes global transparence Alpha to a
Parameters:
a int e [0, 255]
Referenced by A().
void XQGLWidget::Left () [protected, slot]
"Left" key: rotate 5 degrees left
References theta.
void XQGLWidget::Right () [protected, slot]
"Right" key: rotate 5 degrees right
References theta.
void XQGLWidget::Up () [protected, slot]
"Up" key: rotate 5 degrees up
References psi.
void XQGLWidget::Down () [protected, slot]
"Down" key: rotate 5 degrees down
References psi.
void XQGLWidget::SLeft () [protected, slot]
Shift-"Left" key: rotate 45 degrees left
References theta.
void XQGLWidget::SRight () [protected, slot]
Shift-"Right" key: rotate 45 degrees left
References theta.
void XQGLWidget::SUp () [protected, slot]
Shift-"Up" key: rotate 45 degrees left
References psi.
void XQGLWidget::SDown () [protected, slot]
Shift-"Down" key: rotate 45 degrees left
References psi.
void XQGLWidget::CALeft () [protected, slot]
Ctrl-Alt-"Left" key: rotate 1 degrees left
References theta.
void XQGLWidget::CARight () [protected, slot]
Ctrl-Alt-"Right" key: rotate 1 degrees left
References theta.
void XQGLWidget::CAUp () [protected, slot]
Ctrl-Alt-"Up" key: rotate 1 degrees left
References psi.
void XQGLWidget::CADown () [protected, slot]
Ctrl-Alt-"Down" key: rotate 1 degrees left
References psi.
void XQGLWidget::Plus () [protected, slot]
no function
void XQGLWidget::Minus () [protected, slot]
no function
void XQGLWidget::A () [protected, slot]
"A" key: should open a slider to adjust alpha value. not yet implemented correctly.
References SetAlpha().
void XQGLWidget::about () [protected, slot]
open an "About"-Dialog
void XQGLWidget::aboutQt () [protected, slot]
open an "About Qt"-Dialog
void XQGLWidget::initializeGL (void) [protected]
OpenGL initialization setting background colors, setting up lighting, shading, fog and transparence
Reimplemented in C4DView.
References InitLight(), and Loki::SingletonHolder< T, CreationPolicy >::Instance().
Referenced by C4DView::initializeGL().
void XQGLWidget::resizeGL (int width, int height) [protected]
change of viewing distance is handled here too, which is not so clean programming style...
References Loki::SingletonHolder< T, CreationPolicy >::Instance(), and R.
Referenced by ViewPos().
void XQGLWidget::InitLight (void) [protected]
OpenGL initialization setting background colors, setting up lighting, shading, fog and transparence
Todo:
hardcoded light position and colors!
References Loki::SingletonHolder< T, CreationPolicy >::Instance().
Referenced by initializeGL().
The documentation for this class was generated from the following files:
workspace/HyperspaceExplorer/src/UI/XQGLWidget.H
workspace/HyperspaceExplorer/src/UI/XQGLWidget.C