HyperspaceExplorer: ComplexFunction Class Reference
ComplexFunction Class Reference
[Functions and objects]
#include <ComplexFunction.H>
Public Member Functions
ComplexFunction (const QString &name)
Minimal constructor, sets the function name.
ComplexFunction (const QString &name, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
virtual ~ComplexFunction ()
virtual void SetParameters (double=0, double=0, double=0, double=0)
Set up to 4 parameters.
typedef std::complex< double > function_type (std::complex< double >)
A function from .
Protected Member Functions
virtual VecMath::Vector< 4 > & f (double, double)
void Initialize (void)
Protected Attributes
virtual function_type g = 0
The actual function from C to C.
Detailed Description
A surface defined as a function , where the surface in four dimensions is defined as
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
ComplexFunction::ComplexFunction (const QString & name, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
ComplexFunction c'tor given a definition set in (as parameter space)
Parameters:
_umin minimal value in u
_umax maximal value in u
_du stepsize in u
_vmin minimal value in v
_vmax maximal value in v
_dv stepsize in v
name The function name
ComplexFunction::~ComplexFunction () [virtual]
ComplexFunction destructor
Member Function Documentation
Vector< 4 > & ComplexFunction::f (double uu, double vv) [protected, virtual]
ComplexFunction defining function calling g () and returning (z, g (z))
Parameters:
uu Re (z)
vv Im (z)
Returns:
value of defining function at point in question
Implements SurfaceBase.
References Surface::F, g, std::complex< _Tp >::imag(), and std::complex< _Tp >::real().
Referenced by Initialize().
void ComplexFunction::Initialize (void) [protected, virtual]
allocate and initialize X[][] with values of f() call Surface::InitMem ()
Reimplemented from Surface.
References f(), SurfaceBase::getDt(), SurfaceBase::getDu(), SurfaceBase::getTmin(), SurfaceBase::getTsteps(), SurfaceBase::getUmin(), SurfaceBase::getUsteps(), Surface::InitMem(), std::vector< _Tp, _Alloc >::resize(), and Surface::X.
Referenced by coshz::coshz(), cosz::cosz(), CustomComplexFunction::CustomComplexFunction(), emz2::emz2(), ez::ez(), lnz::lnz(), Polynomial::Polynomial(), sinhz::sinhz(), sinz::sinz(), sqrtz::sqrtz(), tanz::tanz(), z2::z2(), z3::z3(), zA::zA(), zm1::zm1(), and zm2::zm2().
virtual void ComplexFunction::SetParameters (double = 0, double = 0, double = 0, double = 0) [inline, virtual]
Set up to 4 parameters.
Defaults to do nothing, so implementations need not implement it by default.
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Functions/ComplexFunction.H
HyperspaceExplorer/src/Functions/ComplexFunction.C