HyperspaceExplorer: Script::BoolStatement Class Reference
Script::BoolStatement Class Reference
[Statements possible in a script]
Statement with a single boolean parameter.
#include <Statement.H>
Public Member Functions
BoolStatement (const Parser *p, const std::string &_arg)
virtual bool execute ()=0
Executes the statement in the current context.
Protected Member Functions
bool getValue ()
Private Attributes
bool _bool
The current state.
Detailed Description
Statement with a single boolean parameter.
Constructor & Destructor Documentation
Script::BoolStatement::BoolStatement (const Parser * p, const std::string & _arg)
Parameters:
p The context in which the Statement is executed
_arg The argument supplied to the Statement
References _bool.
Member Function Documentation
bool Script::BoolStatement::getValue () [inline, protected]
Returns:
The current state
References _bool.
Referenced by Script::Fog4DStmt::execute(), Script::FogStmt::execute(), Script::SolidStmt::execute(), Script::WireStmt::execute(), Script::TransStmt::execute(), Script::LightStmt::execute(), Script::ShadingStmt::execute(), and Script::ColorStmt::execute().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Script/Statement.H
HyperspaceExplorer/src/Script/Statement.C