HyperspaceExplorer: Ball< D > Class Template Reference
Ball< D > Class Template Reference
Bouncing spheres template.
#include <Ball.H>
Public Member Functions
void draw ()
void step (double dt)
Protected Member Functions
void DrawBall (const Vec< D > &center, double r, const Vec< 4 > &rgba)
Protected Attributes
Vec< D > x
Vec< D > v
Friends
class Box< D >
template<unsigned d>
bool touch (const Ball< d > &, const Ball< d > &, double=0.)
Detailed Description
template<unsigned D>
class Ball< D >
Bouncing spheres template.
Member Function Documentation
template<unsigned D> void Ball< D >::draw () [inline]
Todo:
document me
References distance(), Ball< D >::DrawBall(), Box< D >::project(), BallBase::r, and sqrt().
template<unsigned D> void Ball< D >::step (double dt) [inline]
Todo:
document me
References Ball< D >::v.
template<unsigned D> void Ball< D >::DrawBall (const Vec< D > & center, double r, const Vec< 4 > & rgba) [inline, protected]
Todo:
document me
References BallBase::ball, and BallBase::numSegments.
Referenced by Ball< D >::draw().
Member Data Documentation
template<unsigned D> Vec<D> Ball< D >::x [protected]
Todo:
document me
template<unsigned D> Vec<D> Ball< D >::v [protected]
Todo:
document me
Referenced by Ball< D >::step().
The documentation for this class was generated from the following file:
HyperspaceExplorer/src/Balls/Ball.H