HyperspaceExplorer: Function Class Reference
Function Class Reference
[Functions and objects]
A Function is a mathematical function .
#include <Function.H>
Public Types
typedef std::vector< float > floatvec1D
one-dimensional array of floats, implemented as a std::vector
typedef std::vector< floatvec1D > floatvec2D
two-dimensional array of floats, implemented as a nested std::vector
typedef std::vector< floatvec2D > floatvec3D
three-dimensional array of floats, implemented as a nested std::vector
typedef std::vector
< VecMath::Vector< 3 > > vec3vec1D
one-dimensional array of Vector<3>, implemented as a std::vector
typedef std::vector< vec3vec1D > vec3vec2D
two-dimensional array of Vector<3>, implemented as a nested std::vector
typedef std::vector< vec3vec2D > vec3vec3D
three-dimensional array of Vector<3>, implemented as a nested std::vector
typedef std::vector
< VecMath::Vector< 4 > > vec4vec1D
one-dimensional array of Vector<4>, implemented as a std::vector
typedef std::vector< vec4vec1D > vec4vec2D
two-dimensional array of Vector<4>, implemented as a nested std::vector
typedef std::vector< vec4vec2D > vec4vec3D
three-dimensional array of Vector<4>, implemented as a nested std::vector
Public Member Functions
typedef VecMath::Vector< 4 > & function_type (double, double, double)
Type of the function used to generate values.
typedef VecMath::Vector< 4 > raw_function_type (double, double, double)
The real, raw type of the function used to generate values.
Function ()
Function default c'tor.
Function (const QString &name, double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
virtual void Transform (double Rxy, double Rxz, double Rxw, double Ryz, double Ryw, double Rzw, double Tx, double Ty, double Tz, double Tw)
Transforms a Function.
void Transform (void)
Overloaded function executing the transform to the default state.
virtual void Project (double ScrW, double CamW, bool DepthCue4D)
Projects a Function into three-space.
virtual void Draw (void)
Draw the projected Function (onto screen or into GL list, as it is).
virtual void ReInit (double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
Re-initialize a Function if the definition set has changed.
virtual void SetParameters (double _a=0, double _b=0, double _c=0, double _d=0)
Placeholder for function to set parameters in descendants.
VecMath::Vector< 4 > & operator() (double t, double u, double v)
Function evaluation operator.
QString getFunctionName () const
unsigned getNumParameters ()
std::vector< QString > getParameterNames ()
QString getParameterName (unsigned i)
Get a specified parameter name from the list.
Protected Member Functions
virtual vec4vec1D df (double, double, double)
Numerical calculation of the derivatives in t, u and v.
virtual void Initialize (void)
Allocate and initialize X[][][] with values of f().
void InitMem (void)
Initialize the temporary storage areas.
virtual unsigned long MemRequired (void)
void DrawPlane (unsigned)
Draw the current plane of the projected Function.
void DrawStrip (unsigned, unsigned)
Draw the current strip of the projected Function.
void DrawCube (unsigned, unsigned, unsigned)
Draw the current cube or cell of the projected Function.
Protected Attributes
virtual function_type f = 0
The mathematical function defining the Function object.
virtual function_type normal
Calculate normal to function at a given point in definition set.
double tmin
min. value of the first parameter, here called t
double tmax
min. value of the first parameter, here called t
double dt
stepsize in first parameter
double umin
min. value of the second parameter, here called u
double umax
min. value of the second parameter, here called u
double du
stepsize in second parameter
double vmin
min. value of the third parameter, here called v
double vmax
min. value of the third parameter, here called v
double dv
stepsize in third parameter
unsigned tsteps
number of steps in t
unsigned usteps
number of steps in u
unsigned vsteps
number of steps in v
unsigned NumVertices
counter for the number of GL vertices used drawing the function
VecMath::Vector< 4 > F
temporary storage for the value of the function at a given point
vec4vec3D X
temporary storage for function values on grid
vec4vec3D Xtrans
temporary storage for transformed function values
vec3vec3D Xscr
temporary storage for projected function values
floatvec3D R
storage for the coloring of the vertices - red component
floatvec3D G
storage for the coloring of the vertices - red component
floatvec3D B
storage for the coloring of the vertices - red component
QString functionName
the name of the function as a free-form string
std::vector< QString > parameterNames
list of the names of parameters to the function
Detailed Description
A Function is a mathematical function .
The function f is evaluated on a 3-dimensional grid. The Function class provides the evaluation on the grid, together with methods to rotate and translate the grid in 4-space, to project the transformed grid onto 3-space, and to draw the projected grid into an OpenGL display list.
abstract member:
Vector &f (double, double, double);
virtual members:
Vector *df (double, double, double);
Vector &normal (double, double, double);
Transform (double Rxy, double Rxz, double Rxw, double Ryz, double Ryw, double Rzw, double Tx, double Ty, double Tz, double Tw)
Project (double ScrW, double CamW, bool DepthCue4D)
Draw ()
ReInit(double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
SetParameters (double _a = 0, double _b = 0, double _c = 0, double _d = 0)
other useful members:
Transform ()
operator () (double t, double u, double v)
Initialize ();
InitMem ();
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
Function::Function ()
Function default c'tor.
Zeroes everything
Function::Function (const QString & name, double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
Function c'tor given a definition set in R³ (as parameter space)
Parameters:
name a name for the function
_tmin minimal value in t
_tmax maximal value in t
_dt stepsize in t
_umin minimal value in u
_umax maximal value in u
_du stepsize in u
_vmin minimal value in v
_vmax maximal value in v
_dv stepsize in v
References dt, du, dv, Loki::SingletonHolder< T, CreationPolicy >::Instance(), MemRequired(), tmax, tmin, tsteps, umax, umin, usteps, vmax, vmin, and vsteps.
Member Function Documentation
typedef VecMath::Vector<4>& Function::function_type (double , double , double)
Type of the function used to generate values.
Optimized by using a reference as return value.
void Function::Transform (double thetaxy, double thetaxz, double thetaxw, double thetayz, double thetayw, double thetazw, double tx, double ty, double tz, double tw) [virtual]
Transforms a Function.
Todo:
As I look at it, i think this could be optimized by making the transformation matrices static and only canging the corresponding entries... but how to do this beautifully, i don't know
Parameters:
thetaxy rotation around xy plane (z axis); should be ignored because 3D rotation takes care of it, but isn't
thetaxz rotation around xz plane (y axis); should be ignored because 3D rotation takes care of it, but isn't
thetaxw rotation around xw plane
thetayz rotation around xy plane (x axis); should be ignored because 3D rotation takes care of it, but isn't
thetayw rotation around yw plane
thetazw rotation around zw plane
tx translation in x direction
ty translation in y direction
tz translation in z direction
tw translation in w direction
Reimplemented in Object, Sponge, Gasket, and Surface.
References tsteps, usteps, vsteps, X, and Xtrans.
void Function::Project (double scr_w, double cam_w, bool depthcue4d) [virtual]
Projects a Function into three-space.
Todo:
replace hardcoded function to calculate 4D fog color with better one
Parameters:
scr_w w coordinate of screen
cam_w w coordinate of camera
depthcue4d whether to use hyperfog/depth cue
Reimplemented in Object, Sponge, Gasket, and Surface.
References B, G, R, tsteps, usteps, vsteps, Xscr, and Xtrans.
void Function::Draw (void) [virtual]
Draw the projected Function (onto screen or into GL list, as it is).
Reimplemented in Object, Sponge, Gasket, SteinerFunction, and Surface.
References DrawPlane(), and tsteps.
void Function::ReInit (double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv) [virtual]
Re-initialize a Function if the definition set has changed.
Parameters:
tmin minimal value in t
tmax maximal value in t
dt stepsize in t
umin minimal value in u
umax maximal value in u
du stepsize in u
vmin minimal value in v
vmax maximal value in v
dv stepsize in v
Reimplemented in Object, Sponge, Gasket, and Surface.
References dt, du, dv, Initialize(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), tmax, tmin, tsteps, umax, umin, usteps, vmax, vmin, and vsteps.
void Function::SetParameters (double _a = 0, double _b = 0, double _c = 0, double _d = 0) [virtual]
Placeholder for function to set parameters in descendants.
Empty because a generic function has no parameters
Reimplemented in ComplexFunction, z2, z3, zA, ez, emz2, zm1, zm2, sqrtz, lnz, sinz, cosz, sinhz, coshz, tanz, Polynomial, Hypersphere, Torus1, Torus2, GravitationPotential, PolarSin, PolarR, Hypercube, Sponge, Pyramid, Gasket, Surface, Surface1, Horizon, and Torus3.
VecMath::Vector<4>& Function::operator() (double t, double u, double v) [inline]
Function evaluation operator.
As optimization, returns the precomputed value on the grid point closest to (t, u, v)
Parameters:
t first argument, e.g. x or t
u second argument, e.g. y or u
v third argument, e.g. z or v
Returns:
f(t, u, v), approximated by the value on the grid point closest to (t, u, v)
References dt, du, dv, tmin, umin, vmin, and X.
Referenced by df().
QString Function::getFunctionName () const [inline]
Returns:
The name of the function in cleartext
References functionName.
unsigned Function::getNumParameters () [inline]
Returns:
number of parameters for the function
References parameterNames.
std::vector<QString> Function::getParameterNames () [inline]
Returns:
the names of the parameters for the function
References parameterNames.
QString Function::getParameterName (unsigned i) [inline]
Get a specified parameter name from the list.
Parameters:
i index of the wanted parameter
Returns:
name of the ith parameter
References parameterNames.
Function::vec4vec1D Function::df (double tt, double uu, double vv) [protected, virtual]
Numerical calculation of the derivatives in t, u and v.
Todo:
The h value is fixed and hardcoded. better approach, please!
Todo:
I don't think calling operator() is right. Call f()!
Parameters:
tt t value
uu u value
vv v value
Returns:
gradient in t, u and v as array
References F, and operator()().
void Function::Initialize (void) [protected, virtual]
Allocate and initialize X[][][] with values of f().
Call InitMem() above
Reimplemented in ComplexFunction, Hypercube, Sponge, Pyramid, Gasket, and Surface.
References dt, du, dv, f, InitMem(), tmin, tsteps, umin, usteps, vmin, vsteps, and X.
Referenced by CustomFunction::CustomFunction(), CustomPolarFunction::CustomPolarFunction(), Fr3r::Fr3r(), Fr3rExp::Fr3rExp(), Fr3rSin::Fr3rSin(), GravitationPotential::GravitationPotential(), Hypersphere::Hypersphere(), Polar::Polar(), PolarR::PolarR(), PolarSin::PolarSin(), PolarSin2::PolarSin2(), Object::ReInit(), ReInit(), Torus1::Torus1(), and Torus2::Torus2().
void Function::InitMem (void) [protected]
Initialize the temporary storage areas.
Xscr[][][], Xtrans[][][], R[][][], G[][][], B[][][]
Reimplemented in Surface.
References B, G, R, tsteps, usteps, vsteps, Xscr, and Xtrans.
Referenced by Initialize().
unsigned long Function::MemRequired (void) [protected, virtual]
Return the approximate amount of memory needed to display a Function of current definition set
Todo:
uses hardcoded and experimentally found value for memory per cell
Returns:
approx. mem required
Reimplemented in Gasket, and Surface.
References tsteps, usteps, and vsteps.
Referenced by Function(), and Sponge::Initialize().
void Function::DrawPlane (unsigned t) [protected]
Draw the current plane of the projected Function.
Parameters:
t current t value
Reimplemented in Surface.
References DrawStrip(), and usteps.
Referenced by Draw().
void Function::DrawStrip (unsigned t, unsigned u) [protected]
Draw the current strip of the projected Function.
Parameters:
t current t value
u current u value
References DrawCube(), and vsteps.
Referenced by DrawPlane().
void Function::DrawCube (unsigned t, unsigned u, unsigned v) [protected]
Draw the current cube or cell of the projected Function.
Parameters:
t current t value
u current u value
v current v value
References B, G, Loki::SingletonHolder< T, CreationPolicy >::Instance(), NumVertices, R, and Xscr.
Referenced by DrawStrip().
Member Data Documentation
Vector< 4 > & Function::normal [protected]
Calculate normal to function at a given point in definition set.
No further assumption is made than that f () is continuous.
This function is not yet used anywhere, but i like it.
Parameters:
tt t value
uu u value
vv v value
Returns:
surface normal, normalized
Reimplemented in Hypersphere, and Surface.
floatvec3D Function::R [protected]
storage for the coloring of the vertices - red component
Todo:
turn these three arrays into a single array of Color's
Reimplemented in Torus1, Torus2, GravitationPotential, Object, and Surface.
Referenced by DrawCube(), InitMem(), and Project().
floatvec3D Function::G [protected]
storage for the coloring of the vertices - red component
Todo:
turn these three arrays into a single array of Color's
Reimplemented in Object, and Surface.
Referenced by DrawCube(), InitMem(), and Project().
floatvec3D Function::B [protected]
storage for the coloring of the vertices - red component
Todo:
turn these three arrays into a single array of Color's
Reimplemented in Object, and Surface.
Referenced by DrawCube(), InitMem(), and Project().
The documentation for this class was generated from the following files:
workspace/HyperspaceExplorer/src/Functions/Function.H
workspace/HyperspaceExplorer/src/Functions/Function.C