HyperspaceExplorer: Menu4D Class Reference
Menu4D Class Reference
[User Interface]
#include <Menu4D.H>
Public Types
typedef std::map< QString,
QAction * > ActionMapType
typedef std::map< QMenu
*, ActionMapType > MenuMapType
Public Member Functions
Menu4D (C4DView *)
void updateFunctionMenu (const QString &)
QAction *& getAction (const QString &key)
void addToMenuBar (QMenuBar *menuBar)
Private Member Functions
QAction * insertAction (QMenu *, const QString &, const char *, bool=true)
QAction * insertAction (QMenu *, const QString &, FunctionFactory *, bool=true)
New version of insertAction() working with the SlotHelper class.
QAction * insertAction (QMenu *, const QString &, SurfaceFactory *, bool=true)
New version of insertAction() working with the SlotHelper class.
QAction * insertAction (QMenu *_menu, const Function *function, const char *slot, bool checkable=true)
Private Attributes
C4DView * parent
QMenu * functions
QMenu * appear
QMenu * animation
QMenu * help
QMenu * fr3r
QMenu * objects
QMenu * surfaces
QMenu * fcc
MenuMapType menuMap
Detailed Description
The menu for the C4DView.
This class has been outsourced from C4DView to keep C4DView of a managable size.
Author:
Helge Preuss <scout@hyperspace-travel.de>
Member Function Documentation
void Menu4D::updateFunctionMenu (const QString & item)
set the selected function as checked and all the others unchecked
Parameters:
item QString the item's title
References getAction().
Referenced by C4DView::ObjectGasket(), C4DView::ObjectHypercube(), C4DView::ObjectHyperpyramid(), C4DView::ObjectHypersponge(), SurfaceSlotHelper::slot(), and FunctionSlotHelper::slot().
QAction *& Menu4D::getAction (const QString & key)
search for the supplied String in the list of menu entries in all submenus and return the associated QAction
Referenced by C4DView::Colors(), C4DView::Coordinates(), C4DView::Fog(), C4DView::HyperFog(), C4DView::RenderToImages(), C4DView::Shade(), C4DView::Transparent(), updateFunctionMenu(), and C4DView::Wireframe().
QAction * Menu4D::insertAction (QMenu * _menu, const QString & title, const char * slot, bool checkable = true) [private]
insert a menu item with a specified slot into a specified menu AND into the hash map storing the actions by menu title. this is necessary to find the menus whenever you want to change the item titles.
Parameters:
_menu the menu you want to add the item to
title the title of the item
slot the function triggered by the item's selection
checkable whether the menu item is checkable
QAction * Menu4D::insertAction (QMenu * _menu, const QString & title, FunctionFactory * factory, bool checkable = true) [private]
New version of insertAction() working with the SlotHelper class.
Parameters:
_menu the menu you want to add the item to
title the title of the item
checkable whether the menu item is checkable
QAction * Menu4D::insertAction (QMenu * _menu, const QString & title, SurfaceFactory * factory, bool checkable = true) [private]
New version of insertAction() working with the SlotHelper class.
Parameters:
_menu the menu you want to add the item to
title the title of the item
checkable whether the menu item is checkable
The documentation for this class was generated from the following files:
workspace/HyperspaceExplorer/src/UI/Menu4D.H
workspace/HyperspaceExplorer/src/UI/Menu4D.C