HyperspaceExplorer: Surface Class Reference
Surface Class Reference
[Functions and objects]
#include <Surface.H>
Public Member Functions
Surface ()
Surface (const QString &name, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
virtual ~Surface ()
virtual void Transform (double Rxy, double Rxz, double Rxw, double Ryz, double Ryw, double Rzw, double Tx, double Ty, double Tz, double Tw)
void Transform (void)
virtual void Project (double ScrW, double CamW, bool DepthCue4D)
virtual void Draw (void)
virtual void ReInit (double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
virtual void SetParameters (double _a=0, double _b=0, double _c=0, double _d=0)
VecMath::Vector< 4 > ** Data (void)
VecMath::Vector< 4 > & operator() (double u, double v)
typedef VecMath::Vector< 4 > & function_type (double, double)
typedef VecMath::Vector< 4 > raw_function_type (double, double)
Protected Member Functions
virtual VecMath::Vector< 4 > & f (double, double, double)
virtual VecMath::Vector< 4 > * df (double, double)
void Initialize (void)
void InitMem (void)
virtual void Free (void)
virtual unsigned long MemRequired (void)
void DrawPlane (unsigned)
void DrawStrip (unsigned)
Protected Attributes
virtual function_type f = 0
virtual function_type normal
double umin
double umax
double du
double vmin
double vmax
double dv
unsigned usteps
unsigned vsteps
unsigned NumVertices
VecMath::Vector< 4 > F
VecMath::Vector< 4 > ** X
VecMath::Vector< 4 > ** Xtrans
VecMath::Vector< 3 > ** Xscr
VecMath::Vector< 4 > * Xchunk
VecMath::Vector< 4 > * XtransChunk
VecMath::Vector< 3 > * XscrChunk
float ** R
float ** G
float ** B
float * RGBChunk
Detailed Description
A function from , thus describing a parametrized surface in hyperspace
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
Surface::Surface ()
Surface default c'tor zeroes everything
Surface::Surface (const QString & name, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
Function c'tor given a definition set in (as parameter space)
Parameters:
_umin minimal value in u
_umax maximal value in u
_du stepsize in u
_vmin minimal value in v
_vmax maximal value in v
_dv stepsize in v
Surface::~Surface () [virtual]
Surface destructor
References Free().
Member Function Documentation
void Surface::Transform (double Rxy, double Rxz, double thetaxw, double Ryz, double thetayw, double thetazw, double tx, double ty, double tz, double tw) [virtual]
transforms a Surface as I look at it, i think this could be optimized by making the transformation matrices static and only canging the corresponding entries... but how to make this beautifully, i don't know
Parameters:
thetaxy rotation around xy plane (z axis); ignored because 3D rotation takes care of it
thetaxz rotation around xz plane (y axis); ignored because 3D rotation takes care of it
thetaxw rotation around xw plane
thetayz rotation around xy plane (x axis); ignored because 3D rotation takes care of it
thetayw rotation around yw plane
thetazw rotation around zw plane
tx translation in x direction
ty translation in y direction
tz translation in z direction
tw translation in w direction
Reimplemented from Function.
References Transform().
Referenced by Transform().
void Surface::Project (double scr_w, double cam_w, bool depthcue4d) [virtual]
projects a Surface into three-space
Parameters:
scr_w w coordinate of screen
cam_w w coordinate of camera
depthcue4d wheter to use hyperfog/depth cue
Reimplemented from Function.
void Surface::Draw (void) [virtual]
draw the projected Surface (onto screen or into GL list, as it is)
Reimplemented from Function.
References DrawStrip().
void Surface::ReInit (double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv) [virtual]
re-initialize a Surface if the definition set has changed
Parameters:
tmin minimal value in t (ignored)
tmax maximal value in t (ignored)
dt stepsize in t (ignored)
umin minimal value in u
umax maximal value in u
du stepsize in u
vmin minimal value in v
vmax maximal value in v
dv stepsize in v
Reimplemented from Function.
References Initialize().
void Surface::SetParameters (double _a = 0, double _b = 0, double _c = 0, double _d = 0) [virtual]
placeholder for function to set parameters in descendants - empty because generic function has no parameters
Parameters:
_a 1st parameter
_b 2nd parameter
_c 3rd parameter
_d 4th parameter
Reimplemented from Function.
Reimplemented in ComplexFunction, z2, z3, zA, ez, emz2, zm1, zm2, sqrtz, lnz, sinz, cosz, sinhz, coshz, tanz, Polynomial, Surface1, Horizon, and Torus3.
Vector< 4 > * Surface::df (double uu, double vv) [protected, virtual]
numerical calculation of the derivatives in u and v:
Parameters:
uu u value
vv v value
Returns:
gradient in t, u and v as array
void Surface::Initialize (void) [protected, virtual]
allocate and initialize X[][] with values of f() call InitMem () above
Reimplemented from Function.
Reimplemented in ComplexFunction.
References InitMem().
Referenced by Horizon::Horizon(), ReInit(), Surface1::Surface1(), and Torus3::Torus3().
void Surface::InitMem (void) [protected]
Initialize the temporary storage areas Xscr[][], Xtrans[][], R[][], G[][], B[][]
Reimplemented from Function.
Referenced by Initialize(), and ComplexFunction::Initialize().
void Surface::Free (void) [protected, virtual]
auxiliary function to safely free all member arrays
Reimplemented from Function.
Referenced by ~Surface().
unsigned long Surface::MemRequired (void) [protected, virtual]
return the approximate amount of memory needed to display a Function of current definition set uses hardcoded and experimentally found value for memory per cell - ICK!
Returns:
approx. mem required
Reimplemented from Function.
void Surface::DrawPlane (unsigned t) [protected]
draw the current plane of the projected Function
Parameters:
t current t value
Reimplemented from Function.
void Surface::DrawStrip (unsigned u) [protected]
draw the current strip of the projected Function
Parameters:
u current u value
References Loki::SingletonHolder< T, CreationPolicy >::Instance().
Referenced by Draw().
Member Data Documentation
Vector< 4 > & Surface::normal [protected]
calculate normal to function at a given point in definition set no further assumption is made than that f () is continuous this function is not yet used anywhere, but i like it
Parameters:
uu u value
vv v value
Returns:
surface normal, normalized
Reimplemented from Function.
The documentation for this class was generated from the following files:
workspace/HyperspaceExplorer/src/Functions/Surface.H
workspace/HyperspaceExplorer/src/Functions/Surface.C