HyperspaceExplorer: ColorManager Class Reference
ColorManager Class Reference
Interface for all color managers.
#include <ColorManager.H>
Public Member Functions
ColorManager (const Function *_f)
virtual void setFunction (const Function *_f)
virtual void calibrateColor (const Color &col, float x, float y, float z)=0
Point (x, y, z) has color col. This may serve for interpolation.
virtual void setColor (const VecMath::Vector< 4 > &x)
Set current OpenGL color at given point.
virtual Color getColor (const VecMath::Vector< 4 > &)=0
Find the color of a given point.
virtual void depthCueColor (double wmax, double wmin, double w, float, float, float)=0
post-process color at given point to have 4D depth cue
Protected Types
typedef std::vector< Color > colorvec1D
one-dimensional Color array, implemented as a std::vector
typedef std::vector< colorvec1D > colorvec2D
two-dimensional Color array, implemented as a nested std::vector
typedef std::vector< colorvec2D > colorvec3D
three-dimensional Color array, implemented as a nested std::vector
typedef std::vector< colorvec3D > colorvec4D
four-dimensional Color array, implemented as a nested std::vector
Protected Attributes
const Function * f
Function for which to manage colors.
double ambientColorModifier
double specularColorModifier
double specularColorMinimum
double SHININESS
double ALPHA
double offset4Ddepthcue
Detailed Description
Interface for all color managers.
C++ Interface: ColorManager
Description:
Author:
: Helge Preuss <scout@hyperspace-travel.de>, (C) 2008
Copyright: See COPYING file that comes with this distribution sets some values common to all color managers, manages the function belonging to every color manager and has some typedefs for arrays of colors.
But above all, defines the interface every color manager must implement.
Member Function Documentation
void ColorManager::setColor (const VecMath::Vector< 4 > & x) [virtual]
Set current OpenGL color at given point.
Parameters:
x four-dimensional coordinate for which the color is sought
C++ Implementation: ColorManager
Description:
Author:
Helge Preuss <scout@hyperspace-travel.de>, (C) 2008
Copyright: See COPYING file that comes with this distribution set the current OpenGL color uses HARDCODED simple algorithm to set ambient and specular values for a specific color: if halves resp. dobles them, clipping at 1.0
Todo:
make the agorithm which computes the ambient and specular values variable
Parameters:
rgb color value to be set
References ambientColorModifier, getColor(), Color::setComponentLowerLimit(), SHININESS, specularColorMinimum, and specularColorModifier.
virtual Color ColorManager::getColor (const VecMath::Vector< 4 > &) [pure virtual]
Find the color of a given point.
Parameters:
x four-dimensional coordinate for which the color is sought
Implemented in xyz2RGBColorManager, and monochromeColorManager.
Referenced by setColor().
Member Data Documentation
double ColorManager::ambientColorModifier [protected]
value to multiply a color with to get its ambient value
Referenced by setColor().
double ColorManager::specularColorModifier [protected]
value to multiply a color with to get its specular value
Referenced by setColor().
double ColorManager::specularColorMinimum [protected]
minimum value for the specular component of any color
Referenced by setColor().
double ColorManager::SHININESS [protected]
shininess value
Referenced by setColor().
double ColorManager::ALPHA [protected]
alpha value for transparent display
double ColorManager::offset4Ddepthcue [protected]
offset (minimum color) value for 4D depth cue
Referenced by xyz2RGBColorManager::depthCueColor().
The documentation for this class was generated from the following files:
workspace/HyperspaceExplorer/src/ColorManager.H
workspace/HyperspaceExplorer/src/ColorManager.C