HyperspaceExplorer: CustomFunction Class Reference
CustomFunction Class Reference
[Functions R^3 -> R]
#include <CustomFunction.H>
Public Member Functions
CustomFunction (double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv, bool final=true)
virtual ~CustomFunction ()
Protected Member Functions
virtual VecMath::Vector< 4 > & f (double, double, double)
Detailed Description
A Function , which the user can edit to have an arbitrary function.
Constructor & Destructor Documentation
CustomFunction::CustomFunction (double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv, bool final = true)
CustomFunction c'tor given a definition set in R³ (as parameter space) and a flag indicatin whether this is a test construction or a real one
Parameters:
_tmin minimal value in t
_tmax maximal value in t
_dt stepsize in t
_umin minimal value in u
_umax maximal value in u
_du stepsize in u
_vmin minimal value in v
_vmax maximal value in v
_dv stepsize in v
_final real construction or test
References RealFunction::Initialize(), PluginCreator::libraryName(), and CustomFunctionBase< RealFunction::raw_function_type >::loadFunction().
CustomFunction::~CustomFunction () [virtual]
CustomFunction destructor, closes DLL if necessary
Member Function Documentation
Vector< 4 > & CustomFunction::f (double x, double y, double z) [protected, virtual]
CustomFunction defining function; calls loaded function
Parameters:
x x value
y y value
z z value
Returns:
custom function of (x, y, z)
Implements RealBase.
Reimplemented in CustomPolarFunction.
The documentation for this class was generated from the following files:
workspace/HyperspaceExplorer/src/Functions/CustomFunction.H
workspace/HyperspaceExplorer/src/Functions/CustomFunction.C