HyperspaceExplorer: C4DView::MouseHandler4D Class Reference
C4DView::MouseHandler4D Class Reference
#include <MouseHandler.H>
Public Member Functions
MouseHandler4D (C4DView *)
Create a MouseHandler4D for a C4DView.
void mouseMoveEvent (QMouseEvent *)
Mouse move event handler.
void mousePressEvent (QMouseEvent *)
Mouse button event handler.
void mouseReleaseEvent (QMouseEvent *)
Mouse button release event handler.
void mouseDoubleClickEvent (QMouseEvent *)
Double click event handler.
Private Member Functions
void setm_LeftDownPos (QPoint b)
QPoint LeftDownPos () const
void setm_MidDownPos (QPoint b)
QPoint MidDownPos () const
void setm_RightDownPos (QPoint b)
QPoint RightDownPos () const
void setTakingSpinValues (bool b)
Set whether mouse button pressed & mouse moved to take movement speed.
bool TakingSpinValues () const
Private Attributes
C4DView * parent
the C4DView containing this mouse handler
QPoint m_LeftDownPos
position where the LMB press started
QPoint m_MidDownPos
position where the MMB press started
QPoint m_RightDownPos
position where the RMB press started
bool m_TakingSpinValues
true while mouse button pressed & mouse moved to take movement speed
Detailed Description
Inner class to C4DView which handles the mouse events
Author:
Helge Preuss <scout@hyperspace-travel.de>
Member Function Documentation
void C4DView::MouseHandler4D::mouseMoveEvent (QMouseEvent * e)
Mouse move event handler.
Awfully long, which is UGLY, but it does not seem to make much sense to break it up, so here we go
Particular mouse move/button/modifier key combinations documented in the code below
Parameters:
e Qt's mouse event information structure
References UI::ViewImpl::adddR(), C4DView::addm_rot(), C4DView::addm_trans(), UI::ViewImpl::addR(), UI::ViewImpl::addT(), UI::ViewImpl::getdR(), UI::ViewImpl::getFog(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), LeftDownPos(), C4DView::m_trans(), MidDownPos(), C4DView::paintEvent(), parent, UI::ViewImpl::R(), C4DView::Redraw(), RightDownPos(), rotate(), setm_LeftDownPos(), setm_MidDownPos(), setm_RightDownPos(), C4DView::setm_trans(), setTakingSpinValues(), C4DView::SetupDepthCue(), C4DView::Size(), UI::ViewImpl::T(), TakingSpinValues(), C4DView::Transform(), and C4DView::UpdateStatus().
Referenced by C4DView::mouseMoveEvent().
void C4DView::MouseHandler4D::mousePressEvent (QMouseEvent * e)
Mouse button event handler.
Only sets flags which buttons are down
Parameters:
e Qt's mouse event information structure
References Loki::SingletonHolder< T, CreationPolicy >::Instance(), C4DView::Menu(), parent, setm_LeftDownPos(), setm_MidDownPos(), and setm_RightDownPos().
Referenced by C4DView::mousePressEvent().
void C4DView::MouseHandler4D::mouseReleaseEvent (QMouseEvent *)
Mouse button release event handler.
If taking values for an animation, starts the animation.
References Loki::SingletonHolder< T, CreationPolicy >::Instance(), parent, setTakingSpinValues(), C4DView::StartAnimation(), TakingSpinValues(), and C4DView::UpdateStatus().
Referenced by C4DView::mouseReleaseEvent().
void C4DView::MouseHandler4D::mouseDoubleClickEvent (QMouseEvent *)
Double click event handler.
Stops animation, if running, or resets transformation values to default.
References C4DView::Animated(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), parent, C4DView::Redraw(), C4DView::StopAnimation(), C4DView::Transform(), and C4DView::UpdateStatus().
Referenced by C4DView::mouseDoubleClickEvent().
void C4DView::MouseHandler4D::setm_LeftDownPos (QPoint b) [inline, private]
Parameters:
b position where the LMB press started
References m_LeftDownPos.
Referenced by mouseMoveEvent(), and mousePressEvent().
QPoint C4DView::MouseHandler4D::LeftDownPos () const [inline, private]
Returns:
position where the LMB press started
References m_LeftDownPos.
Referenced by mouseMoveEvent().
void C4DView::MouseHandler4D::setm_MidDownPos (QPoint b) [inline, private]
Parameters:
b position where the MMB press started
References m_MidDownPos.
Referenced by mouseMoveEvent(), and mousePressEvent().
QPoint C4DView::MouseHandler4D::MidDownPos () const [inline, private]
Returns:
position where the MMB press started
References m_MidDownPos.
Referenced by mouseMoveEvent().
void C4DView::MouseHandler4D::setm_RightDownPos (QPoint b) [inline, private]
Parameters:
b position where the RMB press started
References m_RightDownPos.
Referenced by mouseMoveEvent(), and mousePressEvent().
QPoint C4DView::MouseHandler4D::RightDownPos () const [inline, private]
Returns:
position where the RMB press started
References m_RightDownPos.
Referenced by mouseMoveEvent().
bool C4DView::MouseHandler4D::TakingSpinValues () const [inline, private]
Returns:
Mouse button pressed & mouse moved to take movement speed?
References m_TakingSpinValues.
Referenced by mouseMoveEvent(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/UI/MouseHandler.H
HyperspaceExplorer/src/UI/MouseHandler.C