HyperspaceExplorer: Script::Parser Class Reference
Script::Parser Class Reference
[Scripting]
Parser reads a file and executes the commands in it in a C4DView.
#include <Parser.H>
Public Member Functions
Parser (const std::string &file)
open a parser object for a given filename
bool execute ()
Execute the commands described in the rc-file.
void setView (UI::View *view)
Define the view we operate on.
UI::View * getView () const
Private Attributes
std::vector< std::string > _lines
Lines of the script.
UI::View * _view
The View on which we're operating.
Detailed Description
Parser reads a file and executes the commands in it in a C4DView.
This class takes the role of the Context class in the class diagram for the Interpreter pattern in the GOF book, p. 245
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
Script::Parser::Parser (const std::string & file)
open a parser object for a given filename
Read a command file and store its content for later execution.
The content of file is stored line-wise
Todo:
lines must not be longer than 4095 characters. Everything after that is discarded. This is a limitation of std::ifstream::getline().
Parameters:
file The script file that is read
References _lines, std::vector< _Tp, _Alloc >::push_back(), and Script::strip_comments().
Member Function Documentation
bool Script::Parser::execute ()
Execute the commands described in the rc-file.
execute the commands for the current command file
Executes the statements in the file one after the other
Returns:
success
References _lines, std::vector< _Tp, _Alloc >::begin(), Script::StatementFactory::createStatement(), std::vector< _Tp, _Alloc >::end(), and Script::Statement::execute().
UI::View* Script::Parser::getView () const [inline]
Returns:
The view we operate on
References _view.
Referenced by Script::ImgPrefixStmt::execute(), Script::ImgDirStmt::execute(), Script::AnimateStmt::execute(), Script::Fog4DStmt::execute(), Script::FogStmt::execute(), Script::SolidStmt::execute(), Script::WireStmt::execute(), Script::TransStmt::execute(), Script::LightStmt::execute(), Script::ShadingStmt::execute(), Script::ColorStmt::execute(), Script::LoopStmt::execute(), Script::FramesStmt::execute(), Script::DeltaStmt::execute(), Script::XformStmt::execute(), Script::ParmStmt< T >::execute(), Script::ObjectStmt::execute(), and Script::SizeStmt::execute().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Script/Parser.H
HyperspaceExplorer/src/Script/Parser.C