HyperspaceExplorer: BallBase Class Reference
BallBase Class Reference
Base class for the bouncing spheres template.
#include <Ball.H>
Static Public Member Functions
static void setRandomSize (bool r)
static bool getRandomSize ()
static void setRMax (const double &r)
static double getRMax ()
static void setNumSegments (unsigned n)
Protected Attributes
double r
double m
Static Protected Attributes
static bool randomSize = true
static double rmax = 0.2
static unsigned numSegments = 16
static GLint ball = MakeStone (12)
Friends
class BoxBase
Detailed Description
Base class for the bouncing spheres template.
Member Function Documentation
static void BallBase::setRandomSize (bool r) [inline, static]
Todo:
document me
References randomSize.
Referenced by BoxBase::setRndSize().
static bool BallBase::getRandomSize () [inline, static]
Todo:
document me
References randomSize.
Referenced by BoxBase::getRndSize().
static void BallBase::setRMax (const double & r) [inline, static]
Todo:
document me
References rmax.
Referenced by BoxBase::setRMax().
static double BallBase::getRMax () [inline, static]
Todo:
document me
References rmax.
Referenced by BoxBase::getRMax().
static void BallBase::setNumSegments (unsigned n) [inline, static]
Todo:
document me
References numSegments.
Member Data Documentation
double BallBase::r [protected]
Todo:
document me
Referenced by Ball< D >::draw(), and Box< D >::makeBall().
double BallBase::m [protected]
Todo:
document me
bool BallBase::randomSize = true [static, protected]
Todo:
document me
Referenced by getRandomSize(), and setRandomSize().
double BallBase::rmax = 0.2 [static, protected]
Todo:
document me
Referenced by getRMax(), and setRMax().
unsigned BallBase::numSegments = 16 [static, protected]
Todo:
document me
Referenced by Ball< D >::DrawBall(), and setNumSegments().
GLint BallBase::ball = MakeStone (12) [static, protected]
Todo:
document me
Referenced by Ball< D >::DrawBall().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Balls/Ball.H
HyperspaceExplorer/src/Balls/Ball.C