HyperspaceExplorer: Object Class Reference
Object Class Reference
[Functions and objects]
Generalized four-dimensional Object, described by vertexes and surfaces.
#include <Object.H>
Public Types
typedef std::vector< unsigned > uintvec1D
one-dimensional array of unsigned, implemented as a std::vector
typedef std::vector< uintvec1D > uintvec2D
two-dimensional array of unsigned, implemented as a nested vector
Public Member Functions
Object (const QString &, unsigned, unsigned)
virtual void ReInit (double, double, double, double, double, double, double, double, double)
virtual void Transform (const VecMath::Rotation< 4 > &R, const VecMath::Vector< 4 > &T)
Transforms an Object.
virtual void Project (double ScrW, double CamW, bool DepthCue4D)
Projects an Object into three-space.
virtual void Draw (void)
Draw the projected Object (onto screen or into GL list, as it is).
virtual VecMath::Vector< 4 > & operator() (double, double, double)
Function evaluation operator for three parameters.
virtual const unsigned getDefinitionSpaceDimensions ()
Protected Member Functions
virtual void Initialize ()
Actually create the Object, this method is overridden in child classes.
void setX (const vec4vec1D &)
Set temporary storage for the function values.
virtual VecMath::Vector< 4 > & f (double, double, double)
Protected Attributes
vec4vec1D X
temporary storage for the function values
vec4vec1D Xtrans
temp. storage for transformed function values
vec3vec1D Xscr
temporary storage for projected function values
uintvec2D Surface
the surfaces, stored as vectors of indeces to the points in X
Detailed Description
Generalized four-dimensional Object, described by vertexes and surfaces.
An Object is a four-dimensional geometrical object which can not be described as a mathematical function from to or from to .
Instead it is described as a set of surfaces.
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
Object::Object (const QString & name, unsigned vertices, unsigned surfaces)
generic Object constructor; only allocates necessary arrays, children must fill them in their c'tor
Parameters:
name name of the object
vertices number of vertices
surfaces number of surfaces
References Function::setfunctionName().
Member Function Documentation
void Object::ReInit (double , double , double , double , double , double , double , double , double) [virtual]
Reinitialize an Object. This function is called when the initialization is done outside the constructor.
Currently it does not differ from Initialize(). In fact, it simply calls Initialize().
Implements Function.
Reimplemented in Sponge, and Gasket.
References Initialize(), and Loki::SingletonHolder< T, CreationPolicy >::Instance().
Referenced by Gasket::ReInit(), and Sponge::ReInit().
void Object::Transform (const VecMath::Rotation< 4 > & R, const VecMath::Vector< 4 > & T) [virtual]
Transforms an Object.
Parameters:
R Rotation
T Translation
Implements Function.
Reimplemented in Sponge, Gasket, and Rotope.
References std::vector< _Tp, _Alloc >::size(), X, and Xtrans.
void Object::Project (double scr_w, double cam_w, bool depthcue4d) [virtual]
Projects an Object into three-space.
Parameters:
scr_w w coordinate of screen
cam_w w coordinate of camera
depthcue4d wheter to use hyperfog/dc
Implements Function.
Reimplemented in Sponge, and Gasket.
References std::vector< _Tp, _Alloc >::at(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), std::vector< _Tp, _Alloc >::resize(), std::vector< _Tp, _Alloc >::size(), X, Xscr, and Xtrans.
virtual const unsigned Object::getDefinitionSpaceDimensions () [inline, virtual]
See also:
Function::getDefinitionSpaceDimensions()
Implements Function.
void Object::Initialize (void) [protected, virtual]
Actually create the Object, this method is overridden in child classes.
Calibrates the color manager from the vertices of the object.
In child classes, this method should be reimplemented to set up the arrays X and Surface. When that is finished, the reimplementation should call
 Object::Initialize()
at the end of its own Initialize() routine to calibrate the color manager.
Implements Function.
Reimplemented in Hypercube, Sponge, Pyramid, and Gasket.
References Loki::SingletonHolder< T, CreationPolicy >::Instance(), std::vector< _Tp, _Alloc >::size(), and X.
Referenced by Gasket::Initialize(), Pyramid::Initialize(), Sponge::Initialize(), Hypercube::Initialize(), ReInit(), and Rotope::Rotope().
virtual VecMath::Vector<4>& Object::f (double , double , double) [inline, protected, virtual]
A pointless function, but it must be overridden to satisfy the Function interface. In an Object it is never called because the four-dimensional object is represented by a list of surfaces instead of a mathematical function.
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Functions/Object.H
HyperspaceExplorer/src/Functions/Object.C