HyperspaceExplorer: C4DView::TemplatedFunctionFactory< function > Class Template Reference
C4DView::TemplatedFunctionFactory< function > Class Template Reference
[Helper classes for User Interface classes]
Class template implementation for a factory creating Function's.
#include <4DView.H>
Public Member Functions
virtual Function * createFunction (C4DView *)
Factory method to create a Function object.
Detailed Description
template<typename function>
class C4DView::TemplatedFunctionFactory< function >
Class template implementation for a factory creating Function's.
The type of the Function to be created by the factory method of this class is passed as a template parameter.
Member Function Documentation
template<class function> Function * C4DView::TemplatedFunctionFactory< function >::createFunction (C4DView * view) [inline, virtual]
Factory method to create a Function object.
The type of the created Function is supplied as template parameter to the TemplatedFunctionFactory object owning this method.
Implements FunctionFactory.
References ValuesDialogImpl::dt(), ValuesDialogImpl::du(), ValuesDialogImpl::dv(), ValuesDialogImpl::tmax(), ValuesDialogImpl::tmin(), ValuesDialogImpl::umax(), ValuesDialogImpl::umin(), C4DView::Values, ValuesDialogImpl::vmax(), and ValuesDialogImpl::vmin().
The documentation for this class was generated from the following file:
workspace/HyperspaceExplorer/src/UI/4DView.H