HyperspaceExplorer: CustomPolarFunction Class Reference
CustomPolarFunction Class Reference
[Polar functions R^3 -> R]
#include <CustomFunction.H>
Public Member Functions
CustomPolarFunction (double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
virtual ~CustomPolarFunction ()
Protected Member Functions
virtual VecMath::Vector< 4 > & f (double, double, double)
Detailed Description
A Function , which the user can edit to have an arbitrary function. The function is interpreted as a four- dimensional polar function, .
Constructor & Destructor Documentation
CustomPolarFunction::CustomPolarFunction (double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
CustomPolarFunction c'tor given a definition set in R³ (as parameter space) and a flag indicating whether this is a test construction or a real one
Parameters:
_tmin minimal value in t
_tmax maximal value in t
_dt stepsize in t
_umin minimal value in u
_umax maximal value in u
_du stepsize in u
_vmin minimal value in v
_vmax maximal value in v
_dv stepsize in v
References Function::Initialize(), PluginCreator::libraryName(), and CustomFunctionBase< Function::raw_function_type >::loadFunction().
CustomPolarFunction::~CustomPolarFunction () [virtual]
CustomPolarFunction destructor, closes DLL if necessary
Member Function Documentation
Vector< 4 > & CustomPolarFunction::f (double x, double y, double z) [protected, virtual]
CustomPolarFunction defining function; calls loaded function
Parameters:
x x value (these would really be phi, theta, psi)
y y value
z z value
Returns:
custom function of (x, y, z)
Reimplemented from CustomFunction.
The documentation for this class was generated from the following files:
workspace/HyperspaceExplorer/src/Functions/CustomFunction.H
workspace/HyperspaceExplorer/src/Functions/CustomFunction.C