HyperspaceExplorer: C4DView Class Reference
C4DView Class Reference
[User Interface]
Displays and manipulates four-dimensional Functions in a QGLWidget.
#include <4DView.H>
Public Slots
void ApplyChanges ()
Called whenever an object or the parameters have changed.
void ParametersChanged (double tmin, double tmax, unsigned tsteps, double umin, double umax, unsigned usteps, double vmin, double vmax, unsigned vsteps, double a, double b, double c, double d, QString &func)
void Wireframe ()
Switch between wireframe and solid display.
void Coordinates ()
switch coordinate cross on or off
void HyperFog ()
switch 4D depth cue on or off
void Light ()
switch lighting on or off
void Colors ()
toggle colors
void Fog ()
Toggle fog/depth cue.
void Transparent ()
toggle object transparency
void Shade ()
toggle shading
void Benchmark ()
run a benchmark test
void RenderToImages ()
switch rendering to files on or off
void FunctionFr3r ()
display a Fr3r object
void FunctionHypersphere ()
display a Hypersphere object
void FunctionTorus1 ()
display a Torus1 object
void FunctionTorus2 ()
display a Torus2 object
void FR3R ()
display a Fr3r object
void GravPotential ()
display a GravPotential object
void SinR ()
display a SinR object
void ExpR ()
display a ExpR object
void Sin ()
display a Sin object
void Sin2 ()
display a Sin2 object
void FunctionR ()
display a FunctionR object
void ObjectHypercube ()
display a ObjectHypercube object
void ObjectHyperpyramid ()
display a ObjectHyperpyramid object
void ObjectHypersponge ()
display a ObjectHypersponge object
void ObjectGasket ()
display a ObjectGasket object
void Surface_1 ()
display a Surface object
void SurfaceHorizon ()
display a SurfaceHorizon object
void SurfaceTorus3 ()
display a SurfaceTorus3 object
void ComplexZ2 ()
display a ComplexZ2 object
void ComplexZ3 ()
display a ComplexZ3 object
void ComplexZA ()
display a ComplexZA object
void ComplexEZ ()
display a ComplexEZ object
void ComplexEMZ2 ()
display a ComplexEMZ2 object
void ComplexZM1 ()
display a ComplexZM1 object
void ComplexZM2 ()
display a ComplexZM2 object
void ComplexSqrtZ ()
display a ComplexSqrtZ object
void ComplexLnZ ()
display a ComplexLnZ object
void ComplexSinZ ()
display a ComplexSinZ object
void ComplexCosZ ()
display a ComplexCosZ object
void ComplexSinhZ ()
display a ComplexSinhZ object
void ComplexCoshZ ()
display a ComplexCoshZ object
void ComplexTanZ ()
display a ComplexTanZ object
void customFunction ()
display a customFunction object
void customPolarFunction ()
display a customPolarFunction object
void customComplexFunction ()
display a customComplexFunction object
void customSurface ()
display a customSurface object
Public Member Functions
C4DView (QWidget *=0)
C4DView constructor.
virtual ~C4DView ()
C4DView destructor.
void SetWireframe (bool wire)
bool GetWireframe (void)
void SetLighting (bool light)
bool GetLighting (void)
void SetDepthCue (bool on)
Toggle depth cue in display and redraw.
void SetRotation (double rx, double ry, double rz)
Set the three-space rotation of the object.
virtual void paintEvent (QPaintEvent *)
virtual void initializeGL (void)
OpenGL initialization.
double Size ()
Get size of displayed area.
void RenderScene (unsigned Frame)
Wrapper for redraw handler.
void Transform (double Rxy, double Rxz, double Rxw, double Ryz, double Ryw, double Rzw, double Tx, double Ty, double Tz, double Tw)
Application of translations and rotations.
void Transform (void)
Overloaded function executing the transform to the default state.
void Redraw ()
Redraw handler.
double Benchmark4D (int, double, double, double, bool=true)
rotate in 4D 360 degrees
double Benchmark3D (int, double, double, double, bool=true)
rotate in 3D 360 degrees
bool getColors () const
bool getShade () const
bool getFog () const
bool getLight () const
bool getTransparent () const
bool getDisplayCoordinates () const
bool getRenderToPixmap () const
bool getDisplayPolygons () const
Menu4D * getMenu () const
Protected Slots
void OnTimer ()
Timer event handler.
void AnimationSettings ()
show a dialog to adjust animation settings
Protected Member Functions
void Project ()
Projects F and coordinate cross into three-space.
void Draw ()
draw the projected Object (onto screen or into GL list, as it is)
void PreRedraw ()
4D projection stuff
QPixmap makePixmap ()
Make a pixmap to to be rendered by the GL widget, and render it.
void writeFrame ()
void DrawCoordinates (void)
draw the coordinate cross (on screen or int GL list) */
void SetupDepthCue (bool)
Switch 3D depth cue on and off.
void StartAnimation ()
void StopAnimation ()
void RandomAnimation ()
Starts a random animation.
void UpdateStatus (QString="")
display some info about current object and its transformations
void AssignValues (const std::auto_ptr< Function > &)
Called whenever an object or the parameters have changed.
void OnPaint ()
Should be called whenever the object is rotated or translated.
virtual void resizeEvent (QResizeEvent *)
Resizing routine.
virtual void mousePressEvent (QMouseEvent *)
Mouse button event handler.
virtual void mouseReleaseEvent (QMouseEvent *)
Mouse button release event handler.
virtual void mouseMoveEvent (QMouseEvent *)
Mouse move event handler.
virtual void mouseDoubleClickEvent (QMouseEvent *)
Double click event handler.
void InitCross ()
Initialize the structures to display a four-dimensional coordinate cross.
Protected Attributes
GLint ObjectList
a GLList for the display of the object
GLint CoordinateCross
a GLList for the display of the coordinates
double Tx
X coordinate for the 4D translation of the object.
double Ty
Y coordinate for the 4D translation of the object.
double Tz
Z coordinate for the 4D translation of the object.
double Tw
W coordinate for the 4D translation of the object.
double Rxy
XY angle for the 4D rotation of the object.
double Rxz
XZ angle for the 4D rotation of the object.
double Rxw
XW angle for the 4D rotation of the object.
double Ryz
YZ angle for the 4D rotation of the object.
double Ryw
YW angle for the 4D rotation of the object.
double Rzw
ZW angle for the 4D rotation of the object.
GLdouble m_rotX
rotation in X
GLdouble m_rotY
rotation in Y
GLdouble m_rotZ
rotation in Z
GLdouble m_transX
translation in X
GLdouble m_transY
translation in Y
GLdouble m_camZ
Z coordinate of the camera (distance from object).
QPoint m_LeftDownPos
position where the LMB press started
QPoint m_MidDownPos
position where the MMB press started
QPoint m_RightDownPos
position where the RMB press started
bool AntiAlias
whether to draw antialiased lines or transparent surfaces
bool DisplayPolygons
whether to draw solid surfaces
bool Lighting
whether to use lights in rendering
bool DepthCue3D
whether to use depth cue
bool DepthCue4D
whether to use depth cue in 4D
bool DisplayCoordinates
whether to show the 4D coordinate cross
bool Animated
whether the image is currently animated
bool TakingSpinValues
true while mouse button pressed and mouse moved to take movement speed
bool RenderToPixmap
whether to save images
bool CurrentlyRendering
whether currently rendering an image
QTimer * AnimationTimer
times out every X ms to draw new animation frame
QTimer * AnimateRandomTimer
times out to change rotation direction
ValuesDialogImpl * Values
dialog to enter function parameters
std::auto_ptr< Function > F
the Function object currently displayed
QString ObjectName
name of current function for status bar
double dxy
delta values in xy rotation angle - for animations
double dxz
delta values in xz rotation angle - for animations
double dxw
delta values in xw rotation angle - for animations
double dyz
delta values in yz rotation angle - for animations
double dyw
delta values in yw rotation angle - for animations
double dzw
delta values in zw rotation angle - for animations
double dx
delta values in x translation - for animations
double dy
delta values in y translation - for animations
double dz
delta values in z translation - for animations
const unsigned animation_fps
frames per second for animations
double CamW
W coordinate of the camera.
double ScrW
W coordinate of the screen.
std::vector< std::vector
< VecMath::Vector< 4 > > > Cross
endpoints of the lines constituting the 4D coordinate cross
std::vector< std::vector
< VecMath::Vector< 4 > > > CrossTrans
endpoints of the lines constituting the transformed 4D coordinates
std::vector< std::vector
< VecMath::Vector< 3 > > > CrossScr
endpoints of the lines constituting the projected 4D coordinates
unsigned animationMaxFrames
limit for saved animation frames
unsigned animationFrame
current frame in animation
QString animationDirectory
where to save the images of an animation
QString animationPrefix
prefix of animation frame filenames
Menu4D * menu
the popup menu
Friends
class FunctionSlot< Fr3r >
class FunctionSlot< Hypersphere >
class FunctionSlot< Torus1 >
class FunctionSlot< Torus2 >
class FunctionSlot< GravitationPotential >
class FunctionSlot< Fr3rSin >
class FunctionSlot< Fr3rExp >
class FunctionSlot< PolarSin >
class FunctionSlot< PolarSin2 >
class FunctionSlot< PolarR >
class FunctionSlot< Surface1 >
class FunctionSlot< Horizon >
class FunctionSlot< Torus3 >
class FunctionSlot< z2 >
class FunctionSlot< z3 >
class FunctionSlot< zA >
class FunctionSlot< ez >
class FunctionSlot< emz2 >
class FunctionSlot< zm1 >
class FunctionSlot< zm2 >
class FunctionSlot< sqrtz >
class FunctionSlot< lnz >
class FunctionSlot< sinz >
class FunctionSlot< cosz >
class FunctionSlot< sinhz >
class FunctionSlot< coshz >
class FunctionSlot< tanz >
class CustomFunctionSlot< CustomFunction >
class CustomFunctionSlot< CustomPolarFunction >
class CustomFunctionSlot< CustomComplexFunction >
class CustomFunctionSlot< CustomSurface >
Classes
class CustomFunctionSlot
Class template to outsource redundant code.
class FunctionSlot
Class template to outsource redundant code.
Detailed Description
Displays and manipulates four-dimensional Functions in a QGLWidget.
This class is much too fat and will be split into parts wherever possible
Todo:
move all menu slots into one (or a few) factory methods
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
C4DView::C4DView (QWidget * parent = 0)
C4DView constructor.
does a lot of initialization to (usually sensible) hardcoded default values, initializes the coordinate cross object (which could well be a class on its own), creates the necessary timers and menus, and finally creates a Hypercube as the default object to display
Parameters:
parent parent QWidget, defaults to NULL
References Menu4D::addToMenuBar(), AnimateRandomTimer, AnimationTimer, ApplyChanges(), InitCross(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), Light(), menu, ObjectHypercube(), OnTimer(), and Values.
Member Function Documentation
void C4DView::SetWireframe (bool wire) [inline]
Parameters:
wire if true, displays wireframe model; else solid
References DisplayPolygons.
Referenced by Wireframe().
bool C4DView::GetWireframe (void) [inline]
Returns:
true if display is set to wireframe, false if solid
References DisplayPolygons.
void C4DView::SetLighting (bool light) [inline]
Parameters:
light whether to use lights in rendering or not
References Lighting.
bool C4DView::GetLighting (void) [inline]
Returns:
whether to use lights in rendering or not
References Lighting.
void C4DView::SetDepthCue (bool on) [inline]
Toggle depth cue in display and redraw.
Parameters:
on whether to use depth cue
References OnPaint(), and SetupDepthCue().
void C4DView::SetRotation (double rx, double ry, double rz) [inline]
Set the three-space rotation of the object.
Parameters:
rx rotation about X-axis
ry rotation about Y-axis
rz rotation about Z-axis
References m_rotX, m_rotY, and m_rotZ.
void C4DView::paintEvent (QPaintEvent *) [virtual]
paintEvent()
References OnPaint().
void C4DView::initializeGL (void) [virtual]
OpenGL initialization.
Now this is not as boring as it seems, because further work has to be done here:
Todo:
trying to check for rendering to file, but this doesn't work yet.
the rest of interesting inits is done in XQGLWidget::initializeGL (), btw.
Reimplemented from XQGLWidget.
References DisplayPolygons, XQGLWidget::initializeGL(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), m_camZ, m_rotX, m_rotY, m_rotZ, m_transX, m_transY, PreRedraw(), RenderScene(), and RenderToPixmap.
Referenced by Colors().
double C4DView::Size ()
Get size of displayed area.
Returns:
approximate diameter of definition space
References ValuesDialogImpl::tmax(), ValuesDialogImpl::tmin(), ValuesDialogImpl::umax(), ValuesDialogImpl::umin(), Values, ValuesDialogImpl::vmax(), and ValuesDialogImpl::vmin().
Referenced by mouseMoveEvent(), resizeEvent(), and SetupDepthCue().
void C4DView::RenderScene (unsigned Frame)
Wrapper for redraw handler.
With an error reporting routine and exit strategy
References CoordinateCross, DisplayCoordinates, Loki::SingletonHolder< T, CreationPolicy >::Instance(), ObjectList, and PreRedraw().
Referenced by initializeGL(), and OnPaint().
void C4DView::Transform (double thetaxy, double thetaxz, double thetaxw, double thetayz, double thetayw, double thetazw, double tx, double ty, double tz, double tw)
Application of translations and rotations.
Calls F->Transform () and transforms the coordinate cross
Parameters:
thetaxy rotation around xy plane (z axis); ignored because 3D rotation takes care of it
thetaxz rotation around xz plane (y axis); ignored because 3D rotation takes care of it
thetaxw rotation around xw plane
thetayz rotation around xy plane (x axis); ignored because 3D rotation takes care of it
thetayw rotation around yw plane
thetazw rotation around zw plane
tx translation in x direction
ty translation in y direction
tz translation in z direction
tw translation in w direction
References Cross, CrossTrans, F, Loki::SingletonHolder< T, CreationPolicy >::Instance(), Rxw, Rxy, Rxz, Ryw, Ryz, and Rzw.
bool C4DView::getColors () const [inline]
Returns:
whether to use colors in rendering or not
bool C4DView::getShade () const [inline]
Returns:
whether to use shading in rendering or not
bool C4DView::getFog () const [inline]
Returns:
whether to use depth cue/fog in rendering or not
bool C4DView::getLight () const [inline]
Returns:
whether to use lighting in rendering or not
bool C4DView::getTransparent () const [inline]
Returns:
whether to use transparence/line antialiasing or not
bool C4DView::getDisplayCoordinates () const [inline]
Returns:
whether to display the 4D coordinate cross or not
References DisplayCoordinates.
bool C4DView::getRenderToPixmap () const [inline]
Returns:
whether to save the rendered images to an image file
References RenderToPixmap.
bool C4DView::getDisplayPolygons () const [inline]
Returns:
whether to draw the objects' surfaces or only the edges
References DisplayPolygons.
Menu4D* C4DView::getMenu () const [inline]
Returns:
a pointer to the popup menu
References menu.
void C4DView::ApplyChanges (void) [slot]
Called whenever an object or the parameters have changed.
Sets the parameters, applies the changed parameters to the function object and redraws it
References ValuesDialogImpl::a(), ValuesDialogImpl::b(), ValuesDialogImpl::c(), ValuesDialogImpl::d(), ValuesDialogImpl::dt(), ValuesDialogImpl::du(), ValuesDialogImpl::dv(), F, Loki::SingletonHolder< T, CreationPolicy >::Instance(), Redraw(), ValuesDialogImpl::tmax(), ValuesDialogImpl::tmin(), Transform(), ValuesDialogImpl::umax(), ValuesDialogImpl::umin(), Values, ValuesDialogImpl::vmax(), and ValuesDialogImpl::vmin().
Referenced by C4DView().
void C4DView::ParametersChanged (double tmin, double tmax, unsigned tsteps, double umin, double umax, unsigned usteps, double vmin, double vmax, unsigned vsteps, double a, double b, double c, double d, QString & func) [slot]
called whenever an object or the parameters have changed; this is the most generalized version, which is great, but sadly it doesn't exist yet
References F.
void C4DView::Project (void) [protected]
Projects F and coordinate cross into three-space.
References CamW, CrossScr, CrossTrans, DepthCue4D, DisplayCoordinates, F, and ScrW.
Referenced by PreRedraw().
void C4DView::Draw (void) [protected]
draw the projected Object (onto screen or into GL list, as it is)
Reimplemented from XQGLWidget.
References DisplayCoordinates, DrawCoordinates(), and F.
Referenced by PreRedraw().
void C4DView::PreRedraw () [protected]
4D projection stuff
Separated from the 3D OpenGL handling into this function
References CoordinateCross, DisplayCoordinates, Draw(), DrawCoordinates(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), ObjectList, and Project().
Referenced by initializeGL(), Redraw(), RenderScene(), and writeFrame().
QPixmap C4DView::makePixmap () [protected]
Make a pixmap to to be rendered by the GL widget, and render it.
this is an embarrassing workaround to make rendering to files work. QGLWidget's renderPixmap() method only produces black frames. Works with QPixmap::grabWindow() instead.
References Loki::SingletonHolder< T, CreationPolicy >::Instance().
Referenced by writeFrame().
void C4DView::writeFrame () [protected]
writes a snapshot of the current frame of an animation or interactive display to disk
updates animationFrame
References animationDirectory, animationFrame, animationMaxFrames, animationPrefix, CurrentlyRendering, Loki::SingletonHolder< T, CreationPolicy >::Instance(), makePixmap(), PreRedraw(), and RenderToPixmap.
Referenced by OnPaint(), and OnTimer().
void C4DView::DrawCoordinates (void) [protected]
draw the coordinate cross (on screen or int GL list) */
References CrossScr, and Loki::SingletonHolder< T, CreationPolicy >::Instance().
Referenced by Draw(), and PreRedraw().
void C4DView::SetupDepthCue (bool on) [protected]
Switch 3D depth cue on and off.
Parameters:
on whether to use fog
References DepthCue3D, Loki::SingletonHolder< T, CreationPolicy >::Instance(), m_camZ, and Size().
Referenced by mouseMoveEvent(), and SetDepthCue().
void C4DView::StartAnimation () [protected]
Err well.. just that! starts AnimationTimer, too...
References Animated, animation_fps, animationFrame, AnimationTimer, Loki::SingletonHolder< T, CreationPolicy >::Instance(), and UpdateStatus().
Referenced by mouseReleaseEvent(), and RandomAnimation().
void C4DView::StopAnimation () [protected]
you guessed it
References Animated, AnimateRandomTimer, AnimationTimer, CurrentlyRendering, dx, dxw, dxy, dxz, dy, dyw, dyz, dz, dzw, and Loki::SingletonHolder< T, CreationPolicy >::Instance().
Referenced by mouseDoubleClickEvent().
void C4DView::RandomAnimation () [protected]
Starts a random animation.
xw/yw/zw rotation speed changes every 10 seconds
Todo:
make hardcoded duration of rotation change frequency adjustable
Todo:
a menu entry for this
References AnimateRandomTimer, AnimationTimer, dxw, dyw, dzw, and StartAnimation().
void C4DView::UpdateStatus (QString status = "") [protected]
display some info about current object and its transformations
In the status bar. Side effect: checks rotation values for overflow and resets them to the interval [-360, 360].
Todo:
Is this wise?
Parameters:
status string to be displayed
References Loki::SingletonHolder< T, CreationPolicy >::Instance(), m_rotX, m_rotY, m_rotZ, ObjectName, Rxw, Ryw, and Rzw.
Referenced by AssignValues(), Benchmark(), Benchmark3D(), Benchmark4D(), C4DView::CustomFunctionSlot< function >::createCustomFunction(), C4DView::CustomFunctionSlot< function >::createCustomSurface(), mouseDoubleClickEvent(), mouseMoveEvent(), mouseReleaseEvent(), OnTimer(), and StartAnimation().
void C4DView::AssignValues (const std::auto_ptr< Function > & F) [protected]
Called whenever an object or the parameters have changed.
Changes the display on the status bar and the number and names of the parameters and grid parameters on the ValuesDialog
Parameters:
F the Function object for which the ValuesDialog is changed
References ValuesDialogImpl::aText(), ValuesDialogImpl::bText(), ValuesDialogImpl::cText(), ValuesDialogImpl::dText(), ObjectName, ValuesDialogImpl::setFunction(), Transform(), UpdateStatus(), and Values.
Referenced by C4DView::CustomFunctionSlot< function >::createCustomFunction(), C4DView::CustomFunctionSlot< function >::createCustomSurface(), C4DView::FunctionSlot< function >::createFunction(), C4DView::FunctionSlot< function >::createSurface(), ObjectGasket(), ObjectHypercube(), ObjectHyperpyramid(), and ObjectHypersponge().
void C4DView::OnPaint () [protected]
Should be called whenever the object is rotated or translated.
References DisplayPolygons, Loki::SingletonHolder< T, CreationPolicy >::Instance(), m_camZ, m_rotX, m_rotY, m_rotZ, m_transX, m_transY, RenderScene(), and writeFrame().
Referenced by Benchmark3D(), Light(), mouseMoveEvent(), OnTimer(), paintEvent(), Redraw(), SetDepthCue(), and Wireframe().
void C4DView::resizeEvent (QResizeEvent * e) [protected, virtual]
Resizing routine.
Also, the definition of the GL viewport is done here
References Size().
void C4DView::mousePressEvent (QMouseEvent * e) [protected, virtual]
Mouse button event handler.
Only sets flags which buttons are down
Parameters:
e Qt's mouse event information structure
Reimplemented from XQGLWidget.
References Loki::SingletonHolder< T, CreationPolicy >::Instance(), m_LeftDownPos, m_MidDownPos, m_RightDownPos, and menu.
void C4DView::mouseReleaseEvent (QMouseEvent * e) [protected, virtual]
Mouse button release event handler.
If taking values for an animation, starts the animation
Parameters:
e Qt's mouse event information structure
Reimplemented from XQGLWidget.
References Loki::SingletonHolder< T, CreationPolicy >::Instance(), StartAnimation(), TakingSpinValues, and UpdateStatus().
void C4DView::mouseMoveEvent (QMouseEvent * e) [protected, virtual]
Mouse move event handler.
Awfully long, which is UGLY, but it does not seem to make much sense to break it up, so here we go
Particular mouse move/button/modifier key combinations documented in the code below
Parameters:
e Qt's mouse event information structure
Reimplemented from XQGLWidget.
References DepthCue3D, dx, dxw, dy, dyw, dz, dzw, Loki::SingletonHolder< T, CreationPolicy >::Instance(), m_camZ, m_LeftDownPos, m_MidDownPos, m_RightDownPos, m_rotX, m_rotY, m_rotZ, m_transX, m_transY, OnPaint(), Redraw(), Rxw, Rxy, Rxz, Ryw, Ryz, Rzw, SetupDepthCue(), Size(), TakingSpinValues, Transform(), Tw, Tx, Ty, Tz, and UpdateStatus().
void C4DView::mouseDoubleClickEvent (QMouseEvent * e) [protected, virtual]
Double click event handler.
Stops animation, if running, or resets transformation values to default
Parameters:
e Qt's mouse event information structure
References Animated, Loki::SingletonHolder< T, CreationPolicy >::Instance(), m_camZ, m_rotX, m_rotY, m_rotZ, m_transX, m_transY, Redraw(), Rxw, Rxy, Rxz, Ryw, Ryz, Rzw, StopAnimation(), Transform(), Tw, Tx, Ty, Tz, and UpdateStatus().
void C4DView::OnTimer () [protected, slot]
Timer event handler.
Updates values if in the middle of an animation, and renders an image.
Writes image to file too, if wanted.
References animationFrame, animationMaxFrames, dx, dxw, dxy, dxz, dy, dyw, dyz, dz, dzw, Loki::SingletonHolder< T, CreationPolicy >::Instance(), m_rotX, m_rotY, m_rotZ, OnPaint(), Redraw(), Rxw, Rxy, Rxz, Ryw, Ryz, Rzw, Transform(), Tw, Tx, Ty, Tz, UpdateStatus(), and writeFrame().
Referenced by C4DView().
void C4DView::AnimationSettings () [protected, slot]
show a dialog to adjust animation settings
Where to write image files and how many files to write
menu callback function
References animationDirectory, animationMaxFrames, animationPrefix, AnimationDialogImpl::getDir(), AnimationDialogImpl::getFrames(), AnimationDialogImpl::getPrefix(), and Loki::SingletonHolder< T, CreationPolicy >::Instance().
void C4DView::Wireframe () [slot]
Switch between wireframe and solid display.
Account for antialiasing only in wireframe mode
Change menu items accordingly
Menu callback function
References DisplayPolygons, Menu4D::getAction(), menu, OnPaint(), SetWireframe(), and Transparent().
void C4DView::Coordinates () [slot]
switch coordinate cross on or off
change menu items accordingly
menu callback function
References DisplayCoordinates, Menu4D::getAction(), menu, and Redraw().
void C4DView::HyperFog () [slot]
switch 4D depth cue on or off
change menu items accordingly
menu callback function
References DepthCue4D, Menu4D::getAction(), menu, and Redraw().
void C4DView::Light () [slot]
switch lighting on or off
change menu items accordingly
menu callback function
References Lighting, and OnPaint().
Referenced by C4DView().
void C4DView::Colors () [slot]
toggle colors
menu callback function
References Menu4D::getAction(), initializeGL(), and menu.
void C4DView::Fog () [slot]
Toggle fog/depth cue.
menu callback function
References Menu4D::getAction(), and menu.
void C4DView::Transparent () [slot]
toggle object transparency
menu callback function
References Menu4D::getAction(), and menu.
Referenced by Wireframe().
void C4DView::Shade () [slot]
toggle shading
menu callback function
References Menu4D::getAction(), and menu.
void C4DView::Benchmark () [slot]
run a benchmark test
menu callback function
References Benchmark3D(), Benchmark4D(), and UpdateStatus().
void C4DView::RenderToImages () [slot]
switch rendering to files on or off
change menu items accordingly
menu callback function
References Menu4D::getAction(), menu, and RenderToPixmap.
void C4DView::FunctionFr3r () [slot]
display a Fr3r object
menu callback function
void C4DView::FunctionHypersphere () [slot]
display a Hypersphere object
menu callback function
void C4DView::FunctionTorus1 () [slot]
display a Torus1 object
menu callback function
void C4DView::FunctionTorus2 () [slot]
display a Torus2 object
menu callback function
void C4DView::FR3R () [slot]
display a Fr3r object
menu callback function
void C4DView::GravPotential () [slot]
display a GravPotential object
menu callback function
void C4DView::SinR () [slot]
display a SinR object
menu callback function
void C4DView::ExpR () [slot]
display a ExpR object
menu callback function
void C4DView::Sin () [slot]
display a Sin object
menu callback function
void C4DView::Sin2 () [slot]
display a Sin2 object
menu callback function
void C4DView::FunctionR () [slot]
display a FunctionR object
menu callback function
void C4DView::ObjectHypercube () [slot]
display a ObjectHypercube object
menu callback function
References ValuesDialogImpl::a(), AssignValues(), F, menu, Redraw(), Menu4D::updateFunctionMenu(), and Values.
Referenced by C4DView().
void C4DView::ObjectHyperpyramid () [slot]
display a ObjectHyperpyramid object
menu callback function
References ValuesDialogImpl::a(), AssignValues(), F, menu, Redraw(), Menu4D::updateFunctionMenu(), and Values.
void C4DView::ObjectHypersponge () [slot]
display a ObjectHypersponge object
menu callback function
References AssignValues(), F, menu, Redraw(), and Menu4D::updateFunctionMenu().
void C4DView::ObjectGasket () [slot]
display a ObjectGasket object
menu callback function
References ValuesDialogImpl::a(), AssignValues(), ValuesDialogImpl::b(), F, menu, Redraw(), Menu4D::updateFunctionMenu(), and Values.
void C4DView::Surface_1 () [slot]
display a Surface object
menu callback function
void C4DView::SurfaceHorizon () [slot]
display a SurfaceHorizon object
menu callback function
void C4DView::SurfaceTorus3 () [slot]
display a SurfaceTorus3 object
menu callback function
void C4DView::ComplexZ2 () [slot]
display a ComplexZ2 object
menu callback function
void C4DView::ComplexZ3 () [slot]
display a ComplexZ3 object
menu callback function
void C4DView::ComplexZA () [slot]
display a ComplexZA object
menu callback function
void C4DView::ComplexEZ () [slot]
display a ComplexEZ object
menu callback function
void C4DView::ComplexEMZ2 () [slot]
display a ComplexEMZ2 object
menu callback function
void C4DView::ComplexZM1 () [slot]
display a ComplexZM1 object
menu callback function
void C4DView::ComplexZM2 () [slot]
display a ComplexZM2 object
menu callback function
void C4DView::ComplexSqrtZ () [slot]
display a ComplexSqrtZ object
menu callback function
void C4DView::ComplexLnZ () [slot]
display a ComplexLnZ object
menu callback function
void C4DView::ComplexSinZ () [slot]
display a ComplexSinZ object
menu callback function
void C4DView::ComplexCosZ () [slot]
display a ComplexCosZ object
menu callback function
void C4DView::ComplexSinhZ () [slot]
display a ComplexSinhZ object
menu callback function
void C4DView::ComplexCoshZ () [slot]
display a ComplexCoshZ object
menu callback function
void C4DView::ComplexTanZ () [slot]
display a ComplexTanZ object
menu callback function
void C4DView::customFunction () [slot]
display a customFunction object
menu callback function
void C4DView::customPolarFunction () [slot]
display a customPolarFunction object
menu callback function
void C4DView::customComplexFunction () [slot]
display a customComplexFunction object
menu callback function
void C4DView::customSurface () [slot]
display a customSurface object
menu callback function
The documentation for this class was generated from the following files:
workspace/HyperspaceExplorer/src/UI/4DView.H
workspace/HyperspaceExplorer/src/UI/4DView.C