HyperspaceExplorer: UI::View Class Reference
UI::View Class Reference
[User Interface]
Interface to display four-dimensional objects.
#include <View.H>
Public Member Functions
virtual const std::auto_ptr
< Function > & F () const =0
virtual void setF (Function *f)=0
Set the currently displayed object to the given Function.
virtual void ObjectHypercube ()=0
Set the currently displayed object to a hypercube.
virtual void ObjectHyperpyramid ()=0
Set the currently displayed object to a hypersimplex.
virtual void ObjectHypersponge ()=0
Set the currently displayed object to a hyper-menger sponge.
virtual void ObjectGasket ()=0
Set the currently displayed object to a hyper-sierpinski gasket.
virtual void ObjectRotope ()=0
Set the currently displayed object to a rotope.
template<typename T>
void setParameter (const std::string &parmName, const T &value)
Makes setting a parameter from the outside possible.
virtual void applyTransform (const VecMath::Rotation< 4 > &R, const VecMath::Vector< 4 > &T)=0
Apply the given Transformation to the currently displayed object.
virtual const
VecMath::Rotation< 4 > & getdR ()=0
virtual void setdR (const VecMath::Rotation< 4 > &_dr)=0
Set the rotation step between frames for animations.
virtual void setNumFrames (unsigned _numFrames)=0
Set the number of frames for an animation.
virtual void setNumLoops (unsigned _numLoops)=0
Set the number of times _numFrames are repeated.
virtual void animate ()=0
Start the animation with the currently active values.
virtual void setSize (unsigned, unsigned)=0
Set the width and height of the viewport.
virtual const std::string & getImgDir ()=0
virtual void setImgDir (const std::string &)=0
Set the directory where to store image files.
virtual const std::string & getImgPrefix ()=0
virtual void setImgPrefix (const std::string &)=0
Set the prefix of image file names, before the frame number and the extension.
virtual void setBackground (const Color &)=0
Set the background color.
virtual const Color & getBackground ()=0
virtual void addLight (Light *)=0
Add a light source to the scene.
virtual void removeLight (std::vector< Light * >::iterator)=0
Remove a light source from the scene.
virtual const std::vector
< Light * > & getLights ()=0
virtual bool getColors () const =0
virtual void setColors (bool)=0
Turn display of colors in rendering on or off.
virtual bool getCoordinates () const =0
virtual void setCoordinates (bool)=0
Turn display of 4D coordinate cross on or off.
virtual bool getFog () const =0
virtual void setFog (bool)=0
Turn depth cue on or off.
virtual bool getHyperfog () const =0
virtual void setHyperfog (bool)=0
Turn depth cue in four dimensions on or off.
virtual bool getLighting () const =0
virtual void setLighting (bool)=0
Turn lighting on or off.
virtual bool getShading () const =0
virtual void setShading (bool)=0
Turn gouraud shading on or off.
virtual bool getSolid () const =0
virtual void setSolid (bool on)=0
Turn wireframe display on or off.
virtual bool getTransparence () const =0
virtual void setTransparence (bool)=0
Turn transparence/line antialiasing on or off.
Protected Member Functions
virtual void ApplyChanges (const ParameterMap &)=0
Apply changes in parameters and display them.
virtual unsigned getNumFrames ()=0
Number of frames for animations.
virtual unsigned getNumLoops ()=0
Number of loops to repeat an animation.
virtual bool getWriteImages ()=0
virtual void setWriteImages (bool)=0
Turn saving images to file system on or off.
virtual void setDefaultBackground ()=0
Set a default background color.
Classes
class FunctionNotSupportedException
Thrown when a function is not supported by a View implementation.
Detailed Description
Interface to display four-dimensional objects.
Provides functions to display Function objects, transform them and animate them. Also to set various viewing states.
Member Function Documentation
virtual const std::auto_ptr<Function>& UI::View::F () const [pure virtual]
Returns:
The currently displayed object
Implemented in UI::ViewImpl.
virtual void UI::View::setF (Function * f) [pure virtual]
Set the currently displayed object to the given Function.
Parameters:
f The object to be set
Implemented in UI::ViewImpl.
Referenced by Script::ObjectStmt::execute().
virtual void UI::View::ObjectHypercube () [pure virtual]
Set the currently displayed object to a hypercube.
Necessary because I don't see a way to set the displayed object to a generic Object, only to Function s
Implemented in C4DView.
virtual void UI::View::ObjectHyperpyramid () [pure virtual]
Set the currently displayed object to a hypersimplex.
Necessary because I don't see a way to set the displayed object to a generic Object, only to Function s
Implemented in C4DView.
virtual void UI::View::ObjectHypersponge () [pure virtual]
Set the currently displayed object to a hyper-menger sponge.
Necessary because I don't see a way to set the displayed object to a generic Object, only to Function s
Implemented in C4DView.
virtual void UI::View::ObjectGasket () [pure virtual]
Set the currently displayed object to a hyper-sierpinski gasket.
Necessary because I don't see a way to set the displayed object to a generic Object, only to Function s
Implemented in C4DView.
virtual void UI::View::ObjectRotope () [pure virtual]
Set the currently displayed object to a rotope.
Necessary because I don't see a way to set the displayed object to a generic Object, only to Function s
Implemented in C4DView.
template<typename T> void UI::View::setParameter (const std::string & parmName, const T & value) [inline]
Makes setting a parameter from the outside possible.
Parameters:
parmName Name of the parameter, as defined in the Function
value Parameter value. Type must match exactly.
References ApplyChanges().
Referenced by Script::ParmStmt< T >::execute().
virtual void UI::View::applyTransform (const VecMath::Rotation< 4 > & R, const VecMath::Vector< 4 > & T) [pure virtual]
Apply the given Transformation to the currently displayed object.
The object is redrawn after the Transformation.
Parameters:
R Rotation to be performed on the object
T Translation to be applied to the object
Implemented in C4DView.
Referenced by Script::XformStmt::execute().
virtual const VecMath::Rotation<4>& UI::View::getdR () [pure virtual]
Returns:
delta values in angles for 4D rotation for animations
Implemented in UI::ViewImpl.
virtual void UI::View::setdR (const VecMath::Rotation< 4 > & _dr) [pure virtual]
Set the rotation step between frames for animations.
Parameters:
_dr Rotation step between two frames of an animation
Implemented in UI::ViewImpl.
Referenced by Script::DeltaStmt::execute().
virtual const std::string& UI::View::getImgDir () [pure virtual]
Returns:
directory to save images to
Implemented in UI::ViewImpl.
virtual const std::string& UI::View::getImgPrefix () [pure virtual]
Returns:
filename prefix for saved images
Implemented in UI::ViewImpl.
virtual const Color& UI::View::getBackground () [pure virtual]
Returns:
The background color
Implemented in UI::ViewImpl.
virtual const std::vector<Light *>& UI::View::getLights () [pure virtual]
Returns:
All lights in the scene
Todo:
Abstract from std::vector and use a generic container
Implemented in UI::ViewImpl.
virtual bool UI::View::getColors () const [pure virtual]
Returns:
whether to use colors in rendering or not
Implemented in UI::ViewImpl.
virtual bool UI::View::getCoordinates () const [pure virtual]
Returns:
whether to display the 4D coordinate cross or not
Implemented in UI::ViewImpl.
virtual bool UI::View::getFog () const [pure virtual]
Returns:
whether to use depth cue/fog in rendering or not
Implemented in UI::ViewImpl.
virtual bool UI::View::getHyperfog () const [pure virtual]
Returns:
whether to use four-dimensional depth cue or not
Implemented in UI::ViewImpl.
virtual bool UI::View::getLighting () const [pure virtual]
Returns:
whether to use lighting in rendering or not
Implemented in UI::ViewImpl.
virtual bool UI::View::getShading () const [pure virtual]
Returns:
whether to use shading in rendering or not
Implemented in UI::ViewImpl.
virtual bool UI::View::getSolid () const [pure virtual]
Returns:
whether to draw the objects' surfaces
Implemented in UI::ViewImpl.
virtual void UI::View::setSolid (bool on) [pure virtual]
Turn wireframe display on or off.
Parameters:
on if true, displays wireframe model; else solid
Implemented in UI::ViewImpl.
Referenced by Script::SolidStmt::execute(), and Script::WireStmt::execute().
virtual bool UI::View::getTransparence () const [pure virtual]
Returns:
whether to use transparence/line antialiasing or not
Implemented in UI::ViewImpl.
virtual bool UI::View::getWriteImages () [protected, pure virtual]
Returns:
whether to save images to file system
Implemented in UI::ViewImpl.
The documentation for this class was generated from the following file:
HyperspaceExplorer/src/UI/View.H