HyperspaceExplorer: Script::SizeStmt Class Reference
Script::SizeStmt Class Reference
[Statements possible in a script]
"size <width> <height>"
#include <Statement.H>
Public Member Functions
SizeStmt (const Parser *p, const std::string &_arg)
virtual bool execute ()
Executes the statement in the current context.
Private Attributes
unsigned _width
Width of the viewport.
unsigned _height
Height of the viewport.
Detailed Description
"size <width> <height>"
sets the width and height of the viewport
Constructor & Destructor Documentation
Script::SizeStmt::SizeStmt (const Parser * p, const std::string & _arg)
Parameters:
p The context in which the Statement is executed
_arg The argument supplied to the Statement
References _height, _width, Script::Statement::arg(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), Script::leading(), and Script::trailing().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Script/Statement.H
HyperspaceExplorer/src/Script/Statement.C