HyperspaceExplorer: FunctionParameter Class Reference
FunctionParameter Class Reference
[A generalized interface for function parameters of arbitrary type]
A parameter to a Function with a name, an optional description and a default.
#include <FunctionParameter.H>
Public Member Functions
FunctionParameter (const std::string &_name, const std::string &_description="")
operator double ()
get the value if it is of type double
operator unsigned ()
get the value if it is of type unsigned
operator int ()
get the value if it is of type int
operator std::string ()
get the value if it is of type std::string
const std::string & getName () const
get the name of the function parameter
void setName (const std::string &_name)
set the name of the function parameter
const std::string & getDescription () const
get the long description of the function parameter
void setDescription (const std::string &_description)
set the long description of the function parameter
template<typename T>
void setValue (FunctionParameterValue< T > *_value)
set the value of the parameter.
void setValue (std::string _value)
Set a value from a string, as contained in a QLineEdit.
template<typename T>
void setDefaultValue (FunctionParameterValue< T > *_defaultValue)
set the default value of the parameter.
FunctionParameterValueBase * value () const
FunctionParameterValueBase * defaultValue () const
Private Attributes
Impl * pImpl
Classes
struct Impl
Data members for class FunctionParameter.
Detailed Description
A parameter to a Function with a name, an optional description and a default.
This class stores a FunctionParameterValue for the value of the parameter, and one for its default value. It also stores strings to provide the name of the parameter and one for the optional description.
It provides access to the parameter values through the type cast operators. These are delegated to the cast operators of the value member.
Write access is not so convenient, because it requires an object of type FunctionParameterValue<T>, which must be created with a call to ParameterFac::createParameterWithValue(). Pass that pointer to setValue().
There are also getters and setters for name and description, of course.
This class uses the Pimpl idiom to ensure encapsulation. It may do a bad job at it, this is my first go at a pimpl class. The data members are hidden in a private struct FunctionParameter::Impl.
See also:
FunctionParameterValueBase
Member Function Documentation
template<typename T> void FunctionParameter::setValue (FunctionParameterValue< T > * _value) [inline]
set the value of the parameter.
Requires a pointer created by ParameterFac::createParameterWithValue().
Todo:
Can't I call createParameterWithValue() from inside setValue()?
References std::auto_ptr< _Tp >::reset(), and FunctionParameter::Impl::value.
Referenced by ParameterFac::createParameterWithDefault(), and ParameterFac::createParameterWithValue().
template<typename T> void FunctionParameter::setDefaultValue (FunctionParameterValue< T > * _defaultValue) [inline]
set the default value of the parameter.
Requires a pointer created by ParameterFac::createParameterWithDefault().
Todo:
Can't I call createParameterWithDefault() from inside setDefaultValue()?
References FunctionParameter::Impl::defaultValue, and std::auto_ptr< _Tp >::reset().
Referenced by ParameterFac::createParameterWithDefault().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Functions/FunctionParameter.H
HyperspaceExplorer/src/Functions/FunctionParameter.C