HyperspaceExplorer: Box< D > Class Template Reference
Box< D > Class Template Reference
Hypercube of dimension D, which contains a number of Balls.
#include <Box.H>
Public Member Functions
Box (unsigned n=1)
virtual void draw ()
virtual void step (const double &dt)
virtual void setNumBalls (unsigned n)
virtual unsigned getNumBalls ()
virtual unsigned getDimension ()
virtual void setXCam (const double &_Xcam)
virtual double * getXCam ()
Static Public Member Functions
static Vec< D > project (unsigned d, const Vec< D > &X, const double &r, Vec< D > &Xproj, double &rproj)
Static Public Attributes
static Vec< D > vertices [1<< D]
Protected Member Functions
Ball< D > * makeBall ()
void addBall ()
void deleteBall ()
void collide (Vec< D > &, Vec< D > &, Vec< D > &, const double &, const double &)
void rotate (Vec< D >[1<< D])
Static Protected Member Functions
static void DefineHypercube ()
Protected Attributes
Vec< D > Xmin
Vec< D > Xmax
vector< Ball< D > * > balls
Static Protected Attributes
static Vec< D > vtrans [1<< D]
static matrix< D > R
static double Xcam [D]
Detailed Description
template<unsigned D>
class Box< D >
Hypercube of dimension D, which contains a number of Balls.
Constructor & Destructor Documentation
template<unsigned D> Box< D >::Box (unsigned n = 1) [inline]
Todo:
document me
References Box< D >::DefineHypercube(), Box< D >::setNumBalls(), Box< D >::vertices, Box< D >::Xmax, and Box< D >::Xmin.
Member Function Documentation
template<unsigned D> void Box< D >::draw () [inline, virtual]
Todo:
document me
Implements BoxBase.
References Box< D >::balls, Box< D >::project(), Box< D >::rotate(), std::vector< _Tp, _Alloc >::size(), Box< D >::vertices, and Box< D >::vtrans.
template<unsigned D> void Box< D >::step (const double & dt) [inline, virtual]
Todo:
document me
Implements BoxBase.
References Box< D >::balls, Box< D >::collide(), cout, BoxBase::elasticity, endl(), exit(), BoxBase::friction, BoxBase::gravity, BoxBase::max_t, BoxBase::num_collisions, std::vector< _Tp, _Alloc >::size(), BoxBase::sloppy, BoxBase::t, Box< D >::Xmax, and Box< D >::Xmin.
template<unsigned D> void Box< D >::setNumBalls (unsigned n) [inline, virtual]
Todo:
document me
Implements BoxBase.
References Box< D >::addBall(), Box< D >::balls, Box< D >::deleteBall(), and std::vector< _Tp, _Alloc >::size().
Referenced by Box< D >::Box().
template<unsigned D> virtual unsigned Box< D >::getNumBalls () [inline, virtual]
Todo:
document me
Implements BoxBase.
References Box< D >::balls, and std::vector< _Tp, _Alloc >::size().
template<unsigned D> virtual unsigned Box< D >::getDimension () [inline, virtual]
Todo:
document me
Implements BoxBase.
template<unsigned D> virtual void Box< D >::setXCam (const double & _Xcam) [inline, virtual]
Todo:
document me
Implements BoxBase.
References Box< D >::Xcam.
template<unsigned D> virtual double* Box< D >::getXCam () [inline, virtual]
Todo:
document me
Implements BoxBase.
References Box< D >::Xcam.
template<unsigned D> Vec< D > Box< D >::project (unsigned d, const Vec< D > & X, const double & r, Vec< D > & Xproj, double & rproj) [inline, static]
Todo:
document me
References Box< D >::R, and Box< D >::Xcam.
Referenced by Box< D >::draw(), and Ball< D >::draw().
template<unsigned D> Ball< D > * Box< D >::makeBall () [inline, protected]
Todo:
document me
References Box< D >::balls, BallBase::r, and std::vector< _Tp, _Alloc >::size().
Referenced by Box< D >::addBall().
template<unsigned D> void Box< D >::addBall () [inline, protected]
Todo:
document me
References Box< D >::balls, Box< D >::makeBall(), and std::vector< _Tp, _Alloc >::push_back().
Referenced by Box< D >::setNumBalls().
template<unsigned D> void Box< D >::deleteBall () [inline, protected]
Todo:
document me
References Box< D >::balls, std::vector< _Tp, _Alloc >::pop_back(), and std::vector< _Tp, _Alloc >::size().
Referenced by Box< D >::setNumBalls().
template<unsigned D> void Box< D >::collide (Vec< D > & v1, Vec< D > & v2, Vec< D > & dx, const double & m1, const double & m2) [inline, protected]
Todo:
document me
References BoxBase::elasticity.
Referenced by Box< D >::step().
template<unsigned D> void Box< D >::rotate (Vec< D > vtrans[1<< D]) [inline, protected]
Todo:
document me
References Box< D >::R, and BoxBase::t.
Referenced by Box< D >::draw().
template<unsigned D> void Box< D >::DefineHypercube () [inline, static, protected]
Todo:
document me
References Box< D >::vertices.
Referenced by Box< D >::Box().
Member Data Documentation
template<unsigned D> Vec< 9 > Box< D >::vertices [static]
Todo:
document me
Referenced by Box< D >::Box(), Box< D >::DefineHypercube(), and Box< D >::draw().
template<unsigned D> Vec<D> Box< D >::Xmin [protected]
Todo:
document me
Referenced by Box< D >::Box(), and Box< D >::step().
template<unsigned D> Vec<D> Box< D >::Xmax [protected]
Todo:
document me
Referenced by Box< D >::Box(), and Box< D >::step().
template<unsigned D> vector<Ball<D> *> Box< D >::balls [protected]
Todo:
document me
Referenced by Box< D >::addBall(), Box< D >::deleteBall(), Box< D >::draw(), Box< D >::getNumBalls(), Box< D >::makeBall(), Box< D >::setNumBalls(), and Box< D >::step().
template<unsigned D> Vec< 9 > Box< D >::vtrans [static, protected]
Todo:
document me
Referenced by Box< D >::draw().
template<unsigned D> matrix< 9 > Box< D >::R [static, protected]
Todo:
document me
Referenced by Box< D >::project(), and Box< D >::rotate().
template<unsigned D> double Box< D >::Xcam [static, protected]
Todo:
document me
Referenced by Box< D >::getXCam(), Box< D >::project(), and Box< D >::setXCam().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Balls/Box.H
HyperspaceExplorer/src/Balls/Box.C