HyperspaceExplorer: Script::XformStmt Class Reference
Script::XformStmt Class Reference
[Statements possible in a script]
"transform <rotation>"
#include <Statement.H>
Public Member Functions
XformStmt (const Parser *p, const std::string &_arg)
virtual bool execute ()
Executes the statement in the current context.
Protected Member Functions
VecMath::Rotation< 4 > & r ()
Private Attributes
VecMath::Rotation< 4 > _r
The rotation state of the object.
Detailed Description
"transform <rotation>"
sets the transform of the current object
Todo:
add support for translations and 3D rotation
Constructor & Destructor Documentation
Script::XformStmt::XformStmt (const Parser * p, const std::string & _arg)
Parameters:
p The context in which the Statement is executed
_arg The argument supplied to the Statement
References _r, and Script::Statement::arg().
Member Function Documentation
VecMath::Rotation<4>& Script::XformStmt::r () [inline, protected]
Returns:
The rotation state of the object
References _r.
Referenced by Script::DeltaStmt::execute(), and execute().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Script/Statement.H
HyperspaceExplorer/src/Script/Statement.C