HyperspaceExplorer: C4DView::CustomFunctionSlot< function > Class Template Reference
C4DView::CustomFunctionSlot< function > Class Template Reference
[Helper classes for User Interface classes]
Class template to outsource redundant code for customized functions.
Static Public Member Functions
static void createCustomFunction (C4DView *view)
C++ Template Implementation: CustomFunctionSlot.
static void createCustomSurface (C4DView *view)
Factory method to create a new customized Function of type R^2->R^4.
Detailed Description
template<class function>
class C4DView::CustomFunctionSlot< function >
Class template to outsource redundant code for customized functions.
Redundant code for the generation of customized functions is moved to a slot called by QActions from the QMenu
Parameters:
function the Function to be created in the slot
Member Function Documentation
template<class function> void C4DView::CustomFunctionSlot< function >::createCustomSurface (C4DView * view) [inline, static]
Factory method to create a new customized Function of type R^2->R^4.
This function template is called by each slot with the correct function type as template parameter.
Sets F to the newly created Function, checks the corresponding menu item, updates the ValuesDialog and redraws. Does some error handling in case the Function could not be loaded.
References C4DView::AssignValues(), UI::Dialogs::ValuesDialogImpl::dt(), UI::Dialogs::ValuesDialogImpl::du(), UI::ViewImpl::F(), C4DView::Redraw(), UI::ViewImpl::setF(), UI::Dialogs::ValuesDialogImpl::tmax(), UI::Dialogs::ValuesDialogImpl::tmin(), UI::Dialogs::ValuesDialogImpl::umax(), UI::Dialogs::ValuesDialogImpl::umin(), C4DView::UpdateStatus(), and C4DView::Values().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/UI/4DView.H
HyperspaceExplorer/src/UI/CustomFunctionSlot.impl.H