HyperspaceExplorer: extrude_base< D > Class Template Reference
extrude_base< D > Class Template Reference
[N-dimensional Rotopes.]
Base class for Extrude classes, providing the actual extrude() function.
#include <Extrude.H>
Public Member Functions
extrude_base ()
Create an empty extrude_base object.
extrude_base (const vertex_data< D > &v)
Create an extrude_base object from an already existing object.
void extrude (unsigned d)
Extrudes an object along a given dimension.
Detailed Description
template<unsigned D>
class extrude_base< D >
Base class for Extrude classes, providing the actual extrude() function.
Author:
Helge Preuss <scout@hyperspace-travel.de>
Member Function Documentation
template<unsigned D> void extrude_base< D >::extrude (unsigned d) [inline]
Extrudes an object along a given dimension.
For each point in the vertex array, a copy is made and shifted along the d axis. Thus, a point becomes a line when extruded along axis 0, a line becomes a square when extruded along axis 1, and so on. A circle becomes a cylinder when extruded along axis 2, and similarly with all kinds of objects. You get the idea.
Parameters:
d The new dimension into which the object is extruded
Extrude vertices into the d axis, setting the d coordinate to 1
Extrude surfaces from each edge of the base surface to its image
add all surfaces which were in the old vertex array, but extruded along the d axis. This is achieved by copying the old surface array and adding the size of the old vertex array to each of the indices therein.
Remove double surfaces from area
References vertex_data< D >::addSurface(), vertex_data< D >::dimension(), std::vector< _Tp, _Alloc >::push_back(), vertex_data< D >::surface(), and vertex_data< D >::X().
Referenced by Extrude< D, Dmin, Dmin >::Extrude(), and Extrude< D, Dmin, Dmax >::Extrude().
The documentation for this class was generated from the following file:
HyperspaceExplorer/src/Functions/Extrude.H