HyperspaceExplorer: Gasket Class Reference
Gasket Class Reference
[Arbitrary four-dimensional objects, described by their surfaces]
#include <Object.H>
Public Member Functions
Gasket (unsigned level=1, double rad=1, VecMath::Vector< 4 > Center=VecMath::Vector< 4 >(0., 0., 0., 0.))
virtual void Transform (double Rxy, double Rxz, double Rxw, double Ryz, double Ryw, double Rzw, double Tx, double Ty, double Tz, double Tw)
virtual void Project (double ScrW, double CamW, bool DepthCue4D)
virtual void Draw (void)
virtual void SetParameters (double _a=0, double _b=0, double=0, double=0)
virtual void ReInit (double, double, double, double, double, double, double, double, double)
Protected Member Functions
virtual void Initialize ()
virtual unsigned long MemRequired (void)
Protected Attributes
unsigned Level
std::vector< Pyramid * > List
double rad
VecMath::Vector< 4 > center
Detailed Description
A four-dimensional version of the Sierpinski Gasket.
It is similar to the Menger Sponge, but it uses a Hypersimplex as generator.
Member Function Documentation
void Gasket::Transform (double Thetaxy, double Thetaxz, double Thetaxw, double Thetayz, double Thetayw, double Thetazw, double Tx, double Ty, double Tz, double Tw) [virtual]
transforms a Gasket
Parameters:
thetaxy rotation around xy plane (z axis); ignored because 3D rotation takes care of it
thetaxz rotation around xz plane (y axis); ignored because 3D rotation takes care of it
thetaxw rotation around xw plane
thetayz rotation around xy plane (x axis); ignored because 3D rotation takes care of it
thetayw rotation around yw plane
thetazw rotation around zw plane
tx translation in x direction
ty translation in y direction
tz translation in z direction
tw translation in w direction
Reimplemented from Object.
References Transform().
Referenced by Transform().
void Gasket::Project (double scr_w, double cam_w, bool depthcue4d) [virtual]
projects a Gasket into three-space
Parameters:
scr_w w coordinate of screen
cam_w w coordinate of camera
depthcue4d wheter to use hyperfog/dc
Reimplemented from Object.
void Gasket::Draw (void) [virtual]
draw the projected Gasket (onto screen or into GL list, as it is)
Reimplemented from Object.
virtual void Gasket::SetParameters (double _a = 0, double _b = 0, double _c = 0, double _d = 0) [inline, virtual]
placeholder for function to set parameters in descendants - empty because a generic function has no parameters
Parameters:
_a 1st parameter
_b 2nd parameter
_c 3rd parameter
_d 4th parameter
Reimplemented from Pyramid.
virtual void Gasket::ReInit (double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv) [inline, virtual]
re-initialize a Function if the definition set has changed
Parameters:
tmin minimal value in t
tmax maximal value in t
dt stepsize in t
umin minimal value in u
umax maximal value in u
du stepsize in u
vmin minimal value in v
vmax maximal value in v
dv stepsize in v
Reimplemented from Object.
References Object::ReInit().
void Gasket::Initialize (void) [protected, virtual]
See also:
Sponge::Initialize()
Reimplemented from Pyramid.
References Loki::SingletonHolder< T, CreationPolicy >::Instance(), and MemRequired().
unsigned long Gasket::MemRequired (void) [protected, virtual]
return the approximate amount of memory needed to display a gasket of current level
Todo:
uses hardcoded and experimentally found value for memory per simplex
Returns:
approx. mem required
Reimplemented from Function.
Referenced by Initialize().
The documentation for this class was generated from the following files:
workspace/HyperspaceExplorer/src/Functions/Object.H
workspace/HyperspaceExplorer/src/Functions/Object.C