HyperspaceExplorer: CustomComplexFunction Class Reference
CustomComplexFunction Class Reference
[Functions C -> C]
#include <CustomFunction.H>
Public Member Functions
CustomComplexFunction (double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
Protected Attributes
ComplexFunction::function_type g
Detailed Description
A Function , which the user can edit to have an arbitrary function.
Constructor & Destructor Documentation
CustomComplexFunction::CustomComplexFunction (double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
CustomComplexFunction c'tor given a definition set in C (as parameter space) and a flag indicatin whether this is a test construction or a real one
Parameters:
_umin minimal value in u
_umax maximal value in u
_du stepsize in u
_vmin minimal value in v
_vmax maximal value in v
_dv stepsize in v
References ComplexFunction::Initialize(), UI::Dialogs::PluginCreator::libraryName(), CustomFunctionBase< ComplexFunction::function_type >::loadFunction(), CustomFunctionBase< ComplexFunction::function_type >::setInvalid(), and CustomFunctionBase< ComplexFunction::function_type >::setValid().
Member Data Documentation
complex< double > CustomComplexFunction::g [protected]
CustomComplexFunction defining function; calls loaded function
Parameters:
z (complex) z value
Returns:
custom function of z
Reimplemented from ComplexFunction.
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Functions/CustomFunction.H
HyperspaceExplorer/src/Functions/CustomFunction.C