HyperspaceExplorer: RealFunction Class Reference
RealFunction Class Reference
[Functions R^3 -> R]
A RealFunction is a mathematical function .
#include <RealFunction.H>
Public Member Functions
RealFunction (const QString &name)
RealFunction (const QString &name, double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv, ParameterMap _parms=ParameterMap())
virtual void Transform (const VecMath::Rotation< 4 > &R, const VecMath::Vector< 4 > &T)
Transforms a RealFunction.
virtual void Project (double ScrW, double CamW, bool DepthCue4D)
Projects a RealFunction into three-space.
virtual void Draw (void)
Draw the projected Function (onto screen or into GL list, as it is).
virtual void ReInit (double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
Re-initialize a RealFunction if the definition set has changed.
virtual const unsigned getDefinitionSpaceDimensions ()
Protected Member Functions
VecMath::Vector< 4 > & normal (double t, double u, double v)
Calculate normal to function at a given point in definition set.
void DrawPlane (unsigned)
Draw the current plane of the projected Function.
void DrawStrip (unsigned, unsigned)
Draw the current strip of the projected Function.
void DrawCube (unsigned, unsigned, unsigned)
Draw the current cube or cell of the projected Function.
virtual void Initialize (void)
Allocate and initialize X[][][] with values of f().
virtual void InitMem (void)
Initialize the temporary storage areas.
Protected Attributes
vec4vec3D X
temporary storage for function values on grid
vec4vec3D Xtrans
temporary storage for transformed function values
vec3vec3D Xscr
temporary storage for projected function values temporary storage for the value of the function at a given point
VecMath::Vector< 4 > F
temporary storage for the value of the function at a given point
Detailed Description
A RealFunction is a mathematical function .
The function f is evaluated on a 3-dimensional cartesian grid. The function value constitutes the fourth dimension of the Function object: .
The parent class Function provides the evaluation on the grid, together with methods to rotate and translate the grid in 4-space, to project the transformed grid onto 3-space, and to draw the projected grid into an OpenGL display list.
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
RealFunction::RealFunction (const QString & _name)
RealFunction c'tor given only a name: All grid values are set to defaults
Parameters:
_name a name for the function
RealFunction::RealFunction (const QString & _name, double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv, ParameterMap _parms = ParameterMap())
RealFunction c'tor given a definition set in R³ (as parameter space)
Parameters:
_name a name for the function
_tmin minimal value in t
_tmax maximal value in t
_dt stepsize in t
_umin minimal value in u
_umax maximal value in u
_du stepsize in u
_vmin minimal value in v
_vmax maximal value in v
_dv stepsize in v
_parms function parameters
References cerr, endl(), RealBase::getDt(), RealBase::getDu(), RealBase::getDv(), RealBase::getTmax(), RealBase::getTmin(), RealBase::getTsteps(), RealBase::getUmax(), RealBase::getUmin(), RealBase::getUsteps(), RealBase::getVmax(), RealBase::getVmin(), RealBase::getVsteps(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), and Function::MemRequired().
Member Function Documentation
void RealFunction::Draw (void) [virtual]
Draw the projected Function (onto screen or into GL list, as it is).
Implements Function.
References DrawPlane(), and RealBase::getTsteps().
void RealFunction::DrawCube (unsigned t, unsigned u, unsigned v) [protected]
Draw the current cube or cell of the projected Function.
Parameters:
t current t value
u current u value
v current v value
References Function::addVertices(), Function::setVertex(), X, and Xscr.
Referenced by DrawStrip().
void RealFunction::DrawPlane (unsigned t) [protected]
Draw the current plane of the projected Function.
Parameters:
t current t value
References DrawStrip(), and RealBase::getUsteps().
Referenced by Draw().
void RealFunction::DrawStrip (unsigned t, unsigned u) [protected]
Draw the current strip of the projected Function.
Parameters:
t current t value
u current u value
References DrawCube(), and RealBase::getVsteps().
Referenced by DrawPlane().
virtual const unsigned RealFunction::getDefinitionSpaceDimensions () [inline, virtual]
See also:
Function::getDefinitionSpaceDimensions()
Implements Function.
void RealFunction::Initialize (void) [protected, virtual]
Allocate and initialize X[][][] with values of f().
Call InitMem() above
Implements Function.
References RealBase::f(), RealBase::getDt(), RealBase::getDu(), RealBase::getDv(), RealBase::getTmin(), RealBase::getTsteps(), RealBase::getUmin(), RealBase::getUsteps(), RealBase::getVmin(), RealBase::getVsteps(), InitMem(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), std::vector< _Tp, _Alloc >::resize(), and X.
Referenced by CustomFunction::CustomFunction(), CustomPolarFunction::CustomPolarFunction(), Fr3r::Fr3r(), Fr3rExp::Fr3rExp(), Fr3rSin::Fr3rSin(), GravitationPotential::GravitationPotential(), Hypersphere::Hypersphere(), Polar::Polar(), PolarR::PolarR(), PolarSin::PolarSin(), PolarSin2::PolarSin2(), ReInit(), Torus1::Torus1(), and Torus2::Torus2().
void RealFunction::InitMem (void) [protected, virtual]
Initialize the temporary storage areas.
Xscr[][][], Xtrans[][][]
References RealBase::getTsteps(), RealBase::getUsteps(), RealBase::getVsteps(), std::vector< _Tp, _Alloc >::resize(), Xscr, and Xtrans.
Referenced by Initialize().
Vector< 4 > & RealFunction::normal (double tt, double uu, double vv) [protected]
Calculate normal to function at a given point in definition set.
No further assumption is made than that f () is continuous.
This function is not yet used anywhere, but i like it.
Parameters:
tt t value
uu u value
vv v value
Returns:
surface normal, normalized
References Function::df(), VecMath::vcross(), and VecMath::vnormalize().
void RealFunction::Project (double scr_w, double cam_w, bool depthcue4d) [virtual]
Projects a RealFunction into three-space.
Parameters:
scr_w w coordinate of screen
cam_w w coordinate of camera
depthcue4d whether to use hyperfog/depth cue
Implements Function.
References RealBase::getTsteps(), RealBase::getUsteps(), RealBase::getVsteps(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), X, Xscr, and Xtrans.
void RealFunction::ReInit (double _tmin, double _tmax, double _dt, double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv) [virtual]
Re-initialize a RealFunction if the definition set has changed.
Parameters:
_tmin minimal value in t
_tmax maximal value in t
_dt stepsize in t
_umin minimal value in u
_umax maximal value in u
_du stepsize in u
_vmin minimal value in v
_vmax maximal value in v
_dv stepsize in v
Implements Function.
References RealBase::getDt(), RealBase::getDu(), RealBase::getDv(), RealBase::getTmax(), RealBase::getTmin(), RealBase::getTsteps(), RealBase::getUmax(), RealBase::getUmin(), RealBase::getUsteps(), RealBase::getVmax(), RealBase::getVmin(), RealBase::getVsteps(), Initialize(), and Loki::SingletonHolder< T, CreationPolicy >::Instance().
void RealFunction::Transform (const VecMath::Rotation< 4 > & R, const VecMath::Vector< 4 > & T) [virtual]
Transforms a RealFunction.
Todo:
As I look at it, i think this could be optimized by making the transformation matrices static and only canging the corresponding entries... but how to do this beautifully, i don't know
Parameters:
R rotation
T translation
Implements Function.
References RealBase::getTsteps(), RealBase::getUsteps(), RealBase::getVsteps(), X, and Xtrans.
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Functions/RealFunction.H
HyperspaceExplorer/src/Functions/RealFunction.C