HyperspaceExplorer: UI::Dialogs::ValuesDialogImpl Class Reference
UI::Dialogs::ValuesDialogImpl Class Reference
[User Interface]
A Dialog to enter parameters for the displayed function.
#include <ValuesDialogImpl.H>
Public Slots
virtual void accept ()
This function is called when the user clicks the "Apply" button.
Signals
void ApplyChanges (const ParameterMap &)
Tell the C4DView to update according to the ParameterMap's values.
Public Member Functions
ValuesDialogImpl (QWidget *parent=0, Qt::WFlags f=0)
Set up the components of the dialog and displays it.
void setFunction (const std::auto_ptr< Function > &)
Adjust the display according to the Function whose Parameters are controlled.
std::string print ()
output for debugging purposes
double tmin ()
lower bound for parameter t
double tmax ()
upper bound for parameter t
unsigned tsteps ()
steps in parameter t
double dt ()
delta in parameter t
double umin ()
lower bound for parameter u
double umax ()
upper bound for parameter u
unsigned usteps ()
steps in parameter u
double du ()
delta in parameter u
double vmin ()
lower bound for parameter v
double vmax ()
upper bound for parameter v
unsigned vsteps ()
steps in parameter v
double dv ()
delta in parameter v
Private Member Functions
void setParameters (const ParameterMap &)
Adjust the displayed parameter fields to the parameters the function needs.
Private Attributes
ParameterMap parameters
parameters to manage
Detailed Description
A Dialog to enter parameters for the displayed function.
These parameters encompass the definition space, the resolution of the grid on which the function's values are sampled and displayed, as well as parameters which are specific to the function.
Todo:
The switching on and off of input fields, depending on which function is selected, is done from C4DView. This is of course unfortunate and will be changed.
Author:
Helge Preuss <scout@hyperspace-travel.de>
Member Function Documentation
void UI::Dialogs::ValuesDialogImpl::setFunction (const std::auto_ptr< Function > & F)
Adjust the display according to the Function whose Parameters are controlled.
Sets the internal map of parameters to the parameters the Function expects and adjusts input elements accordingly
Shows as many sliders to adjust the size of the grid the function is evaluated on, as the definition space of the function has dimensions
Only displays labels for the parts of the dialog which are shown
References UI::Dialogs::ValuesDialog::functionLabel, UI::Dialogs::ValuesDialog::gridLabel, UI::Dialogs::ValuesDialog::Label, UI::Dialogs::ValuesDialog::Max, UI::Dialogs::ValuesDialog::MaxLabel, UI::Dialogs::ValuesDialog::maxNumDimensions, UI::Dialogs::ValuesDialog::Min, UI::Dialogs::ValuesDialog::MinLabel, setParameters(), UI::Dialogs::ValuesDialog::Slider, and UI::Dialogs::ValuesDialog::Steps.
Referenced by C4DView::AssignValues().
void UI::Dialogs::ValuesDialogImpl::setParameters (const ParameterMap & parms) [private]
Adjust the displayed parameter fields to the parameters the function needs.
Sets the internal map of parameters to the parameters the Function expects
Shows input fields for as many parameters as necessary
Sets the text on these fields to the parameter's name, the tool tip to its optional description and the value to its value
References std::map< _Key, _Tp, _Compare, _Alloc >::begin(), std::map< _Key, _Tp, _Compare, _Alloc >::end(), UI::Dialogs::ValuesDialog::maxNumParameters, UI::Dialogs::ValuesDialog::Parameter, UI::Dialogs::ValuesDialog::ParameterLabel, parameters, and value().
Referenced by setFunction().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/UI/ValuesDialogImpl.H
HyperspaceExplorer/src/UI/ValuesDialogImpl.C