HyperspaceExplorer: VecMath::Vector< D, N > Class Template Reference
VecMath::Vector< D, N > Class Template Reference
[Vector and Matrix algebra]
Vector<D, N>: a D-dimensional vector of numbers of type N.
#include <Vector.H>
Public Member Functions
Vector (N,...)
N & operator[] (unsigned i)
N operator[] (unsigned i) const
Vector< D, N > & operator+= (const Vector< D, N > &Y)
Vector< D, N > & operator-= (const Vector< D, N > &Y)
Vector< D, N > & operator*= (const N &s)
Vector< D, N > operator- (void) const
Vector< D, N > operator+ (const Vector< D, N > &Y)
Vector< D, N > operator- (const Vector< D, N > &Y)
Vector< D, N > operator* (const N &s)
N operator* (const Vector< D, N > &X) const
Vector< D, N > operator/ (const N &s)
N sqnorm (void) const
N * data ()
Vector ()
Default constructor.
Vector (N,...)
Constructor with variable arglist.
N & operator[] (unsigned i)
Returns a reference to component i.
N operator[] (unsigned i) const
Returns component i by value.
Vector< D, N > & operator+= (const Vector< D, N > &Y)
Vector< D, N > & operator-= (const Vector< D, N > &Y)
Vector< D, N > & operator*= (const N &s)
Vector< D, N > operator- (void) const
Vector< D, N > operator+ (const Vector< D, N > &Y)
Vector< D, N > operator- (const Vector< D, N > &Y)
Vector< D, N > operator* (const N &s)
N operator* (const Vector< D, N > &X) const
scalar multiplication between two Vectors (dot product)
Vector< D, N > operator/ (const N &s)
N sqnorm (void) const
N * data ()
Direct access to the array storing the components.
Static Public Member Functions
static unsigned dimension (void)
static unsigned dimension (void)
Private Attributes
N x [D]
A static array storing the components.
Detailed Description
template<unsigned D, typename N = double>
class VecMath::Vector< D, N >
Vector<D, N>: a D-dimensional vector of numbers of type N.
Parameters:
D dimension of the vector
N numerical type of the vector elements
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
template<unsigned D, typename N> Vector::Vector (N x0, ...) [inline]
constructor with variable arglist
Parameters:
x0 first element of the Vector
... the following elements
References VecMath::Vector< D, N >::x.
template<unsigned D, typename N = double> VecMath::Vector< D, N >::Vector () [inline]
Default constructor.
Doesn't do anything, the lazy bastard!
template<unsigned D, typename N = double> VecMath::Vector< D, N >::Vector (N , ...)
Constructor with variable arglist.
Parameters:
x0 first element of the Vector
... the following elements
Member Function Documentation
template<unsigned D, typename N> N & Vector::operator[] (unsigned i) [inline]
operator [] returns a reference to component i
Parameters:
i index of the element
Returns:
non-const reference to the accessed element
References VecMath::Vector< D, N >::x.
template<unsigned D, typename N> N Vector::operator[] (unsigned i) const [inline]
operator [] returns component i by value
Parameters:
i index of the element
Returns:
the accessed element
References VecMath::Vector< D, N >::x.
template<unsigned D, typename N> unsigned Vector::dimension (void) [inline, static]
Returns:
dimension of the Vector (the template parameter D)
template<unsigned D, typename N> Vector< D, N > & Vector::operator+= (const Vector< D, N > & Y) [inline]
Parameters:
Y other Vector
Returns:
*this+Y
References VecMath::Vector< D, N >::x.
template<unsigned D, typename N> Vector< D, N > & Vector::operator-= (const Vector< D, N > & Y) [inline]
Parameters:
Y other Vector
Returns:
*this-Y
References VecMath::Vector< D, N >::x.
template<unsigned D, typename N> Vector< D, N > & Vector::operator*= (const N & s) [inline]
Parameters:
s scalar type
Returns:
*this*s
References VecMath::Vector< D, N >::x.
template<unsigned D, typename N> Vector< D, N > Vector::operator- (void) const [inline]
Returns:
-*this
References VecMath::Vector< D, N >::x.
template<unsigned D, typename N> Vector< D, N > Vector::operator+ (const Vector< D, N > & Y) [inline]
Parameters:
Y other Vector
Returns:
*this+Y
template<unsigned D, typename N> Vector< D, N > Vector::operator- (const Vector< D, N > & Y) [inline]
Parameters:
Y other Vector
Returns:
*this-Y
template<unsigned D, typename N> Vector< D, N > Vector::operator* (const N & s) [inline]
Parameters:
s scalar type
Returns:
*this*s
Referenced by VecMath::Vector< D, N >::operator/(), and VecMath::Vector< D, N >::sqnorm().
template<unsigned D, typename N> N Vector::operator* (const Vector< D, N > & Y) const [inline]
scalar multiplication between two Vectors
Parameters:
Y other Vector
Returns:
dot product < *this, Y >
References VecMath::Vector< D, N >::x.
template<unsigned D, typename N> Vector< D, N > Vector::operator/ (const N & s) [inline]
Parameters:
s scalar type
Returns:
*this/s
References VecMath::Vector< D, N >::operator*().
template<unsigned D, typename N> N Vector::sqnorm (void) const [inline]
Returns:
the squared norm of the vector, |V|²
References VecMath::Vector< D, N >::operator*().
Referenced by Global::glVertex(), and VecMath::vnormalize().
template<unsigned D, typename N = double> N& VecMath::Vector< D, N >::operator[] (unsigned i)
Returns a reference to component i.
Parameters:
i index of the element
Returns:
non-const reference to the accessed element
template<unsigned D, typename N = double> N VecMath::Vector< D, N >::operator[] (unsigned i) const
Returns component i by value.
Parameters:
i index of the element
Returns:
the accessed element
template<unsigned D, typename N = double> static unsigned VecMath::Vector< D, N >::dimension (void) [static]
Returns:
dimension of the Vector (the template parameter D)
template<unsigned D, typename N = double> Vector<D, N>& VecMath::Vector< D, N >::operator+= (const Vector< D, N > & Y)
Parameters:
Y other Vector
Returns:
*this+Y
template<unsigned D, typename N = double> Vector<D, N>& VecMath::Vector< D, N >::operator-= (const Vector< D, N > & Y)
Parameters:
Y other Vector
Returns:
*this-Y
template<unsigned D, typename N = double> Vector<D, N>& VecMath::Vector< D, N >::operator*= (const N & s)
Parameters:
s scalar type
Returns:
*this*s
template<unsigned D, typename N = double> Vector<D, N> VecMath::Vector< D, N >::operator- (void) const
Returns:
-*this
template<unsigned D, typename N = double> Vector<D, N> VecMath::Vector< D, N >::operator+ (const Vector< D, N > & Y)
Parameters:
Y other Vector
Returns:
*this+Y
template<unsigned D, typename N = double> Vector<D, N> VecMath::Vector< D, N >::operator- (const Vector< D, N > & Y)
Parameters:
Y other Vector
Returns:
*this-Y
template<unsigned D, typename N = double> Vector<D, N> VecMath::Vector< D, N >::operator* (const N & s)
Parameters:
s scalar type
Returns:
*this*s
template<unsigned D, typename N = double> N VecMath::Vector< D, N >::operator* (const Vector< D, N > & X) const
scalar multiplication between two Vectors (dot product)
Parameters:
Y other Vector
Returns:
dot product < *this, Y >
template<unsigned D, typename N = double> Vector<D, N> VecMath::Vector< D, N >::operator/ (const N & s)
Parameters:
s scalar type
Returns:
*this/s
template<unsigned D, typename N = double> N VecMath::Vector< D, N >::sqnorm (void) const
Returns:
the squared norm of the vector, |V|²
template<unsigned D, typename N = double> N* VecMath::Vector< D, N >::data () [inline]
Direct access to the array storing the components.
Needed by glVertex3dv
The documentation for this class was generated from the following files:
workspace/HyperspaceExplorer/src/plugins/Vector.H
workspace/HyperspaceExplorer/src/Vector.H