HyperspaceExplorer: Hypercube Class Reference
Hypercube Class Reference
[Arbitrary four-dimensional objects, described by their surfaces]
A four-dimensional cube.
#include <Object.H>
Public Member Functions
Hypercube (double a, const VecMath::Vector< 4 > &_center=VecMath::Vector< 4 >(0., 0., 0., 0.))
Construct a hypercube with a side length and a center.
virtual void SetParameters (const ParameterMap &parms)
Set parameters to the Function.
virtual std::string description ()
Protected Member Functions
virtual void Initialize ()
Actually creates the Hypercube.
void DeclareSquare (unsigned, unsigned, unsigned, unsigned, unsigned)
Declare a square in the Surface array.
Protected Attributes
double _a
Side length of the hypercube.
VecMath::Vector< 4 > _center
Center of the hypercube.
Detailed Description
A four-dimensional cube.
Constructor & Destructor Documentation
Hypercube::Hypercube (double a, const VecMath::Vector< 4 > & center = VecMath::Vector<4>(0., 0., 0., 0.))
Construct a hypercube with a side length and a center.
Hypercube constructor.
Parameters:
center center
a side_length/2
References Function::declareParameter(), and Initialize().
Member Function Documentation
virtual std::string Hypercube::description () [inline, virtual]
Returns:
A string carrying a description of the Function
Reimplemented in Sponge.
References _a, and std::ends().
void Hypercube::Initialize (void) [protected, virtual]
Actually creates the Hypercube.
sets up the vertices of the Hypercube in X[], then sets up the surfaces of the Hypercube by declaring the appropriate squares as a list in Surface[][].
Reimplemented from Object.
Reimplemented in Sponge.
References _a, _center, DeclareSquare(), Object::Initialize(), and Object::X.
Referenced by Hypercube().
void Hypercube::DeclareSquare (unsigned i, unsigned a, unsigned b, unsigned c, unsigned d) [protected]
Declare a square in the Surface array.
Parameters:
i index of the square
a index of vertex 1
b index of vertex 2
c index of vertex 3
d index of vertex 4
Referenced by Initialize().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Functions/Object.H
HyperspaceExplorer/src/Functions/Object.C