HyperspaceExplorer: Log Class Reference
Log Class Reference
#include <Log.H>
Public Member Functions
void log (std::string)
Log & operator<< (const std::string &)
template<unsigned D>
Log & operator<< (const VecMath::Vector< D > &)
template<unsigned D>
Log & operator<< (const VecMath::Rotation< D > &)
Log & operator<< (long x)
Log & operator<< (unsigned long x)
Log & operator<< (double x)
Private Member Functions
Log ()
Log (const Log &)
Log & operator= (const Log &)
~Log ()
Friends
class Loki::CreateUsingNew< Log >
Detailed Description
A class to conditionally print debug messages, depending on whether the preprocessor variable DEBUG is defined
That implies a lot of ifdef DEBUG in its declaration as well as its definition. Never mind the ugliness.
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
Log::Log () [inline, private]
disabled default constructor
Log::Log (const Log &) [private]
disabled copy constructor
Log::~Log () [inline, private]
disabled destructor
Member Function Documentation
void Log::log (std::string) [inline]
print a string with a line break
References std::cerr, and std::endl().
Log& Log::operator<< (const std::string &) [inline]
print a string without a line break
References std::cerr.
Referenced by operator<<().
template<unsigned D> Log& Log::operator<< (const VecMath::Vector< D > &) [inline]
print a Vector without a line break
References std::cerr.
template<unsigned D> Log& Log::operator<< (const VecMath::Rotation< D > &) [inline]
print a Rotation without a line break
References std::cerr.
Log& Log::operator<< (long x) [inline]
print a long integer without a line break
References Loki::SingletonHolder< T, CreationPolicy >::Instance(), and operator<<().
Log& Log::operator<< (unsigned long x) [inline]
print an unsigned long integer without a line break
References Loki::SingletonHolder< T, CreationPolicy >::Instance(), and operator<<().
Log& Log::operator<< (double x) [inline]
print a double without a line break
References Loki::SingletonHolder< T, CreationPolicy >::Instance(), and operator<<().
Log& Log::operator= (const Log &) [private]
disabled assignment operator
The documentation for this class was generated from the following file:
HyperspaceExplorer/src/Log.H