HyperspaceExplorer: Rotope Class Reference
Rotope Class Reference
[N-dimensional]
A four-dimensional Rotope.
#include <Rotope.H>
Public Member Functions
Rotope (const QString &)
Construct a Rotope. Not yet implemented properly.
virtual void Transform (const VecMath::Rotation< 4 > &, const VecMath::Vector< 4 > &)
Transforms a Rotope.
virtual void Draw (void)
Draw the projected Rotope (onto screen or into GL list, as it is).
virtual QString getFunctionName () const
Private Attributes
vertex_data< 4 > * _rotope
Actual rotope object to which all functions are delegated.
Detailed Description
A four-dimensional Rotope.
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
Rotope::Rotope (const QString & name)
Construct a Rotope. Not yet implemented properly.
Todo:
use a projection function on vertex_data
References _rotope, std::cerr, Object::Initialize(), std::vector< _Tp, _Alloc >::size(), Object::X, and vertex_data< D >::X().
Member Function Documentation
void Rotope::Transform (const VecMath::Rotation< 4 > & R, const VecMath::Vector< 4 > & T) [virtual]
Transforms a Rotope.
Parameters:
R Rotation
T Translation
Reimplemented from Object.
References _rotope, std::vector< _Tp, _Alloc >::size(), Object::X, vertex_data< D >::X(), and Object::Xtrans.
virtual QString Rotope::getFunctionName () const [inline, virtual]
Returns:
The name of the function in cleartext
Reimplemented from Function.
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Functions/Rotope.H
HyperspaceExplorer/src/Functions/Rotope.C