HyperspaceExplorer: CustomSurface Class Reference
CustomSurface Class Reference
[Functions R^2 -> R^4, describing surfaces in four-space]
#include <CustomFunction.H>
Public Member Functions
CustomSurface (double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
virtual ~CustomSurface ()
Protected Attributes
virtual Surface::function_type f
Detailed Description
A Function , which the user can edit to have an arbitrary function.
Constructor & Destructor Documentation
CustomSurface::CustomSurface (double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv)
CustomSurface c'tor given a definition set in R² (as parameter space) and a flag indicatin whether this is a test construction or a real one
Parameters:
_umin minimal value in u
_umax maximal value in u
_du stepsize in u
_vmin minimal value in v
_vmax maximal value in v
_dv stepsize in v
References Surface::Initialize(), PluginCreator::libraryName(), and CustomFunctionBase< Surface::raw_function_type >::loadFunction().
CustomSurface::~CustomSurface () [virtual]
CustomFunction destructor, closes DLL if necessary
Member Data Documentation
Vector< 4 > & CustomSurface::f [protected]
CustomFunction defining function; calls loaded function
Parameters:
u u value
v v value
Returns:
custom function of (u, v)
Reimplemented from Surface.
The documentation for this class was generated from the following files:
workspace/HyperspaceExplorer/src/Functions/CustomFunction.H
workspace/HyperspaceExplorer/src/Functions/CustomFunction.C