HyperspaceExplorer: Script::ObjectStmt Class Reference
Script::ObjectStmt Class Reference
[Statements possible in a script]
"object <object_name>"
#include <Statement.H>
Public Member Functions
ObjectStmt (const Parser *p, const std::string &_arg)
virtual bool execute ()
Executes the statement in the current context.
Detailed Description
"object <object_name>"
sets the object to be displayed to the supplied type
Constructor & Destructor Documentation
Script::ObjectStmt::ObjectStmt (const Parser * p, const std::string & _arg) [inline]
Parameters:
p The context in which the Statement is executed
_arg The argument supplied to the Statement
Member Function Documentation
bool Script::ObjectStmt::execute () [virtual]
Executes the statement in the current context.
Todo:
make a map (or something like that) to call the right function for the string supplied as argument
Reimplemented from Script::Statement.
References Script::Statement::arg(), Script::Parser::getView(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), Script::Statement::parser(), and UI::View::setF().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Script/Statement.H
HyperspaceExplorer/src/Script/Statement.C