HyperspaceExplorer: UI::Dialogs::FunctionDialogImpl Class Reference
UI::Dialogs::FunctionDialogImpl Class Reference
[User Interface]
A Dialog to enter a function from .
#include <FunctionDialogImpl.H>
Public Member Functions
FunctionDialogImpl (QWidget *parent=0, Qt::WFlags f=0)
FunctionDialogImpl c'tor - displays the dialog.
Private Slots
virtual bool checkValidity ()
Called when the user clicks the OK button in the Function Dialog.
virtual bool loadFunction ()
Display and load the selected DLL into current address space.
Private Member Functions
virtual bool functionPresent (const QString &)
Loads the dynamic library given by libName, if it exists and can be loaded.
virtual void writeSource ()
Write a C++ source file containing the given function.
Detailed Description
A Dialog to enter a function from .
The function which has been entered will then be compiled into a dynamic library and loaded to be displayed on screen as a Function.
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
UI::Dialogs::FunctionDialogImpl::FunctionDialogImpl (QWidget * parent = 0, Qt::WFlags f = 0)
FunctionDialogImpl c'tor - displays the dialog.
Parameters:
parent parent widget (NULL)
f window flags
References checkValidity(), and loadFunction().
Member Function Documentation
bool UI::Dialogs::FunctionDialogImpl::checkValidity () [private, virtual, slot]
Called when the user clicks the OK button in the Function Dialog.
Checks whether all fields are filled in, whether the given function is valid C++ syntax, ie. whether it compiles, and whether the compiled code links into a dynamic library.
As a side effect, it generates this library.
Finally, it checks whether the library can be loaded. if so, it accepts the input.
Also, this function creates a directory structure "plugins/real" under the resource directory and changes the CWD to that folder for the duration of checkValidity ().
The name for this function is chosen rather unfortunately, i admit.
Returns:
success
References PluginCreator::checkValidity().
Referenced by FunctionDialogImpl().
bool UI::Dialogs::FunctionDialogImpl::loadFunction () [private, virtual, slot]
Display and load the selected DLL into current address space.
Loads a dynamic library, which can be selected by the user on a QFileDialog. calls loadFunction () below. see there.
Returns:
success (?)
Implements PluginCreator.
References PluginCreator::loadFunction().
Referenced by FunctionDialogImpl().
bool UI::Dialogs::FunctionDialogImpl::functionPresent (const QString & libName) [private, virtual]
Loads the dynamic library given by libName, if it exists and can be loaded.
Then checks whether a function named f() is present. if so, returns true. else borks with an error message.
Parameters:
libName filename for the selected DLL
Returns:
success
Implements PluginCreator.
void UI::Dialogs::FunctionDialogImpl::writeSource () [private, virtual]
Write a C++ source file containing the given function.
Also written is a little framework to make the source file compilable by g++ (there is currently no support for other compilers).
The resulting file "<function-name>.C" defines the function f() and the function symbolic(), which returns the function in symbolic terms, not in C++ syntax.
Implements PluginCreator.
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/UI/FunctionDialogImpl.H
HyperspaceExplorer/src/UI/FunctionDialogImpl.C