HyperspaceExplorer: UI::Dialogs::AnimationDialogImpl Class Reference
UI::Dialogs::AnimationDialogImpl Class Reference
[User Interface]
A Dialog to select settings concerning the writing of animated frames to disk.
#include <AnimationDialogImpl.H>
Public Member Functions
AnimationDialogImpl (QWidget *parent=0, Qt::WFlags f=0)
virtual ~AnimationDialogImpl ()
Empty destructor Read the maximum number of frames written to disk.
int getFrames ()
QString getDir ()
Read the directory where the images are stored.
QString getPrefix ()
Read the prefix of the filenames of stored images.
Protected Slots
void openFileDialog ()
Open a QFileDialog to select save directory.
Detailed Description
A Dialog to select settings concerning the writing of animated frames to disk.
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
UI::Dialogs::AnimationDialogImpl::AnimationDialogImpl (QWidget * parent = 0, Qt::WFlags f = 0)
AnimationDialogImpl c'tor taking parameters for the parent AnimationDialog, which in turn inherited them from QDialog displays the dialog
Parameters:
parent parent widget (NULL)
f window flags
References openFileDialog().
Member Function Documentation
QString UI::Dialogs::AnimationDialogImpl::getDir () [inline]
Read the directory where the images are stored.
Returns:
directory where the images are stored
Referenced by C4DView::Menu4D::AnimationSettings().
int UI::Dialogs::AnimationDialogImpl::getFrames () [inline]
Returns:
maximum number of frames written to disk
Referenced by C4DView::Menu4D::AnimationSettings().
QString UI::Dialogs::AnimationDialogImpl::getPrefix () [inline]
Read the prefix of the filenames of stored images.
Returns:
prefix of the filenames of stored images
Referenced by C4DView::Menu4D::AnimationSettings().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/UI/AnimationDialogImpl.H
HyperspaceExplorer/src/UI/AnimationDialogImpl.C