HyperspaceExplorer: ComplexDialogImpl Class Reference
ComplexDialogImpl Class Reference
[User Interface]
A Dialog to enter a user-defined complex function, .
#include <ComplexDialogImpl.H>
Public Slots
virtual bool checkValidity ()
virtual bool loadFunction ()
Public Member Functions
ComplexDialogImpl (QWidget *parent=0, Qt::WFlags f=0)
Protected Member Functions
virtual bool functionPresent (const QString &)
virtual void writeSource ()
Detailed Description
A Dialog to enter a user-defined complex function, .
The function will then be compiled into a dynamic library and loaded to be displayed on screen.
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
ComplexDialogImpl::ComplexDialogImpl (QWidget * parent = 0, Qt::WFlags f = 0)
ComplexDialogImpl c'tor taking parameters for the parent ComplexDialog, which in turn inherited them from QDialog displays the dialog
Parameters:
parent parent widget (NULL)
f window flags
References checkValidity(), and loadFunction().
Member Function Documentation
bool ComplexDialogImpl::checkValidity () [virtual, slot]
this function is called when the user clicks the OK button in the Function Dialog. checks whether all fields are filled in, whether the given function is valid C++ syntax, ie. whether it compiles, and whether the compiled code links into a dynamic library. as a side effect, it generates this library. finally, it checks whether the library can be loaded. if so, it accepts the input. also, this function creates a directory structure "plugins/real" under the resource directory and changes the CWD to that folder for the duration of checkValidity (). the name for this function is chosen rather unfortunately, i guess.
Returns:
success
References PluginCreator::checkValidity().
Referenced by ComplexDialogImpl().
bool ComplexDialogImpl::loadFunction () [virtual, slot]
display and load the selected DLL into current address space loads a dynamic library, which can be selected by the user on a QFileDialog. calls loadFunction () below. see there.
Returns:
success (?)
Implements PluginCreator.
References PluginCreator::loadFunction().
Referenced by ComplexDialogImpl().
bool ComplexDialogImpl::functionPresent (const QString & libName) [protected, virtual]
loads the dynamic library given by libName, if it exists and can be loaded. then it checks whether a function named f () is present. if so, returns true. else borks with an error message.
Parameters:
libName filename for the selected DLL
Returns:
success
Implements PluginCreator.
void ComplexDialogImpl::writeSource () [protected, virtual]
write a C++ source file, containing the given function and some framework to make it compilable by g++ (there is currently no support for other compilers). the resulting file "<function-name>.C" defines the function f () and the function symbolic (), which returns the function in symbolic terms, not in C++ syntax.
Implements PluginCreator.
The documentation for this class was generated from the following files:
workspace/HyperspaceExplorer/src/UI/ComplexDialogImpl.H
workspace/HyperspaceExplorer/src/UI/ComplexDialogImpl.C