HyperspaceExplorer: LSystem Class Reference
LSystem Class Reference
#include <LSystem.H>
Public Member Functions
LSystem (unsigned=2)
LSystem (string, map< string, string >, unsigned=2)
virtual ~LSystem ()
void level (unsigned n)
unsigned level ()
void axiom (string a)
string axiom ()
void set_rule (string key, string rule)
void rules (map< string, string > rules)
map< string, string > rules (void)
void angle (double angle)
double angle ()
void object (string key, string object)
void object (map< string, string > object)
map< string, string > object ()
string object (string key)
virtual string Expand ()
virtual string POV_Source ()
virtual void Draw ()
Protected Member Functions
string POV_Header (const string &)
string POV_Footer (const Vector &, const Vector &)
virtual string POV_Atom (const string &, const string &)
virtual string Expand (string, unsigned)
Protected Attributes
string _axiom
map< string, string > _rules
unsigned _level
double _scale
double _angle
map< string, string > _object
Detailed Description
An experimental class to display Lindenmayer Systems (LSystems)
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
LSystem::LSystem (unsigned l = 2)
Todo:
document me
LSystem::LSystem (string axiom, map< string, string > rules, unsigned level = 2)
Todo:
document me
LSystem::~LSystem () [virtual]
Todo:
document me
Member Function Documentation
double LSystem::angle () [inline]
Todo:
document me
References _angle.
void LSystem::angle (double angle) [inline]
Todo:
document me
References _angle.
string LSystem::axiom () [inline]
Todo:
document me
References _axiom.
void LSystem::axiom (string a) [inline]
Todo:
document me
References _axiom.
virtual void LSystem::Draw (void) [inline, virtual]
Todo:
document me
string LSystem::Expand (string axiom, unsigned l) [protected, virtual]
Todo:
document me
References Expand(), and sqrt().
string LSystem::Expand () [virtual]
Todo:
document me
Referenced by Expand(), and POV_Source().
unsigned LSystem::level () [inline]
Todo:
document me
References _level.
void LSystem::level (unsigned n) [inline]
Todo:
document me
References _level.
string LSystem::object (string key) [inline]
Todo:
document me
References _object.
map<string, string> LSystem::object () [inline]
Todo:
document me
References _object.
void LSystem::object (map< string, string > object)
Todo:
document me
void LSystem::object (string key, string object) [inline]
Todo:
document me
References _object.
string LSystem::POV_Atom (const string & key, const string & transform) [protected, virtual]
Todo:
document me
References endl().
Referenced by POV_Source().
string LSystem::POV_Footer (const Vector & xmin, const Vector & xmax) [protected]
Todo:
document me
References std::basic_ostringstream< _CharT, _Traits, _Alloc >::str().
Referenced by POV_Source().
string LSystem::POV_Header (const string & expanded) [protected]
Todo:
document me
References std::map< _Key, _Tp, _Compare, _Alloc >::begin(), std::map< _Key, _Tp, _Compare, _Alloc >::end(), and endl().
Referenced by POV_Source().
string LSystem::POV_Source () [virtual]
Todo:
document me
References cerr, endl(), Expand(), isdigit(), POV_Atom(), POV_Footer(), POV_Header(), and rotate().
map<string, string> LSystem::rules (void) [inline]
Todo:
document me
References _rules.
void LSystem::rules (map< string, string > rules) [inline]
Todo:
document me
References _rules.
void LSystem::set_rule (string key, string rule) [inline]
Todo:
document me
References _rules.
Member Data Documentation
double LSystem::_angle [protected]
Todo:
document me
Referenced by angle().
string LSystem::_axiom [protected]
Todo:
document me
Referenced by axiom().
unsigned LSystem::_level [protected]
Todo:
document me
Referenced by level().
map<string, string> LSystem::_object [protected]
Todo:
document me
Referenced by object().
map<string, string> LSystem::_rules [protected]
Todo:
document me
Referenced by rules(), and set_rule().
double LSystem::_scale [protected]
Todo:
document me
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Functions/LSystems/LSystem.H
HyperspaceExplorer/src/Functions/LSystems/LSystem.C