HyperspaceExplorer: Pyramid Class Reference
Pyramid Class Reference
[Arbitrary four-dimensional objects, described by their surfaces]
A four-dimensional pyramid, also known as hypersimplex.
#include <Object.H>
Public Member Functions
Pyramid (double _a, const VecMath::Vector< 4 > &_Center=VecMath::Vector< 4 >(0., 0., 0., 0.))
Pyramid (hypersimplex) constructor.
virtual void SetParameters (const ParameterMap &parms)
Set parameters to the Function.
Protected Member Functions
virtual void Initialize ()
Actually creates the Pyramid.
void DeclareTriangle (unsigned, unsigned, unsigned, unsigned)
Declare a triangle in the Surface array.
Protected Attributes
VecMath::Vector< 4 > center
location
double a
size
Detailed Description
A four-dimensional pyramid, also known as hypersimplex.
Constructor & Destructor Documentation
Pyramid::Pyramid (double _a, const VecMath::Vector< 4 > & _center = VecMath::Vector<4> (0., 0., 0., 0.))
Pyramid (hypersimplex) constructor.
Parameters:
_center center
_a side_length/2
References Function::declareParameter(), and Initialize().
Member Function Documentation
void Pyramid::Initialize (void) [protected, virtual]
Actually creates the Pyramid.
See also:
Hypercube::Initialize()
Reimplemented from Object.
Reimplemented in Gasket.
References a, center, DeclareTriangle(), Object::Initialize(), std::vector< _Tp, _Alloc >::size(), sqrt(), and Object::X.
Referenced by Pyramid().
void Pyramid::DeclareTriangle (unsigned i, unsigned a, unsigned b, unsigned c) [protected]
Declare a triangle in the Surface array.
Parameters:
i index of the square
a index of vertex 1
b index of vertex 2
c index of vertex 3
Referenced by Initialize().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Functions/Object.H
HyperspaceExplorer/src/Functions/Object.C