HyperspaceExplorer: zA Class Reference
zA Class Reference
[Functions C -> C]
#include <ComplexFunction.H>
Public Member Functions
zA (double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv, double _alpha=2)
virtual void SetParameters (const ParameterMap &parms)
Protected Attributes
virtual function_type g
Private Attributes
double alpha
Exponent.
Detailed Description
Constructor & Destructor Documentation
zA::zA (double _umin, double _umax, double _du, double _vmin, double _vmax, double _dv, double _alpha = 2)
z^a c'tor given a definition set in C (as parameter space)
Parameters:
_umin minimal value in Re (z)
_umax maximal value in Re (z)
_du stepsize in Re (z)
_vmin minimal value in Im (z)
_vmax maximal value in Im (z)
_dv stepsize in Im (z)
_alpha exponent
References Function::declareParameter(), and ComplexFunction::Initialize().
Member Function Documentation
virtual void zA::SetParameters (const ParameterMap & parms) [inline, virtual]
See also:
Function::SetParameters()
Reimplemented from Function.
References alpha, std::map< _Key, _Tp, _Compare, _Alloc >::begin(), std::map< _Key, _Tp, _Compare, _Alloc >::end(), and Function::setParameter().
Member Data Documentation
complex< double > zA::g [protected]
z^a defining function
Parameters:
z operand
Returns:
z^alpha
Reimplemented from ComplexFunction.
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Functions/ComplexFunction.H
HyperspaceExplorer/src/Functions/ComplexFunction.C