HyperspaceExplorer: UI::Dialogs::SurfaceDialogImpl Class Reference
UI::Dialogs::SurfaceDialogImpl Class Reference
[User Interface]
A Dialog to enter a function from .
#include <SurfaceDialogImpl.H>
Public Member Functions
SurfaceDialogImpl (QWidget *parent=0, Qt::WFlags f=0)
Private Slots
virtual bool checkValidity ()
virtual bool loadFunction ()
Display and load the selected DLL into current address space.
Private Member Functions
virtual bool functionPresent (const QString &)
Loads the dynamic library given by libName, if it exists and can be loaded.
virtual void writeSource ()
Write a C++ source file containing the given function.
Detailed Description
A Dialog to enter a function from .
The function will then be compiled into a dynamic library and loaded to be displayed on screen
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
UI::Dialogs::SurfaceDialogImpl::SurfaceDialogImpl (QWidget * parent = 0, Qt::WFlags f = 0)
SurfaceDialogImpl c'tor taking parameters for the parent ComplexDialog, which in turn inherited them from QDialog displays the dialog
Parameters:
parent parent widget (NULL)
f window flags
References checkValidity(), and loadFunction().
Member Function Documentation
bool UI::Dialogs::SurfaceDialogImpl::checkValidity () [private, virtual, slot]
See also:
PluginCreator::checkValidity()
References UI::Dialogs::PluginCreator::checkValidity().
Referenced by SurfaceDialogImpl().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/UI/SurfaceDialogImpl.H
HyperspaceExplorer/src/UI/SurfaceDialogImpl.C