HyperspaceExplorer: C4DView::Menu4D Class Reference
C4DView::Menu4D Class Reference
[User Interface]
The menu for the C4DView and handlers for menu events.
#include <Menu4D.H>
Public Slots
void customFunction ()
"Object/f:R^3 -> R/Custom function" menu item selected
void customPolarFunction ()
"Object/f:R^3 -> R/Custom polar function" menu item selected
void ObjectHypercube ()
"Object/Objects/Hypercube" menu item selected
void ObjectHyperpyramid ()
"Object/Objects/Hyperpyramid" menu item selected
void ObjectHypersponge ()
"Object/Objects/Menger Sponge" menu item selected
void ObjectGasket ()
"Object/Objects/Sierpinski Gasket" menu item selected
void ObjectRotope ()
"Object/Objects/Rotope" menu item selected
void customSurface ()
"Object/Surfaces/Custom surface" menu item selected
void customComplexFunction ()
"Object/Surfaces/f:C -> C/Custom complex function" menu item selected
void Colors ()
"Appearance/Colors" menu item selected
void Shade ()
"Appearance/Shading" menu item selected
void Fog ()
"Appearance/Depth Cue" menu item selected
void Transparent ()
"Appearance/Transparence" menu item selected
void Light ()
"Appearance/Lighting" menu item selected
void Wireframe ()
"Appearance/Wireframe" menu item selected
void Coordinates ()
"Appearance/Coordinate Cross" menu item selected
void setBackground ()
"Appearance/Set Background Color" menu item selected
void HyperFog ()
"Appearance/4D Depth Cue" menu item selected
void RenderToImages ()
"Animation/Render to Images" menu item selected
void AnimationSettings ()
"Animation/Animation Settings" menu item selected
void Benchmark ()
"Animation/Benchmark" menu item selected
void RandomAnimation ()
"Animation/Random Animation" menu item selected
void Help ()
"Help/Online Help" menu item selected
void about ()
"Help/About" menu item selected
void aboutQt ()
"Help/About Qt" menu item selected
Public Member Functions
Menu4D (C4DView *)
Creates the application's main menu and all its submenus.
void addToMenuBar (QMenuBar *menuBar)
Add the menu to a QMenuBar.
void updateFunctionMenu (const QString &)
Set the selected function as checked and uncheck all the others.
QAction *& getAction (const QString &key)
Search for the QAction associated with a menu item.
Private Types
typedef std::map< QString,
QAction * > ActionMapType
Assigns a QAction to a menu title.
typedef std::map< QMenu
*, ActionMapType > MenuMapType
Manages an ActionMap for each submenu.
Private Member Functions
QAction * insertAction (QMenu *, const QString &, const char *, bool=true)
insert a menu item with a specified slot into a specified menu
QAction * insertAction (QMenu *, const QString &, RealFunctionFactory *, bool=true)
insert a menu item creating a RealFunction object into a specified menu
QAction * insertAction (QMenu *, const QString &, SurfaceFactory *, bool=true)
insert a menu item creating a Surface object into a specified menu
Private Attributes
C4DView * _parent
the C4DView containing this menu
QMenu * _functions
The "Object" menu.
QMenu * _fr3r
The "Object/f:R^3 -> R" submenu.
QMenu * _objects
The "Object/Objects" submenu.
QMenu * _surfaces
The "Object/Surfaces" submenu.
QMenu * _fcc
The "Object/Surfaces/f:C -> C" submenu.
QMenu * _appear
The "Appearance" menu.
QMenu * _animation
The "Animation" menu.
QMenu * _help
The "Help" menu.
MenuMapType menuMap
Keeps the QActions belonging to the menu entries.
Detailed Description
The menu for the C4DView and handlers for menu events.
This class has been outsourced from C4DView to keep C4DView to a managable size.
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
C4DView::Menu4D::Menu4D (C4DView * _parent)
Creates the application's main menu and all its submenus.
This Constructor is where the menu structure is defined; if you want to change the menu, do it here.
Basically this happens by inserting all the menu items and the QActions they trigger manually. The application of TemplatedRealFunctionFactory<Function> as Factory object _helps to save a lot of redundant code, but still every menu item must be specified manually.
References _animation, _appear, _fcc, _fr3r, _functions, _help, _objects, _surfaces, about(), AnimationSettings(), Benchmark(), Colors(), Coordinates(), customComplexFunction(), customFunction(), customPolarFunction(), customSurface(), Fog(), getAction(), UI::ViewImpl::getColors(), UI::ViewImpl::getCoordinates(), UI::ViewImpl::getFog(), UI::ViewImpl::getLighting(), UI::ViewImpl::getShading(), UI::ViewImpl::getSolid(), UI::ViewImpl::getTransparence(), UI::ViewImpl::getWriteImages(), Help(), HyperFog(), insertAction(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), Light(), ObjectGasket(), ObjectHypercube(), ObjectHyperpyramid(), ObjectHypersponge(), ObjectRotope(), RandomAnimation(), RenderToImages(), setBackground(), UI::ViewImpl::setSolid(), Shade(), Transparent(), and Wireframe().
Member Function Documentation
void C4DView::Menu4D::about () [slot]
"Help/About" menu item selected
Open an "About"-Dialog telling a few basics about the software
References _parent.
Referenced by Menu4D().
void C4DView::Menu4D::aboutQt () [slot]
"Help/About Qt" menu item selected
Open an "About Qt"-Dialog
References _parent.
void C4DView::Menu4D::addToMenuBar (QMenuBar * menuBar)
Add the menu to a QMenuBar.
Parameters:
menuBar The menu bar you want augmented with the menu
References _animation, _appear, _functions, _help, and Loki::SingletonHolder< T, CreationPolicy >::Instance().
Referenced by C4DView::C4DView().
void C4DView::Menu4D::AnimationSettings () [slot]
"Animation/Animation Settings" menu item selected
Show a dialog to adjust _animation settings - where to write image files and how many files to write.
References _parent, C4DView::animationMaxFrames(), UI::Dialogs::AnimationDialogImpl::getDir(), UI::Dialogs::AnimationDialogImpl::getFrames(), UI::ViewImpl::getImgDir(), UI::ViewImpl::getImgPrefix(), UI::Dialogs::AnimationDialogImpl::getPrefix(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), C4DView::setanimationMaxFrames(), UI::ViewImpl::setImgDir(), and UI::ViewImpl::setImgPrefix().
Referenced by Menu4D().
void C4DView::Menu4D::Benchmark () [slot]
"Animation/Benchmark" menu item selected
Run a benchmark test
References _parent, C4DView::Benchmark3D(), C4DView::Benchmark4D(), endl(), ends(), and C4DView::UpdateStatus().
Referenced by Menu4D().
void C4DView::Menu4D::Colors () [slot]
"Appearance/Colors" menu item selected
Toggle colors
References _parent, getAction(), UI::ViewImpl::getColors(), and C4DView::setColors().
Referenced by Menu4D().
void C4DView::Menu4D::Coordinates () [slot]
"Appearance/Coordinate Cross" menu item selected
Switch coordinate cross on or off
Change menu items accordingly
References _parent, getAction(), UI::ViewImpl::getCoordinates(), and C4DView::setCoordinates().
Referenced by Menu4D().
void C4DView::Menu4D::customComplexFunction () [slot]
"Object/Surfaces/f:C -> C/Custom complex function" menu item selected
Display a CustomComplexFunction object
References _parent.
Referenced by Menu4D().
void C4DView::Menu4D::customFunction () [slot]
"Object/f:R^3 -> R/Custom function" menu item selected
Display a CustomFunction object
References _parent.
Referenced by Menu4D().
void C4DView::Menu4D::customPolarFunction () [slot]
"Object/f:R^3 -> R/Custom polar function" menu item selected
Display a CustomPolarFunction object
References _parent.
Referenced by Menu4D().
void C4DView::Menu4D::customSurface () [slot]
"Object/Surfaces/Custom surface" menu item selected
Display a CustomSurface object
References _parent.
Referenced by Menu4D().
void C4DView::Menu4D::Fog () [slot]
"Appearance/Depth Cue" menu item selected
Toggle fog/depth cue
References _parent, getAction(), UI::ViewImpl::getFog(), and C4DView::setFog().
Referenced by Menu4D().
QAction *& C4DView::Menu4D::getAction (const QString & key)
Search for the QAction associated with a menu item.
Parameters:
key The title of the wanted menu item
Returns:
The QAction associated with key
References std::map< _Key, _Tp, _Compare, _Alloc >::begin(), std::map< _Key, _Tp, _Compare, _Alloc >::count(), std::map< _Key, _Tp, _Compare, _Alloc >::end(), and menuMap.
Referenced by Colors(), Coordinates(), Fog(), HyperFog(), Light(), Menu4D(), RenderToImages(), Shade(), Transparent(), updateFunctionMenu(), and Wireframe().
void C4DView::Menu4D::Help () [slot]
"Help/Online Help" menu item selected
Display _help window
References C4DView::_helpFile.
Referenced by Menu4D().
void C4DView::Menu4D::HyperFog () [slot]
"Appearance/4D Depth Cue" menu item selected
Switch 4D depth cue on or off Change menu items accordingly
References _parent, getAction(), UI::ViewImpl::getHyperfog(), and C4DView::setHyperfog().
Referenced by Menu4D().
QAction * C4DView::Menu4D::insertAction (QMenu * _menu, const QString & title, SurfaceFactory * factory, bool checkable = true) [private]
insert a menu item creating a Surface object into a specified menu
This version is called whenever a new Surface should be initialized and displayed in C4DView
Parameters:
_menu the menu you want to add the item to
title the title of the item
factory the factory object creating the desired Surface object
checkable whether the menu item is checkable
References _fr3r, _parent, std::map< _Key, _Tp, _Compare, _Alloc >::insert(), and menuMap.
QAction * C4DView::Menu4D::insertAction (QMenu * _menu, const QString & title, RealFunctionFactory * factory, bool checkable = true) [private]
insert a menu item creating a RealFunction object into a specified menu
This version is called whenever a new RealFunction should be initialized and displayed in C4DView
Parameters:
_menu the menu you want to add the item to
title the title of the item
factory the factory object creating the desired RealFunction object
checkable whether the menu item is checkable
References _fr3r, _parent, std::map< _Key, _Tp, _Compare, _Alloc >::insert(), and menuMap.
QAction * C4DView::Menu4D::insertAction (QMenu * _menu, const QString & title, const char * slot, bool checkable = true) [private]
insert a menu item with a specified slot into a specified menu
Insert a menu item with a specified slot into a specified menu and into the hash map storing the actions by menu title. This is necessary to find the menus whenever you want to change the item titles.
Parameters:
_menu the menu you want to add the item to
title the title of the item
slot the function triggered by the item's selection
checkable whether the menu item is checkable
References std::map< _Key, _Tp, _Compare, _Alloc >::insert(), and menuMap.
Referenced by Menu4D().
void C4DView::Menu4D::Light () [slot]
"Appearance/Lighting" menu item selected
Switch lighting on or off
Change menu items accordingly
References _parent, getAction(), UI::ViewImpl::getLighting(), and C4DView::setLighting().
Referenced by Menu4D().
void C4DView::Menu4D::ObjectGasket () [slot]
"Object/Objects/Sierpinski Gasket" menu item selected
Display a Gasket object
References _parent, and C4DView::ObjectGasket().
Referenced by Menu4D().
void C4DView::Menu4D::ObjectHypercube () [slot]
"Object/Objects/Hypercube" menu item selected
Display a Hypercube object
References _parent, and C4DView::ObjectHypercube().
Referenced by Menu4D().
void C4DView::Menu4D::ObjectHyperpyramid () [slot]
"Object/Objects/Hyperpyramid" menu item selected
Display a Hyperpyramid object
References _parent, and C4DView::ObjectHyperpyramid().
Referenced by Menu4D().
void C4DView::Menu4D::ObjectHypersponge () [slot]
"Object/Objects/Menger Sponge" menu item selected
Display a Hypersponge object
References _parent, and C4DView::ObjectHypersponge().
Referenced by Menu4D().
void C4DView::Menu4D::ObjectRotope () [slot]
"Object/Objects/Rotope" menu item selected
Display a Rotope object
References _parent, and C4DView::ObjectRotope().
Referenced by Menu4D().
void C4DView::Menu4D::RandomAnimation () [slot]
"Animation/Random Animation" menu item selected
Animate the object whith the rotation of the animation changing randomly every couple of seconds
References _parent, and C4DView::RandomAnimation().
Referenced by Menu4D().
void C4DView::Menu4D::RenderToImages () [slot]
"Animation/Render to Images" menu item selected
Switch rendering to files on or off
Change menu items accordingly
References _parent, getAction(), UI::ViewImpl::getWriteImages(), and UI::ViewImpl::setWriteImages().
Referenced by Menu4D().
void C4DView::Menu4D::setBackground () [slot]
"Appearance/Set Background Color" menu item selected
Pop up a color selector and set the background to the chosen color
References _parent, and C4DView::setBackground().
Referenced by Menu4D().
void C4DView::Menu4D::Shade () [slot]
"Appearance/Shading" menu item selected
Toggle shading
References _parent, getAction(), UI::ViewImpl::getShading(), and C4DView::setShading().
Referenced by Menu4D().
void C4DView::Menu4D::Transparent () [slot]
"Appearance/Transparence" menu item selected
Toggle object transparency
References _parent, getAction(), UI::ViewImpl::getTransparence(), and C4DView::setTransparence().
Referenced by Menu4D().
void C4DView::Menu4D::updateFunctionMenu (const QString & item)
Set the selected function as checked and uncheck all the others.
Parameters:
item Title of the item whose checking status is toggled
References _fcc, _fr3r, _functions, _objects, _surfaces, std::map< _Key, _Tp, _Compare, _Alloc >::begin(), std::map< _Key, _Tp, _Compare, _Alloc >::end(), getAction(), and menuMap.
Referenced by C4DView::ObjectGasket(), C4DView::ObjectHypercube(), C4DView::ObjectHyperpyramid(), C4DView::ObjectHypersponge(), and C4DView::ObjectRotope().
void C4DView::Menu4D::Wireframe () [slot]
"Appearance/Wireframe" menu item selected
Switch between wireframe and solid display
Account for antialiasing only in wireframe mode
Change menu items accordingly
References _parent, getAction(), UI::ViewImpl::getSolid(), C4DView::paintEvent(), and UI::ViewImpl::setSolid().
Referenced by Menu4D().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/UI/Menu4D.H
HyperspaceExplorer/src/UI/Menu4D.C