HyperspaceExplorer: C4DView::FunctionSlot< function > Class Template Reference
C4DView::FunctionSlot< function > Class Template Reference
[Helper classes for User Interface classes]
Class template to outsource redundant code.
#include <4DView.H>
Static Public Member Functions
static void createFunction (C4DView *view)
Factory method to create a new Function of type R^3->R.
static void createSurface (C4DView *view)
Factory method to create a new Function of type R^2->R^4.
static void createObject (C4DView *view)
Detailed Description
template<class function>
class C4DView::FunctionSlot< function >
Class template to outsource redundant code.
Class template to outsource redundant code for the generation of functions in a slot called by QActions from the QMenu
Parameters:
function the Function to be created in the slot
Member Function Documentation
template<class function> void C4DView::FunctionSlot< function >::createFunction (C4DView * view) [inline, static]
Factory method to create a new Function of type R^3->R.
This function template is called by each slot with the correct function type as template parameter.
Sets F to the newly created Function, checks the corresponding menu item, updates the ValuesDialog and redraws.
References C4DView::AssignValues(), ValuesDialogImpl::dt(), ValuesDialogImpl::du(), ValuesDialogImpl::dv(), C4DView::F, Loki::SingletonHolder< T, CreationPolicy >::Instance(), C4DView::menu, C4DView::Redraw(), ValuesDialogImpl::tmax(), ValuesDialogImpl::tmin(), ValuesDialogImpl::umax(), ValuesDialogImpl::umin(), Menu4D::updateFunctionMenu(), C4DView::Values, ValuesDialogImpl::vmax(), and ValuesDialogImpl::vmin().
template<class function> void C4DView::FunctionSlot< function >::createSurface (C4DView * view) [inline, static]
Factory method to create a new Function of type R^2->R^4.
This function template is called by each slot with the correct function type as template parameter.
Sets F to the newly created Function, checks the corresponding menu item, updates the ValuesDialog and redraws.
References C4DView::AssignValues(), ValuesDialogImpl::dt(), ValuesDialogImpl::du(), C4DView::F, C4DView::menu, C4DView::Redraw(), ValuesDialogImpl::tmax(), ValuesDialogImpl::tmin(), ValuesDialogImpl::umax(), ValuesDialogImpl::umin(), Menu4D::updateFunctionMenu(), and C4DView::Values.
The documentation for this class was generated from the following file:
workspace/HyperspaceExplorer/src/UI/4DView.H