HyperspaceExplorer: C4DView::MenuHandler Class Reference
C4DView::MenuHandler Class Reference
Callback functions for menu items.
#include <MenuHandler.H>
Public Slots
void Wireframe ()
Switch between wireframe and solid display.
void Coordinates ()
Switch coordinate cross on or off.
void HyperFog ()
Switch 4D depth cue on or off.
void Light ()
Switch lighting on or off.
void Colors ()
Toggle colors.
void Fog ()
Toggle fog/depth cue.
void Transparent ()
Toggle object transparency.
void Shade ()
Toggle shading.
void Benchmark ()
Run a benchmark test.
void RenderToImages ()
Switch rendering to files on or off.
void ObjectHypercube ()
Display a ObjectHypercube object.
void ObjectHyperpyramid ()
Display a ObjectHyperpyramid object.
void ObjectHypersponge ()
Display a ObjectHypersponge object.
void ObjectGasket ()
Display a ObjectGasket object.
void customFunction ()
Display a customFunction object.
void customPolarFunction ()
Display a customPolarFunction object.
void customSurface ()
Display a customSurface object.
void customComplexFunction ()
Display a customComplexFunction object.
void AnimationSettings ()
Show a dialog to adjust animation settings.
void Help ()
Display help window.
void about ()
Open an "About"-Dialog.
void aboutQt ()
Open an "About Qt"-Dialog.
Public Member Functions
MenuHandler (C4DView *parent)
Private Attributes
C4DView * m_parent
The associated C4DView.
Detailed Description
Callback functions for menu items.
Basically, all member functions are slots called by the Menu4D's items.
Most of these slots must translate a parameter-less call to a state change in the associated C4DView.
Todo:
Rework the member functions so that they work with a generic UI::View object instead of an explicitly specified C4DView.
Member Function Documentation
void C4DView::MenuHandler::Wireframe () [slot]
Switch between wireframe and solid display.
Account for antialiasing only in wireframe mode
Change menu items accordingly
References C4DView::DisplayPolygons(), C4DView::Menu4D::getAction(), m_parent, C4DView::Menu(), C4DView::OnPaint(), and C4DView::setWireframe().
void C4DView::MenuHandler::Coordinates () [slot]
Switch coordinate cross on or off.
Change menu items accordingly
References C4DView::DisplayCoordinates(), m_parent, and C4DView::setCoordinates().
void C4DView::MenuHandler::HyperFog () [slot]
Switch 4D depth cue on or off.
Change menu items accordingly
References C4DView::DepthCue4D(), m_parent, and C4DView::setHyperfog().
void C4DView::MenuHandler::Light () [slot]
Switch lighting on or off.
Change menu items accordingly
Todo:
uses hardcoded values for light attributes
Todo:
move all the GL stuff away from the menu handler, back into C4DView
References C4DView::Lighting(), m_parent, C4DView::OnPaint(), and C4DView::setLighting().
Referenced by C4DView::C4DView().
void C4DView::MenuHandler::RenderToImages () [slot]
Switch rendering to files on or off.
Change menu items accordingly
References C4DView::Menu4D::getAction(), m_parent, C4DView::Menu(), C4DView::RenderToPixmap(), and C4DView::setRenderToPixmap().
void C4DView::MenuHandler::AnimationSettings () [slot]
Show a dialog to adjust animation settings.
Where to write image files and how many files to write.
References C4DView::animationDirectory(), C4DView::animationMaxFrames(), C4DView::animationPrefix(), AnimationDialogImpl::getDir(), AnimationDialogImpl::getFrames(), AnimationDialogImpl::getPrefix(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), m_parent, C4DView::setanimationDirectory(), C4DView::setanimationMaxFrames(), and C4DView::setanimationPrefix().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/UI/MenuHandler.H
HyperspaceExplorer/src/UI/MenuHandler.C