HyperspaceExplorer: Script::Statement Class Reference
Script::Statement Class Reference
[Statements possible in a script]
Base class for all possible statements in a script.
#include <Statement.H>
Public Member Functions
Statement (const Parser *parser, const std::string &arg)
virtual bool execute ()
Executes the statement in the current context.
Protected Member Functions
const std::string & arg ()
const Parser * parser ()
Private Attributes
std::string _arg
Argument(s) following the statement.
const Parser * _parser
The current context.
Detailed Description
Base class for all possible statements in a script.
This class represents the class AbstractExpression in the class diagram for the Interpreter pattern as implemented in the GOF book, p. 245
Constructor & Destructor Documentation
Script::Statement::Statement (const Parser * parser, const std::string & arg) [inline]
Parameters:
parser The context in which the Statement is executed
arg The argument supplied to the Statement
Member Function Documentation
const std::string& Script::Statement::arg () [inline, protected]
Returns:
Argument(s) following the statement
References _arg.
Referenced by Script::ImgPrefixStmt::execute(), Script::ImgDirStmt::execute(), Script::CoordsStmt::execute(), Script::RotDeltaStmt::execute(), Script::RotStmt::execute(), Script::ParmStmt< T >::execute(), Script::ObjectStmt::execute(), execute(), Script::FramesStmt::FramesStmt(), Script::LoopStmt::LoopStmt(), Script::SizeStmt::SizeStmt(), Script::SleepStmt::SleepStmt(), and Script::XformStmt::XformStmt().
const Parser* Script::Statement::parser () [inline, protected]
Returns:
The current context
References _parser.
Referenced by Script::ImgPrefixStmt::execute(), Script::ImgDirStmt::execute(), Script::AnimateStmt::execute(), Script::Fog4DStmt::execute(), Script::FogStmt::execute(), Script::SolidStmt::execute(), Script::WireStmt::execute(), Script::TransStmt::execute(), Script::LightStmt::execute(), Script::ShadingStmt::execute(), Script::ColorStmt::execute(), Script::LoopStmt::execute(), Script::FramesStmt::execute(), Script::DeltaStmt::execute(), Script::XformStmt::execute(), Script::ParmStmt< T >::execute(), Script::ObjectStmt::execute(), and Script::SizeStmt::execute().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Script/Statement.H
HyperspaceExplorer/src/Script/Statement.C