HyperspaceExplorer: UI::ViewImpl Class Reference
UI::ViewImpl Class Reference
[User Interface]
Interface with attributes to display four-dimensional objects.
#include <ViewImpl.H>
Public Member Functions
ViewImpl ()
Initialize the View with default values for all states.
virtual const std::auto_ptr
< Function > & F () const
virtual void setF (Function *_f)
Implementation of UI::View::setFunction.
virtual const
VecMath::Rotation< 4 > & getdR ()
virtual void setdR (const VecMath::Rotation< 4 > &_dr)
Set the rotation step between frames for animations.
virtual void setNumFrames (unsigned frames)
Set the number of frames for an animation.
virtual void setNumLoops (unsigned loops)
Set the number of times _numFrames are repeated.
virtual const std::string & getImgDir ()
virtual void setImgDir (const std::string &)
Set the directory where to store image files.
virtual const std::string & getImgPrefix ()
virtual void setImgPrefix (const std::string &)
Set the prefix of image file names, before the frame number and the extension.
virtual const Color & getBackground ()
virtual void setBackground (const Color &bg)
Set the background color.
virtual void addLight (Light *l)
Add a light source to the scene.
virtual void removeLight (std::vector< Light * >::iterator)
Remove a light source from the scene.
virtual const std::vector
< Light * > & getLights ()
virtual bool getColors () const
virtual void setColors (bool on)
Turn display of colors on or off.
virtual bool getCoordinates () const
virtual void setCoordinates (bool on)
Turn display of coordinate cross on or off.
virtual bool getFog () const
virtual void setFog (bool on)
Turn depth cue on or off.
virtual bool getHyperfog () const
virtual void setHyperfog (bool on)
Turn depth cue in four dimensions on or off.
virtual bool getLighting () const
virtual void setLighting (bool on)
Turn lighting on or off.
virtual bool getShading () const
virtual void setShading (bool on)
Turn gouraud shading on or off.
virtual bool getSolid () const
virtual void setSolid (bool on)
Turn wireframe display on or off.
virtual bool getTransparence () const
virtual void setTransparence (bool on)
Turn transparenc/line antialiasing on or off.
Protected Member Functions
virtual unsigned getNumFrames ()
Number of frames for animations.
virtual unsigned getNumLoops ()
Number of loops to repeat an animation.
virtual bool getWriteImages ()
virtual void setWriteImages (bool on)
Turn saving images to file system on or off.
virtual void setDefaultBackground ()
Set a default background color.
virtual void setT (const VecMath::Vector< 4 > &_t)
virtual const VecMath::Vector< 4 > & T ()
virtual void addT (const VecMath::Vector< 4 > &_dT)
Add a Translation to the current translation state.
virtual void setR (const VecMath::Rotation< 4 > &_r)
virtual const
VecMath::Rotation< 4 > & R ()
virtual void addR (const VecMath::Rotation< 4 > &_dR)
Add a Rotation to the current rotation state.
virtual void adddR (const VecMath::Rotation< 4 > &)
Add a Rotation to the current rotation speed.
double CamW () const
void setCamW (const double &_cw)
double ScrW () const
void setScrW (const double &_sw)
double distance ()
Viewport distance; currently fixed to 1.
Static Protected Member Functions
static const LightSource & getDefaultLightSource ()
static const LightSource & getFlatLightSource ()
Private Attributes
std::auto_ptr< Function > _F
the Function object currently displayed
bool _colors
whether to use colors in rendering
bool _coordinates
whether to display the 4D coordinate cross
bool _fog
whether to use depth cue/fog in rendering
bool _hyperfog
whether to use four-dimensional depth cue
bool _lighting
whether to use lighting in rendering
bool _shading
whether to use shading in rendering
bool _solid
whether to draw the objects' surfaces
bool _transparence
whether to use transparence/line antialiasing
std::vector< Light * > _lights
Stores all the lights in the scene.
Color _background
background color
VecMath::Rotation< 4 > _dR
delta values in angles for 4D rotation for animations
VecMath::Vector< 4 > _T
coordinates for 4D translation
VecMath::Rotation< 4 > _R
angles for 4D rotation
double _camW
W coordinate of the camera.
double _scrW
W coordinate of the screen.
unsigned _numFrames
number of frames for animations
unsigned _numLoops
number of loops to repeat an animation
bool _writeImages
whether to save images to file system
std::string _imageDir
directory to save images to
std::string _imagePrefix
filename prefix for saved images
Static Private Attributes
static Color _defaultBackground
Default Color for the background.
static LightSource _defaultLightSource
Point LightSource with sensible defaults for good light.
static LightSource _flatLightSource
LightSource for flat, all-ambient lighting.
Detailed Description
Interface with attributes to display four-dimensional objects.
This class provides a partial implementation of the class View, with the class attributes and their getters and setters.
It also stores view states, which are common to all implementations, such as:
The object which is currently displayed
The 4D transformation of that object
The 4D viewport (camera and screen position)
Member Function Documentation
virtual const std::auto_ptr<Function>& UI::ViewImpl::F () const [inline, virtual]
Returns:
The currently displayed object
Implements UI::View.
References _F.
Referenced by C4DView::ApplyChanges(), C4DView::C4DView(), C4DView::CustomFunctionSlot< function >::createCustomFunction(), C4DView::CustomFunctionSlot< function >::createCustomSurface(), C4DView::ObjectGasket(), C4DView::ObjectHypercube(), C4DView::ObjectHyperpyramid(), C4DView::ObjectHypersponge(), C4DView::ObjectRotope(), C4DView::PreRedraw(), C4DView::Project(), SurfaceSlotHelper::slot(), FunctionSlotHelper::slot(), C4DView::Transform(), and C4DView::UpdateStatus().
virtual const VecMath::Rotation<4>& UI::ViewImpl::getdR () [inline, virtual]
Returns:
delta values in angles for 4D rotation for animations
Implements UI::View.
References _dR.
Referenced by adddR(), C4DView::animate(), C4DView::MouseHandler4D::mouseMoveEvent(), C4DView::OnAnimationTimer(), and C4DView::StartAnimation().
virtual void UI::ViewImpl::setdR (const VecMath::Rotation< 4 > & _dr) [inline, virtual]
Set the rotation step between frames for animations.
Parameters:
_dr Rotation step between two frames of an animation
Implements UI::View.
References _dR.
Referenced by adddR(), C4DView::RandomAnimation(), and C4DView::StopAnimation().
virtual const std::string& UI::ViewImpl::getImgDir () [inline, virtual]
Returns:
directory to save images to
Implements UI::View.
References _imageDir.
Referenced by C4DView::Menu4D::AnimationSettings(), and C4DView::writeFrame().
void UI::ViewImpl::setImgDir (const std::string & s) [virtual]
Set the directory where to store image files.
Parameters:
s Directory where to store image files
Implements UI::View.
References _imageDir, and setWriteImages().
Referenced by C4DView::Menu4D::AnimationSettings().
virtual const std::string& UI::ViewImpl::getImgPrefix () [inline, virtual]
Returns:
filename prefix for saved images
Implements UI::View.
References _imagePrefix.
Referenced by C4DView::Menu4D::AnimationSettings(), and C4DView::writeFrame().
void UI::ViewImpl::setImgPrefix (const std::string & s) [virtual]
Set the prefix of image file names, before the frame number and the extension.
Parameters:
s Filename prefix for saved images
Implements UI::View.
References _imagePrefix, and setWriteImages().
Referenced by C4DView::Menu4D::AnimationSettings().
virtual const Color& UI::ViewImpl::getBackground () [inline, virtual]
Returns:
The background color
Implements UI::View.
References _background.
virtual void UI::ViewImpl::addLight (Light * l) [inline, virtual]
Add a light source to the scene.
Parameters:
l Light source added to the scene
Implements UI::View.
References _lights, and std::vector< _Tp, _Alloc >::push_back().
virtual const std::vector<Light *>& UI::ViewImpl::getLights () [inline, virtual]
Returns:
All lights in the scene
Todo:
Abstract from std::vector and use a generic container
Implements UI::View.
References _lights.
virtual bool UI::ViewImpl::getColors () const [inline, virtual]
Returns:
whether to use colors in rendering or not
Implements UI::View.
References _colors.
Referenced by C4DView::Menu4D::Colors(), and C4DView::Menu4D::Menu4D().
virtual bool UI::ViewImpl::getCoordinates () const [inline, virtual]
Returns:
whether to display the 4D coordinate cross or not
Implements UI::View.
References _coordinates.
Referenced by C4DView::Menu4D::Coordinates(), C4DView::Menu4D::Menu4D(), C4DView::PreRedraw(), C4DView::Project(), and C4DView::RenderScene().
virtual bool UI::ViewImpl::getFog () const [inline, virtual]
Returns:
whether to use depth cue/fog in rendering or not
Implements UI::View.
References _fog.
Referenced by C4DView::Menu4D::Fog(), C4DView::InitFog(), C4DView::Menu4D::Menu4D(), C4DView::MouseHandler4D::mouseMoveEvent(), and C4DView::resizeGL().
virtual bool UI::ViewImpl::getHyperfog () const [inline, virtual]
Returns:
whether to use four-dimensional depth cue or not
Implements UI::View.
References _hyperfog.
Referenced by C4DView::Menu4D::HyperFog(), and C4DView::Project().
virtual bool UI::ViewImpl::getLighting () const [inline, virtual]
Returns:
whether to use lighting in rendering or not
Implements UI::View.
References _lighting.
Referenced by C4DView::InitLight(), C4DView::Menu4D::Light(), C4DView::Menu4D::Menu4D(), and C4DView::setLighting().
virtual bool UI::ViewImpl::getShading () const [inline, virtual]
Returns:
whether to use shading in rendering or not
Implements UI::View.
References _shading.
Referenced by C4DView::InitShade(), C4DView::Menu4D::Menu4D(), and C4DView::Menu4D::Shade().
virtual bool UI::ViewImpl::getSolid () const [inline, virtual]
Returns:
whether to draw the objects' surfaces
Implements UI::View.
References _solid.
Referenced by C4DView::initializeGL(), C4DView::Menu4D::Menu4D(), C4DView::paintEvent(), and C4DView::Menu4D::Wireframe().
virtual void UI::ViewImpl::setSolid (bool on) [inline, virtual]
Turn wireframe display on or off.
Parameters:
on if true, displays wireframe model; else solid
Implements UI::View.
References _solid.
Referenced by C4DView::Menu4D::Menu4D(), and C4DView::Menu4D::Wireframe().
virtual bool UI::ViewImpl::getTransparence () const [inline, virtual]
Returns:
whether to use transparence/line antialiasing or not
Implements UI::View.
References _transparence.
Referenced by C4DView::InitTransparence(), C4DView::Menu4D::Menu4D(), and C4DView::Menu4D::Transparent().
virtual bool UI::ViewImpl::getWriteImages () [inline, protected, virtual]
Returns:
whether to save images to file system
Implements UI::View.
References _writeImages.
Referenced by C4DView::initializeGL(), C4DView::Menu4D::Menu4D(), C4DView::Menu4D::RenderToImages(), and C4DView::writeFrame().
virtual void UI::ViewImpl::setT (const VecMath::Vector< 4 > & _t) [inline, protected, virtual]
Parameters:
_t New translation state
References _T.
Referenced by C4DView::Transform().
virtual const VecMath::Vector<4>& UI::ViewImpl::T () [inline, protected, virtual]
Returns:
Current translation state
References _T.
Referenced by C4DView::MouseHandler4D::mouseMoveEvent(), C4DView::OnAnimationTimer(), and C4DView::Transform().
virtual void UI::ViewImpl::addT (const VecMath::Vector< 4 > & _dT) [inline, protected, virtual]
Add a Translation to the current translation state.
Parameters:
_dT Delta t
References _T.
Referenced by C4DView::MouseHandler4D::mouseMoveEvent().
virtual void UI::ViewImpl::setR (const VecMath::Rotation< 4 > & _r) [inline, protected, virtual]
Parameters:
_r New rotation state
References _R.
Referenced by C4DView::Transform().
virtual const VecMath::Rotation<4>& UI::ViewImpl::R () [inline, protected, virtual]
Returns:
Current rotation state
References _R.
Referenced by C4DView::animate(), C4DView::Benchmark3D(), C4DView::checkAnglesForOverflow(), C4DView::MouseHandler4D::mouseMoveEvent(), C4DView::OnAnimationTimer(), and C4DView::Transform().
void UI::ViewImpl::adddR (const VecMath::Rotation< 4 > & ddR) [protected, virtual]
Add a Rotation to the current rotation speed.
Parameters:
ddR Rotation to be added to the current Rotation state
References getdR(), and setdR().
Referenced by C4DView::MouseHandler4D::mouseMoveEvent().
double UI::ViewImpl::CamW () const [inline, protected]
Returns:
W coordinate of the camera
References _camW.
Referenced by C4DView::Project().
void UI::ViewImpl::setCamW (const double & _cw) [inline, protected]
Parameters:
_cw W coordinate of the camera
References _camW.
double UI::ViewImpl::ScrW () const [inline, protected]
Returns:
W coordinate of the screen to project onto
References _scrW.
Referenced by C4DView::Project().
void UI::ViewImpl::setScrW (const double & _sw) [inline, protected]
Parameters:
_sw W coordinate of the screen to project onto
References _scrW.
static const LightSource& UI::ViewImpl::getDefaultLightSource () [inline, static, protected]
Returns:
Point LightSource with sensible defaults for good light
References _defaultLightSource.
static const LightSource& UI::ViewImpl::getFlatLightSource () [inline, static, protected]
Returns:
LightSource for flat, all-ambient lighting
References _flatLightSource.
Member Data Documentation
std::vector<Light *> UI::ViewImpl::_lights [private]
Stores all the lights in the scene.
Todo:
Abstract from std::vector and use a generic container
Referenced by addLight(), getLights(), and removeLight().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/UI/ViewImpl.H
HyperspaceExplorer/src/UI/ViewImpl.C