HyperspaceExplorer: Global Class Reference
Global Class Reference
#include <Globals.H>
Public Member Functions
QAction * getQuitAction () const
QMainWindow * getMainWindow () const
int GetGLList ()
Color & FogColor ()
void setFogColor (const Color &rgba)
double atod (QString)
double atod (const std::string &)
int atoi (const std::string &)
unsigned atou (const std::string &)
std::string itoa (int x)
std::string ftoa (double x)
void CheckGLErrors (const char *op=0)
void glVertex (VecMath::Vector< 3 > &V)
VecMath::Vector< 3 > vnormalize (double xx, double yy, double zz)
Static Public Member Functions
static unsigned long getMaxMemory ()
static Color & white ()
static Color & grey50 ()
static bool checkMemory ()
Public Attributes
QStringList rcdirs
const double SR3
Static Private Member Functions
static unsigned long check_proc_meminfo ()
Private Attributes
QMainWindow * mainWindow
QAction * quitAction
Static Private Attributes
static bool check_memory = false
static Color fog_color
static Color White
static Color Grey50
static unsigned long MaximumMemory = check_proc_meminfo ()
Detailed Description
As a workaround to end the embarassing practice of keeping global variables, I have created this class as a singleton. You might also call it a namespace.
I plan to advance this class to a full-blown registry though. One day.
Members are accessed with the SingletonHolder static function, i.e. Globals::Instance().
Author:
Helge Preuss <scout@hyperspace-travel.de>
Member Function Documentation
int Global::GetGLList ()
find the ID of the first free GL list
Returns:
first freee GL list
double Global::atod (QString s)
makes a double precision value from a QString implemented because I called a function atod () ages ago, for convenience
Parameters:
s string to be converted
Returns:
its numerical value
string Global::itoa (int x)
makes a string from an integer value implemented because I called a function itoa () ages ago, for convenience
Parameters:
x number to be converted
Returns:
its string representation
Referenced by VecMath::Matrix< D, N >::Matrix().
string Global::ftoa (double x)
makes a string from a double value implemented because I called a function ftoa () ages ago, for convenience
Parameters:
x number to be converted
Returns:
its string representation
void Global::CheckGLErrors (const char * op = 0)
debug function for OpenGL commands; outputs all current GL errors on cerr
Parameters:
op optional repetition of last GL command
void Global::glVertex (VecMath::Vector< 3 > & V) [inline]
define a GL Vertex from a Vector<3>
Parameters:
V the vertex to be defined
References VecMath::Vector< D, N >::data(), and VecMath::Vector< D, N >::sqnorm().
Vector< 3 > Global::vnormalize (double xx, double yy, double zz)
normalizes a Vector made from 3 doubles out-of-place
Parameters:
xx x component of Vector to be normalized
yy y component of Vector to be normalized
zz z component of Vector to be normalized
Returns:
normalized Vector
References VecMath::vnormalize().
static unsigned long Global::getMaxMemory () [inline, static]
maximum amount of memory available for use
References MaximumMemory.
static Color& Global::white () [inline, static]
color definition for White
References White.
static Color& Global::grey50 () [inline, static]
color definition for Grey
References Grey50.
unsigned long Global::check_proc_meminfo () [static, private]
get the system memory from /proc/meminfo of course, this only works on OS's with /proc filesystem and /proc/meminfo information! relies on /proc/meminfo of being of the format: MemTotal: 506912 kB ... returns 512 MB as default memory size, when /proc/meminfo is not present
Returns:
total memory size, or 512 MB
References check_memory.
Member Data Documentation
QStringList Global::rcdirs
why tf did i make that global again? damn, i really should write comments immediately after writing the code</rant>
const double Global::SR3
sqrt (3), stored to save computation time, probably superfluous
bool Global::check_memory = false [static, private]
whether to check for memory usage. this member is set or unset from check_proc_meminfo(), depending on the success of that function.
Referenced by check_proc_meminfo().
Color Global::fog_color [static, private]
global (YUCK!) background color global (YUCK!) fog/depth cue color
Color Global::White [static, private]
color definition for White
Referenced by white().
Color Global::Grey50 [static, private]
color definition for Grey
Referenced by grey50().
unsigned long Global::MaximumMemory = check_proc_meminfo () [static, private]
maximum amount of memory available for use
maximum memory that should be consumed; calls check_proc_meminfo () above
Referenced by getMaxMemory().
QMainWindow* Global::mainWindow [private]
main window of the application
QAction* Global::quitAction [private]
global QAction that quits the program
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Globals.H
HyperspaceExplorer/src/Globals.C