HyperspaceExplorer: Script::LoopStmt Class Reference
Script::LoopStmt Class Reference
[Statements possible in a script]
"loop <num_loops>"
#include <Statement.H>
Public Member Functions
LoopStmt (const Parser *p, const std::string &_arg)
virtual bool execute ()
Executes the statement in the current context.
Private Attributes
unsigned _loops
Number of times to loop.
Detailed Description
"loop <num_loops>"
set the number of loops, ie. repetitions of num_frames frames
Constructor & Destructor Documentation
Script::LoopStmt::LoopStmt (const Parser * p, const std::string & _arg)
Parameters:
p The context in which the Statement is executed
_arg The argument supplied to the Statement
References _loops, Script::Statement::arg(), Loki::SingletonHolder< T, CreationPolicy >::Instance(), and Script::trailing().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Script/Statement.H
HyperspaceExplorer/src/Script/Statement.C