HyperspaceExplorer: C4DView::TemplatedSurfaceFactory< function > Class Template Reference
C4DView::TemplatedSurfaceFactory< function > Class Template Reference
[Helper classes for User Interface classes]
Class template implementation for a factory creating Surface's.
#include <4DView.H>
Private Member Functions
virtual Surface * doCreateSurface (C4DView *)
Implementation of TemplateMethod createSurface().
Detailed Description
template<typename function>
class C4DView::TemplatedSurfaceFactory< function >
Class template implementation for a factory creating Surface's.
The type of the Surface to be created by the factory method of this class is passed as a template parameter.
Separate classes are needed for Functions and Surfaces, because their constructors differ.
Member Function Documentation
template<class function> Surface * C4DView::TemplatedSurfaceFactory< function >::doCreateSurface (C4DView * view) [inline, private, virtual]
Implementation of TemplateMethod createSurface().
Factory method to create a Surface object.
The type of the created Surface is supplied as template parameter to the TemplatedSurfaceFactory object owning this method.
Implements SurfaceFactory.
References UI::Dialogs::ValuesDialogImpl::du(), UI::Dialogs::ValuesDialogImpl::dv(), UI::Dialogs::ValuesDialogImpl::umax(), UI::Dialogs::ValuesDialogImpl::umin(), C4DView::Values(), UI::Dialogs::ValuesDialogImpl::vmax(), and UI::Dialogs::ValuesDialogImpl::vmin().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/UI/4DView.H
HyperspaceExplorer/src/UI/TemplatedFunctionFactory.impl.H