HyperspaceExplorer: Sponge Class Reference
Sponge Class Reference
[Arbitrary four-dimensional objects, described by their surfaces]
A four-dimensional Menger Sponge.
#include <Object.H>
Public Member Functions
Sponge (unsigned _level=1, unsigned _distance=2, double _rad=0.8, VecMath::Vector< 4 > _center=VecMath::Vector< 4 >(0., 0., 0., 0.))
Sponge constructor.
virtual ~Sponge ()
Sponge destructor.
virtual void Transform (const VecMath::Rotation< 4 > &R, const VecMath::Vector< 4 > &T)
Transforms a Sponge.
virtual void Project (double ScrW, double CamW, bool DepthCue4D)
Projects a Sponge into three-space.
virtual void Draw (void)
Draw the projected Sponge (onto screen or into GL list, as it is).
virtual void SetParameters (const ParameterMap &parms)
Set parameters to the Function.
virtual void ReInit (double, double, double, double, double, double, double, double, double)
Rebuild the Sponge if the parameters have changed.
virtual std::string description ()
Protected Member Functions
virtual void Initialize ()
This function actually creates the hypersponge.
virtual unsigned long MemRequired (unsigned)
return the approximate amount of memory needed to display a sponge of current level and given distance
Protected Attributes
unsigned Level
Level of the hypersponge.
std::vector< Hypercube * > List
List of sub-sponges (see Initialize()).
int distance
max. distance (see Initialize())
double rad
radius, more correctly size, of the sponge
VecMath::Vector< 4 > center
center of the sponge
Detailed Description
A four-dimensional Menger Sponge.
A Menger Sponge in three dimensions is a fractal produced by subdividing a cube and taking away parts of the cube which get subsequentally smaller. The level parameter controls how often this process is repeated, i.e. how many holes there are in the final object.
A four-dimensional Menger Sponge is created analogously from a hypercube.
The fractal can be further controlled by the distance parameter:
distance = 0: Only the innermost cube is removed, resulting in a four-dimensional foam with connected body and disjoint holes.
distance = 1: the innermost and the next to innermost cubes are removed, which results in a foam in three dimensions, but has holes in the four-dimensional structure.
distance = 2: the holes reach the surface of the cube, resulting in a sponge structure - both the holes and the cubes ("curd") are connected.
distance = 3: only the corners of the hypercube remain, resulting in dust - the "curd" is disjoint, the holes are connected.
Constructor & Destructor Documentation
Sponge::Sponge (unsigned _level = 1, unsigned _distance = 2, double _rad = 0.8, VecMath::Vector< 4 > _center = VecMath::Vector< 4 >(0., 0., 0., 0.))
Sponge constructor.
Parameters:
_level hypersponge level
_distance distance of subcubes to center to be counted as part of the fractal
= 0: solid hypercube
= 1: foam
= 2: sponge
= 3: dust
>= 4: nothing
_rad side_length/2
_center center
Member Function Documentation
void Sponge::Transform (const VecMath::Rotation< 4 > & R, const VecMath::Vector< 4 > & T) [virtual]
Transforms a Sponge.
The transformation is achieved by transforming all constituting sub-sponges.
Parameters:
R rotation
T translation
Reimplemented from Object.
References List, and Function::Transform().
void Sponge::Project (double scr_w, double cam_w, bool depthcue4d) [virtual]
Projects a Sponge into three-space.
The projection is achieved by projecting all constituting sub-sponges.
Parameters:
scr_w w coordinate of screen
cam_w w coordinate of camera
depthcue4d wheter to use hyperfog/dc
Reimplemented from Object.
References List.
void Sponge::Draw (void) [virtual]
Draw the projected Sponge (onto screen or into GL list, as it is).
Draws all sub-sponges, recursively.
Reimplemented from Object.
References Level, and List.
virtual std::string Sponge::description () [inline, virtual]
Returns:
A string with a description of the Hypersponge object
Reimplemented from Hypercube.
References Level.
void Sponge::Initialize (void) [protected, virtual]
This function actually creates the hypersponge.
It views it as an assembly of smaller sponges, slicing the sponge in three sub-sponges in every one of the four dimensions, and then taking away some of the resulting 81 smaller sub-sponges.
if the parameter distance is zero, it only removes the sub-sponge with distance 0 from the center, i.e. the one at the center.
if the parameter distance is one, it only removes the sub-sponges with distance <= 1, amounting to nine removed sub-sponges. The three- dimensional surface of the hypercube enveloping the sponge is not breached, because the surface of a hypercube is two units away from the center, instead of one unit, as in 3D.
if distance = 2, the holes reach the hypercubes surface, giving an object analogous to the three-dimensional Menger Sponge.
if distance = 3, only the 16 corners of the hypercube remain, giving four-dimensional fractal dust.
If the level of the sponge is 1, the sub-sponges are hypercubes. Otherwise, they are Hypersponges with a level reduced by 1.
Reimplemented from Hypercube.
References center, distance, Loki::SingletonHolder< T, CreationPolicy >::Instance(), Level, List, Function::MemRequired(), and rad.
unsigned long Sponge::MemRequired (unsigned distance) [protected, virtual]
return the approximate amount of memory needed to display a sponge of current level and given distance
Todo:
uses hardcoded and experimentally found value for memory per hypercube
Parameters:
distance see Initialize()
Returns:
approx. mem required
References Level.
Member Data Documentation
std::vector<Hypercube *> Sponge::List [protected]
List of sub-sponges (see Initialize()).
Todo:
Use smart pointers instead of a simple pointer-to-object
Referenced by Draw(), Initialize(), Project(), ReInit(), Transform(), and ~Sponge().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Functions/Object.H
HyperspaceExplorer/src/Functions/Object.C