HyperspaceExplorer: VecMath::Matrix< D, N > Class Template Reference
VecMath::Matrix< D, N > Class Template Reference
[Vector and Matrix algebra]
#include <Matrix.H>
Public Member Functions
Matrix ()
Matrix (N, N, N, N, N, N)
Matrix (unsigned, unsigned, N)
N & operator() (unsigned i, unsigned j)
Matrix< D, N > operator*= (const Matrix< D, N > &)
Matrix< D, N > operator* (const Matrix< D, N > &) const
Vector< D, N > operator* (const Vector< D, N > &)
Matrix< D, N > operator- ()
std::string Print ()
Private Attributes
N M [D][D]
A static two-dimensional array storing the components.
Detailed Description
template<unsigned D, typename N = double>
class VecMath::Matrix< D, N >
Matrix<D, N>: a DxD matrix of numbers of type N
Parameters:
D dimension of the matrix
N numerical type of the matrix elements
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
template<unsigned D, typename N> VecMath::Matrix< D, N >::Matrix () [inline]
default constructor: creates a unit DxD Matrix
References VecMath::Matrix< D, N >::M.
template<unsigned D, typename N> VecMath::Matrix< D, N >::Matrix (N Rxy, N Rxz, N Rxw, N Ryz, N Ryw, N Rzw) [inline]
creates a DxD rotation Matrix, where D=4, not yet implemented
Parameters:
Rxy rotation around xy plane (z axis)
Rxz rotation around xz plane (y axis)
Rxw rotation around xw plane
Ryz rotation around xy plane (x axis)
Ryw rotation around yw plane
Rzw rotation around zw plane
References abort(), and Global::itoa().
template<unsigned D, typename N> VecMath::Matrix< D, N >::Matrix (unsigned ii, unsigned jj, N Theta) [inline]
creates a rotation about axes ii and jj of angle Theta
Parameters:
ii first (row) index
jj second (column) index
Theta rotation angle
References cos(), VecMath::Matrix< D, N >::M, and sin().
Member Function Documentation
template<unsigned D, typename N = double> N& VecMath::Matrix< D, N >::operator() (unsigned i, unsigned j) [inline]
access operator
Parameters:
i row index
j column index
Returns:
References VecMath::Matrix< D, N >::M.
template<unsigned D, typename N> Matrix< D, N > VecMath::Matrix< D, N >::operator*= (const Matrix< D, N > & B) [inline]
Matrix multiplication
Parameters:
B Matrix to multiply with
Returns:
*this * B
References VecMath::Matrix< D, N >::M.
template<unsigned D, typename N> Matrix< D, N > VecMath::Matrix< D, N >::operator* (const Matrix< D, N > & B) const [inline]
Matrix multiplication
Parameters:
B Matrix to multiply with
Returns:
*this * B
References VecMath::Matrix< D, N >::M.
template<unsigned D, typename N> Vector< D, N > VecMath::Matrix< D, N >::operator* (const Vector< D, N > & V) [inline]
apply the Matrix on a vector
Parameters:
V Vector to multiply with (project)
Returns:
*this * V
References VecMath::Matrix< D, N >::M.
template<unsigned D, typename N> Matrix< D, N > VecMath::Matrix< D, N >::operator- (void) [inline]
Matrix negation
Returns:
- *this
References VecMath::Matrix< D, N >::M.
template<unsigned D, typename N> std::string VecMath::Matrix< D, N >::Print () [inline]
output, mainly for debugging purposes
References std::ends(), VecMath::Matrix< D, N >::M, std::setprecision(), and std::setw().
The documentation for this class was generated from the following file:
HyperspaceExplorer/src/VecMath/Matrix.H