HyperspaceExplorer: vertex_data< D > Class Template Reference
vertex_data< D > Class Template Reference
[N-dimensional Rotopes.]
Base class for all Rotope s. This class may vanish, as Object can take its place.
#include <VertexData.H>
Public Member Functions
virtual void print ()
Output of all vertices.
Protected Member Functions
vertex_data ()
Create an empty array of vertices.
virtual void addSurface (unsigned, unsigned, unsigned, unsigned)
Add a surface to the array of surfaces.
virtual void addSurface (unsigned, unsigned, unsigned)
Add a surface to the array of surfaces.
virtual unsigned & dimension ()
Dimension of the object.
std::vector< VecMath::Vector
< D > > & X ()
The array of vertices.
virtual uintvec2D & surface ()
The array of surfaces.
virtual std::vector
< VecMath::Vector< 4 > > vertices ()
The array of vertices, projected to four dimensions if necessary.
Private Member Functions
bool checkSurfaceExists (const uintvec1D &)
Private Attributes
unsigned _dimension
Dimension of the object.
std::vector< VecMath::Vector< D > > _X
The array of vertices.
uintvec2D _surface
The array of surfaces.
Friends
class Rotope
Detailed Description
template<unsigned D>
class vertex_data< D >
Base class for all Rotope s. This class may vanish, as Object can take its place.
Contains an array of vertices (Vectors) and a function to print them. This is used mainly in the development of Rotope objects.
Parameters:
D Dimension of the vector space we're working in
Author:
Helge Preuss <scout@hyperspace-travel.de>
Constructor & Destructor Documentation
template<unsigned D> vertex_data< D >::vertex_data () [inline, protected]
Create an empty array of vertices.
Only derived classes can create a vertex_data object.
References std::vector< _Tp, _Alloc >::push_back(), and vertex_data< D >::X().
Member Function Documentation
template<unsigned D> void vertex_data< D >::addSurface (unsigned v1, unsigned v2, unsigned v3, unsigned v4) [inline, protected, virtual]
Add a surface to the array of surfaces.
Parameters:
v1 Index (in the vertex array) of the first vertex
v2 Index (in the vertex array) of the second vertex
v3 Index (in the vertex array) of the third vertex
v4 Index (in the vertex array) of the fourth vertex
Implements RotopeBase.
References vertex_data< D >::checkSurfaceExists(), std::vector< _Tp, _Alloc >::push_back(), vertex_data< D >::surface(), and vertex_data< D >::X().
Referenced by extrude_base< D >::extrude(), and taper_base< D >::taper().
template<unsigned D> void vertex_data< D >::addSurface (unsigned v1, unsigned v2, unsigned v3) [inline, protected, virtual]
Add a surface to the array of surfaces.
Overloaded version for three vertices
Parameters:
v1 Index (in the vertex array) of the first vertex
v2 Index (in the vertex array) of the second vertex
v3 Index (in the vertex array) of the third vertex
Implements RotopeBase.
References vertex_data< D >::checkSurfaceExists(), std::vector< _Tp, _Alloc >::push_back(), vertex_data< D >::surface(), and vertex_data< D >::X().
template<unsigned D> std::vector< VecMath::Vector< 4 > > vertex_data< D >::vertices () [inline, protected, virtual]
The array of vertices, projected to four dimensions if necessary.
Todo:
This is hardcoded! Ugh!
Implements RotopeBase.
References vertex_data< D >::X().
template<unsigned D> bool vertex_data< D >::checkSurfaceExists (const uintvec1D & newSurface) [inline, private]
Returns:
Whether argument or permutation of it already in _surface
Test if a new surface is a permutation of a surface already existing.
Parameters:
newSurface The surface to be tested whether it is already stored
Check for equality against every surface in _surface .
Because the corners of a surface are all different numbers, if we found an equal vertex for each corner, the surface is considered equal.
That algorithm breaks down if there are surfaces which are odd permutations of existing surfaces, eg. (0, 1, 3, 2), (0, 1, 2, 3). I don't think such permutations make sense, as the edges of the surface would be self-intersecting.
References std::vector< _Tp, _Alloc >::size(), and vertex_data< D >::surface().
Referenced by vertex_data< D >::addSurface().
The documentation for this class was generated from the following file:
HyperspaceExplorer/src/Functions/VertexData.H