HyperspaceExplorer: LightOpenGL Class Reference
LightOpenGL Class Reference
Implementation of a Light for OpenGL.
#include <Light.H>
Public Member Functions
LightOpenGL (const LightSource &s)
Construct a LightOpenGL from a LightSource definition.
virtual void render () const
Set the light source into the scene.
Detailed Description
Implementation of a Light for OpenGL.
Member Function Documentation
void LightOpenGL::render () const [virtual]
Set the light source into the scene.
C++ Implementation: Light.
Description:
Author: Helge Preuss <scout@hyperspace-travel.de>, (C) 2008
Copyright: See COPYING file that comes with this distribution Includes all OpenGL headers in a system-independent way
Todo:
GL_LIGHT0 is hardcoded, make this variable. To quote from the OpenGL API docs: "It is always the case that GL_LIGHTi = GL_LIGHT0 + i."
Implements Light.
References Light::getAmbient(), Light::getDiffuse(), Light::getPosition(), and Light::getSpecular().
Referenced by C4DView::InitLight(), and C4DView::setLighting().
The documentation for this class was generated from the following files:
HyperspaceExplorer/src/Light.H
HyperspaceExplorer/src/Light.C