HyperspaceExplorer: Helper classes for User Interface classes
Helper classes for User Interface classes
[User Interface]
Classes
class RealFunctionFactory
Abstract base class for a factory creating Function's.
class SurfaceFactory
Abstract base class for a factory creating Surface's.
class C4DView::TemplatedRealFunctionFactory< function >
Class template implementation for a factory creating Function's.
class C4DView::TemplatedSurfaceFactory< function >
Class template implementation for a factory creating Surface's.
class C4DView::CustomFunctionSlot< function >
Class template to outsource redundant code for customized functions.
class FunctionSlotHelper
Single-stop slot for menu QActions generating Function objects.
class SurfaceSlotHelper
Single-stop slot for menu QActions generating Surface objects.
Functions
static void C4DView::CustomFunctionSlot::createCustomFunction (C4DView *view)
C++ Template Implementation: CustomFunctionSlot.
virtual RealFunction * C4DView::TemplatedRealFunctionFactory::doCreateFunction (C4DView *)
Implementation of TemplateMethod createFunction().
Function Documentation
template<class function> void C4DView::CustomFunctionSlot< function >::createCustomFunction (C4DView * view) [inline, static, inherited]
C++ Template Implementation: CustomFunctionSlot.
Description: Implementation for createCustomFunction() and createCustomSurface()
Author:
: Helge Preuss <scout@hyperspace-travel.de>, (C) 2008
Copyright: See COPYING file that comes with this distribution Factory method to create a new customized Function of type R^3->R This function template is called by each slot with the correct function type as template parameter.
Sets F to the newly created Function, checks the corresponding menu item, updates the ValuesDialog and redraws. Does some error handling in case the Function could not be loaded.
References C4DView::AssignValues(), UI::Dialogs::ValuesDialogImpl::dt(), UI::Dialogs::ValuesDialogImpl::du(), UI::Dialogs::ValuesDialogImpl::dv(), UI::ViewImpl::F(), C4DView::Redraw(), UI::ViewImpl::setF(), UI::Dialogs::ValuesDialogImpl::tmax(), UI::Dialogs::ValuesDialogImpl::tmin(), UI::Dialogs::ValuesDialogImpl::umax(), UI::Dialogs::ValuesDialogImpl::umin(), C4DView::UpdateStatus(), C4DView::Values(), UI::Dialogs::ValuesDialogImpl::vmax(), and UI::Dialogs::ValuesDialogImpl::vmin().
template<class function> RealFunction * C4DView::TemplatedRealFunctionFactory< function >::doCreateFunction (C4DView * view) [inline, private, virtual, inherited]
Implementation of TemplateMethod createFunction().
C++ Template Implementation: TemplatedFunctionFactory, TemplatedSurfaceFactory.
Description: Implementation for creatFunction() resp. createSurface()
Author:
: Helge Preuss <scout@hyperspace-travel.de>, (C) 2008
Copyright: See COPYING file that comes with this distribution Factory method to create a Function object The type of the created Function is supplied as template parameter to the TemplatedFunctionFactory object owning this method.
Implements RealFunctionFactory.
References UI::Dialogs::ValuesDialogImpl::dt(), UI::Dialogs::ValuesDialogImpl::du(), UI::Dialogs::ValuesDialogImpl::dv(), UI::Dialogs::ValuesDialogImpl::tmax(), UI::Dialogs::ValuesDialogImpl::tmin(), UI::Dialogs::ValuesDialogImpl::umax(), UI::Dialogs::ValuesDialogImpl::umin(), C4DView::Values(), UI::Dialogs::ValuesDialogImpl::vmax(), and UI::Dialogs::ValuesDialogImpl::vmin().