HyperspaceExplorer: Vector and Matrix algebra
Vector and Matrix algebra
Classes
class VecMath::Matrix< D, N >
struct VecMath::NumAxes< D >
Determine number of rotation axes in D-dimensional space.
class VecMath::RotationAxes< D >
How to generate a Rotation matrix from a Rotation component.
class VecMath::Rotation< D, N >
Rotation in D-dimensional space defined by angles about the main axes.
class VecMath::Vector< D, N >
Vector<D, N>: a D-dimensional vector of numbers of type N.
Functions
template<unsigned D, typename N>
std::ostream & VecMath::operator<< (std::ostream &o, const Rotation< D, N > &v)
Rotation output operator.
template<unsigned D, typename N>
std::istringstream & VecMath::operator>> (std::istringstream &in, Rotation< D, N > &v)
Rotation input operator.
template<unsigned D, typename N>
std::ostream & VecMath::operator<< (std::ostream &o, const Vector< D, N > &v)
Vector output operator.
template<unsigned D, typename N>
std::istringstream & VecMath::operator>> (std::istringstream &in, Vector< D, N > &v)
Vector input operator.
template<unsigned D, typename N>
Vector< D > VecMath::cross (const Vector< D > &, const Vector< D > &)
cross product of two Vectors
template<unsigned D, typename N>
Vector< D > VecMath::cross (const Vector< D > &, const Vector< D > &, const Vector< D > &)
specialization for cross product of three 4-Vectors
template<typename N>
Vector< 3, N > VecMath::vcross (Vector< 3, N > a, Vector< 3, N > b)
specialization for cross product of two 3-Vectors
template<typename N>
Vector< 4, N > VecMath::vcross (Vector< 4, N > a, Vector< 4, N > b, Vector< 4, N > c)
specialization for cross product of three 4-Vectors
template<unsigned D, typename N>
Vector< D, N > VecMath::vnormalize (const Vector< D, N > &x)
normalizes a 3-Vector out-of-place
Function Documentation
template<unsigned D, typename N> Vector<D> VecMath::cross (const Vector< D > & , const Vector< D > & , const Vector< D > &) [inline]
specialization for cross product of three 4-Vectors
fails for dimensions other than 4 due to lack of template specialization
Parameters:
a first operand of cross product
b second operand of cross product
c third operand of cross product
Returns:
a x b x c
template<unsigned D, typename N> Vector<D> VecMath::cross (const Vector< D > & , const Vector< D > &) [inline]
cross product of two Vectors
fails for dimensions other than 3 due to lack of template specialization
Parameters:
a first operand of cross product
b second operand of cross product
Returns:
a x b
template<unsigned D, typename N> std::ostream & VecMath::operator<< (std::ostream & o, const Vector< D, N > & v) [inline]
Vector output operator.
Parameters:
o ostream to push into
v Vector to print
Returns:
a new ostream to push Vectors and stuff into
template<unsigned D, typename N> std::ostream& VecMath::operator<< (std::ostream & o, const Rotation< D, N > & v) [inline]
Rotation output operator.
Parameters:
o ostream to push into
v Rotation to print
Returns:
a new ostream to push Rotations and stuff into
template<unsigned D, typename N> std::istringstream& VecMath::operator>> (std::istringstream & in, Vector< D, N > & v) [inline]
Vector input operator.
Parameters:
o istream to read from
v Vector to read
Returns:
a new istream to read stuff from
References VecMath::Vector< D, N >::dimension().
template<unsigned D, typename N> std::istringstream& VecMath::operator>> (std::istringstream & in, Rotation< D, N > & v) [inline]
Rotation input operator.
Parameters:
o istream to read from
v Rotation to read
Returns:
a new istream to read stuff from
References VecMath::Rotation< D, N >::r().
template<typename N> Vector<4, N> VecMath::vcross (Vector< 4, N > a, Vector< 4, N > b, Vector< 4, N > c) [inline]
specialization for cross product of three 4-Vectors
Parameters:
a first operand of cross product
b second operand of cross product
c third operand of cross product
Returns:
a x b x c
template<typename N> Vector<3, N> VecMath::vcross (Vector< 3, N > a, Vector< 3, N > b) [inline]
specialization for cross product of two 3-Vectors
Parameters:
a first operand of cross product
b second operand of cross product
Returns:
a x b
Referenced by RealFunction::normal().
template<unsigned D, typename N> Vector<D, N> VecMath::vnormalize (const Vector< D, N > & x) [inline]
normalizes a 3-Vector out-of-place
Parameters:
x Vector to be normalized
Returns:
its normalized value
References norm(), VecMath::Vector< D, N >::sqnorm(), and sqrt().
Referenced by RealFunction::normal(), and Global::vnormalize().