HyperspaceExplorer: Script Namespace Reference
Script Namespace Reference
Interpreting and executing scripts.
Classes
class Parser
Parser reads a file and executes the commands in it in a C4DView.
class BadStatementException
exception thrown when an unknown statement is encountered in a script
class Statement
Base class for all possible statements in a script.
class BoolStatement
Statement with a single boolean parameter.
class SizeStmt
"size <width> <height>"
class ObjectStmt
"object <object_name>"
class ParmStmt
"parameter <double|int|unsigned|string> <parameter>"
class XformStmt
"transform <rotation>"
class RotStmt
"rotation <rotation>"
class DeltaStmt
"transform_step <rotation>"
class RotDeltaStmt
"rotation_step <rotation>"
class FramesStmt
"frames <num_frames>"
class LoopStmt
"loop <num_loops>"
class ColorStmt
"color <bool>"
class ShadingStmt
"shading <bool>"
class LightStmt
"lighting <bool>"
class TransStmt
"transparence <bool>"
class WireStmt
"wireframe <bool>"
class SolidStmt
"solid <bool>"
class FogStmt
"depthcue3d <bool>"
class Fog4DStmt
"depthcue4d <bool>"
class CoordsStmt
"coordinates <bool>"
class AnimateStmt
"animate"
class SleepStmt
"sleep <milliseconds>"
class ImgDirStmt
"image_dir <directory>"
class ImgPrefixStmt
"image_prefix <filename_prefix>"
class StatementFactory
Factory object to create Statement objects from a Parser and a given line.
Functions
string strip_ws (const string &s)
Trim whitespace from the beginning and the end of a string.
string strip_comments (const string &s)
Remove everything beginning with a "#" character to the end of the line.
bool starts_with (const string &haystack, const string &needle)
string leading (const string &haystack, const string &needle)
string trailing (const string &haystack, const string &needle)
Detailed Description
Interpreting and executing scripts.
Function Documentation
std::string Script::leading (const string & haystack, const string & needle)
Returns:
the part of haystack before the start of needle
References strip_ws().
bool Script::starts_with (const string & haystack, const string & needle)
Does haystack start with needle ?
References strip_ws().
std::string Script::strip_ws (const string & s)
Trim whitespace from the beginning and the end of a string.
Returns:
The trimmed string
Referenced by leading(), starts_with(), strip_comments(), and trailing().
std::string Script::trailing (const string & haystack, const string & needle)
Returns:
the part of haystack after the end of needle
References strip_ws().