stages:
  - build
  - test

variables:
  QT_IMAGE: theshadowx/qt5:latest
  DEBIAN_FRONTEND: noninteractive

Build:
  stage: build
  image: ${QT_IMAGE}
  when: always
  script:
    - qmake
    - make -j4

BuildDoc:
  stage: build
  image: ${QT_IMAGE}
  when: always
  before_script:
    - apt install -y doxygen graphviz texlive-full
  script:
    doxygen

