stages:
  - build
  - test
  - build-main
  - deploy

variables:
  QT_IMAGE: theshadowx/qt5:latest
  DEBIAN_FRONTEND: noninteractive

include:
  - template: Code-Quality.gitlab-ci.yml

Build:
  stage: build
  image: ${QT_IMAGE}
  when: always
  before_script:
    - apt update
    - apt upgrade
    - apt install -y g++-8
    - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  script:
    - qmake
    - make -j4 sub-src
  artifacts:
    paths:
      - lib/libHyperspaceExplorer.a

BuildDoc:
  stage: build
  image: ${QT_IMAGE}
  when: always
  before_script:
    - apt install -y doxygen graphviz texlive ghostscript
  script:
    doxygen
  artifacts:
    paths:
      - doc/html/**/*

Test:
  stage: test
  image: ${QT_IMAGE}
  when: always
  dependencies:
    - Build
  before_script:
    - apt update
    - apt upgrade
    - apt install -y g++-8
    - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  script:
    - qmake
    - make -j4 sub-tests
  artifacts:
    paths:
      - tests/HyperspaceExplorer-tests

code_quality:
  artifacts:
    paths:
      - gl-code-quality-report.json

BuildMain:
  stage: build-main
  image: ${QT_IMAGE}
  when: always
  dependencies:
    - Build
    - Test
  before_script:
    - apt update
    - apt upgrade
    - apt install -y g++-8
    - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  script:
    - qmake
    - make sub-main
  artifacts:
    paths:
      - HyperspaceExplorer

DeployDoc:
  stage: deploy
  only:
    - master
  dependencies:
    - BuildDoc
  script:
    - echo "Deploying documentation to $CI_ENVIRONMENT_NAME ($CI_ENVIRONMENT_SLUG)"
  environment:
    name: doc
    url: https://gitlab.com/lilacashes/HyperspaceExplorer/doc
