//
// C++ Implementation: PluginCreator
//
// Description: 
//
//
// Author: Helge Preuss <scout@hyperspace-travel.de>, (C) 2008
//
// Copyright: See COPYING file that comes with this distribution
//
//

#include <QString>
#include <QFile>
#include <QMessageBox>

#include "PluginCreator.H"

/*******************************************************************************
 *  compile the C++ source code written by writeSource (), displaying errors and
 *  warnings, if they come up.
 *  needs "Vector.H" in the current directory or in the C++ include path.
 *  might tweak the compilation flags a little, or make them variable
 *  @return 	success
 */
bool PluginCreator::compile (QString name) {
    QString compileCommand = "g++ -I.. -I../.. -g -c -Wall -fPIC \""
            +name
            +".C\" > /tmp/HyperspaceExplorer.compile.errors 2>&1";
    bool Success = !system (compileCommand);
    
    if (!Success) {
        QFile Errs ("/tmp/HyperspaceExplorer.compile.errors");
        Errs.open (QIODevice::ReadOnly);
        QString ErrString (Errs.readAll ());
        QMessageBox::warning (NULL, "Compilation Errors", compileCommand+":\n"+ErrString);
    }

    return Success;
}


/*******************************************************************************
 *  link the object file generated by compile () into a dynamic library.
 *  needs "Vector.o" in the current directory.
 *  @return 	success
 */
bool PluginCreator::link (QString name) {
    QString linkCommand = "g++ -shared -Wl,-export-dynamic -Wl,-soname,\""
            +name+".so\" -o \""
            +name+".so\" \""
            +name+".o\""
            +"> /tmp/HyperspaceExplorer.link.errors 2>&1";
    bool Success = !system (linkCommand);
    
    if (!Success) {
        QFile Errs ("/tmp/HyperspaceExplorer.link.errors");
        Errs.open (QIODevice::ReadOnly);
        QString ErrString (Errs.readAll ());
        QMessageBox::warning (NULL, "Link Errors", linkCommand+":\n"+ErrString);
    }

    return Success;
}


