/*
Hyperspace Explorer - visualizing higher-dimensional geometry
Copyright (C) 2010  Lene Preuss <lene.preuss@gmail.com>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

*/

/********************************************************************************
** Form originally  generated from reading ui file 'ValuesDialog.ui'
**
** Created: Fri Apr 25 15:22:18 2008
**      by: Qt User Interface Compiler version 4.3.4
**
********************************************************************************/

#ifndef UI_VALUESDIALOG_H
#define UI_VALUESDIALOG_H

#include <Qt3Support/Q3MimeSourceFactory>
#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QComboBox>
#include <QtGui/QDialog>
#include <QtGui/QGridLayout>
#include <QtGui/QHBoxLayout>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>
#include <QtGui/QSlider>
#include <QtGui/QVBoxLayout>

#include "UI/ParameterInput.h"

namespace UI {

    /// Dialogs for entering values
    namespace Dialogs {
        /// Base class for ValuesDialogImpl, originally created by uic
        /** The autogenerated nature is responsible for the ugly code.
         *
         * \em Don't try to generate this file from a UI file made by Qt Designer,
         *  that would totally mess up the declarations!
         *   \ingroup UIGroup                                                 */
        class ValuesDialog {
            protected:
                /// maximum number of grid dimensions to control
                static const unsigned maxNumDimensions = 3;
                /// maximum number of function parameters to display
                static const unsigned maxNumParameters = 4;
                /// group this many parameter input fields on a line
                static const unsigned parametersPerLine = 2;

                /// create the widgets in the dialog and lay them out
                void setupUi(QDialog *ValuesDialog) {
                    QFont font;

                    //  global initializations, layout and header
                    {
                        if (ValuesDialog->objectName().isEmpty())
                            ValuesDialog->setObjectName(
                                    QString::fromUtf8("ValuesDialog"));
                        ValuesDialog->resize(343, 410);
                        QSizePolicy sizePolicy(QSizePolicy::Minimum,
                                            QSizePolicy::Minimum);
                        sizePolicy.setHorizontalStretch(0);
                        sizePolicy.setVerticalStretch(0);
                        sizePolicy.setHeightForWidth(
                                ValuesDialog->sizePolicy().hasHeightForWidth());
                        ValuesDialog->setSizePolicy(sizePolicy);
                        ValuesDialog->setSizeGripEnabled(false);
                        gridLayout = new QGridLayout(ValuesDialog);
                        gridLayout->setSpacing(6);
                        gridLayout->setMargin(11);
                        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
                        AllBoundsLayout = new QVBoxLayout();
                        AllBoundsLayout->setSpacing(6);
                        AllBoundsLayout->setObjectName(
                                QString::fromUtf8("AllBoundsLayout"));
                        gridLabel = new QLabel(ValuesDialog);
                        gridLabel->setObjectName(QString::fromUtf8("gridLabel"));
                        font.setBold(true);
                        font.setWeight(75);
                        gridLabel->setFont(font);
                        gridLabel->setAlignment(Qt::AlignCenter);

                        AllBoundsLayout->addWidget(gridLabel);
                    }
                    //  defining the grid resolution and bounds
                    for (unsigned i = 0; i < maxNumDimensions; i++) {
                        SliderLayout[i] = new QHBoxLayout();
                        SliderLayout[i]->setSpacing(6);
                        SliderLayout[i]->setObjectName(
                                QString::fromUtf8("SliderLayout[i]"));
                        SliderLayout[i]->setContentsMargins(0, 0, 0, 0);
                        Label[i] = new QLabel(ValuesDialog);
                        Label[i]->setObjectName(QString::fromUtf8("Label[i]"));

                        SliderLayout[i]->addWidget(Label[i]);

                        Slider[i] = new QSlider(ValuesDialog);
                        Slider[i]->setObjectName(QString::fromUtf8("Slider[i]"));
                        Slider[i]->setMinimum(1);
                        Slider[i]->setMaximum(50);
                        Slider[i]->setPageStep(5);
                        Slider[i]->setValue(5);
                        Slider[i]->setOrientation(Qt::Horizontal);
                        Slider[i]->setTickInterval(5);

                        SliderLayout[i]->addWidget(Slider[i]);

                        Steps[i] = new QLabel(ValuesDialog);
                        Steps[i]->setObjectName(QString::fromUtf8("Steps[i]"));

                        SliderLayout[i]->addWidget(Steps[i]);

                        AllBoundsLayout->addLayout(SliderLayout[i]);

                        BoundsLayout[i] = new QHBoxLayout();
                        BoundsLayout[i]->setSpacing(6);
                        BoundsLayout[i]->setObjectName(
                                QString::fromUtf8("BoundsLayout[i]"));
                        BoundsLayout[i]->setContentsMargins(0, 0, 0, 0);
                        MinLayout[i] = new QHBoxLayout();
                        MinLayout[i]->setSpacing(6);
                        MinLayout[i]->setObjectName(QString::fromUtf8("MinLayout[i]"));
                        MinLayout[i]->setContentsMargins(0, 0, 0, 0);
                        MinLabel[i] = new QLabel(ValuesDialog);
                        MinLabel[i]->setObjectName(QString::fromUtf8("MinLabel[i]"));

                        MinLayout[i]->addWidget(MinLabel[i]);

                        Min[i] = new QLineEdit(ValuesDialog);
                        Min[i]->setObjectName(QString::fromUtf8("Min[i]"));

                        MinLayout[i]->addWidget(Min[i]);

                        BoundsLayout[i]->addLayout(MinLayout[i]);

                        MaxLayout[i] = new QHBoxLayout();
                        MaxLayout[i]->setSpacing(6);
                        MaxLayout[i]->setObjectName(QString::fromUtf8("MaxLayout[i]"));
                        MaxLayout[i]->setContentsMargins(0, 0, 0, 0);
                        MaxLabel[i] = new QLabel(ValuesDialog);
                        MaxLabel[i]->setObjectName(QString::fromUtf8("MaxLabel[i]"));

                        MaxLayout[i]->addWidget(MaxLabel[i]);

                        Max[i] = new QLineEdit(ValuesDialog);
                        Max[i]->setObjectName(QString::fromUtf8("Max[i]"));

                        MaxLayout[i]->addWidget(Max[i]);

                        BoundsLayout[i]->addLayout(MaxLayout[i]);

                        AllBoundsLayout->addLayout(BoundsLayout[i]);
                    }

                    gridLayout->addLayout(AllBoundsLayout, 0, 0, 1, 1);

                    //  function parameters - heading and layout
                    {
                        functionLabel = new QLabel(ValuesDialog);
                        functionLabel->setObjectName(QString::fromUtf8("functionLabel"));
                        functionLabel->setFont(font);
                        functionLabel->setAlignment(Qt::AlignCenter);

                        gridLayout->addWidget(functionLabel, 2, 0, 1, 1);

                        AllParametersLayout = new QVBoxLayout();
                        AllParametersLayout->setSpacing(6);
                        AllParametersLayout->setObjectName(
                                QString::fromUtf8("AllParametersLayout"));
                        AllParametersLayout->setContentsMargins(0, 0, 0, 0);
                    }

                    //  function parameters - input fields
                    for (unsigned j = 0; j < maxNumParameters/parametersPerLine; j++) {
                        ParameterLineLayout[j] = new QHBoxLayout();
                        ParameterLineLayout[j]->setSpacing(6);
                        ParameterLineLayout[j]->setObjectName(
                                QString::fromUtf8("ParameterLineLayout[j]"));
                        ParameterLineLayout[j]->setContentsMargins(0, 0, 0, 0);
                        for (unsigned i = parametersPerLine*j;
                            i < parametersPerLine*j+parametersPerLine; i++) {
                            ParameterLayout[i] = new QHBoxLayout();
                            ParameterLayout[i]->setSpacing(6);
                            ParameterLayout[i]->setObjectName(
                                    QString::fromUtf8("ParameterLayout[i]"));
                            ParameterLayout[i]->setContentsMargins(0, 0, 0, 0);
                            ParameterLabel[i] = new QLabel(ValuesDialog);
                            ParameterLabel[i]->setObjectName(
                                    QString::fromUtf8("ParameterLabel[i]"));

                            ParameterLayout[i]->addWidget(ParameterLabel[i]);

                            Parameter[i] = new ParameterLineEdit(ValuesDialog);
                            dynamic_cast<QWidget *>(Parameter[i])->setObjectName(
                                    QString::fromUtf8("Parameter[i]"));

                            ParameterLayout[i]->addWidget(
                                    dynamic_cast<QWidget *>(Parameter[i]));

                            ParameterLineLayout[j]->addLayout(ParameterLayout[i]);
                        }


                        AllParametersLayout->addLayout(ParameterLineLayout[j]);
                    }

                    gridLayout->addLayout(AllParametersLayout, 4, 0, 1, 1);

                    //  "Apply" button
                    {
                        ButtonLayout = new QHBoxLayout();
                        ButtonLayout->setSpacing(6);
                        ButtonLayout->setObjectName(QString::fromUtf8("ButtonLayout"));
                        ButtonLayout->setContentsMargins(0, 0, 0, 0);
                        buttonApply = new QPushButton(ValuesDialog);
                        buttonApply->setObjectName(QString::fromUtf8("buttonApply"));
                        buttonApply->setAutoDefault(true);

                        ButtonLayout->addWidget(buttonApply);
                        gridLayout->addLayout(ButtonLayout, 5, 0, 1, 1);
                    }

                    //  tab order
                    for (unsigned i = 0; i < maxNumDimensions; ++i) {
                        QWidget::setTabOrder(Slider[i], Min[i]);
                        QWidget::setTabOrder(Min[i], Max[i]);
                        if (i < maxNumDimensions-1)
                            QWidget::setTabOrder(Max[i], Slider[i+1]);
                    }
                    QWidget::setTabOrder(Max[maxNumDimensions-1],
                                         dynamic_cast<QWidget *>(Parameter[0]));
                    for (unsigned i = 0; i < maxNumParameters-1; ++i) {
                        QWidget::setTabOrder(dynamic_cast<QWidget *>(Parameter[i]),
                                             dynamic_cast<QWidget *>(Parameter[i+1]));
                    }
                    QWidget::setTabOrder(
                            dynamic_cast<QWidget *>(Parameter[maxNumParameters-1]),
                            buttonApply);

                    retranslateUi(ValuesDialog);

                    //  signal/slot connections
                    for (unsigned i = 0; i < maxNumDimensions; ++i) {
                        QObject::connect(Slider[i], SIGNAL(valueChanged(int)),
                                        Steps[i], SLOT(setNum(int)));
                        for (unsigned j = i+1; j < maxNumDimensions; ++j) {
                            QObject::connect(Slider[i], SIGNAL(valueChanged(int)),
                                            Slider[j], SLOT(setValue(int)));
                        }
                    }
                    QObject::connect(buttonApply, SIGNAL(clicked()),
                                    ValuesDialog, SLOT(accept()));

                    QMetaObject::connectSlotsByName(ValuesDialog);
                } // setupUi

                /// add the text(s) associated with each widget
                void retranslateUi(QDialog *ValuesDialog) {
                    ValuesDialog->setWindowTitle(
                            QApplication::translate("ValuesDialog",
                                "Enter Values for the Function", 0,
                                QApplication::UnicodeUTF8));
                    ValuesDialog->setWhatsThis(QApplication::translate("ValuesDialog",
                        "In this dialog window the user can enter up to four parameters"
                        "to the displayed four-dimensional function or object.\n"
                        "She can also change the resolution of the grid.", 0,
                        QApplication::UnicodeUTF8));
                    gridLabel->setText(QApplication::translate("ValuesDialog",
                        "Grid size and bounds", 0, QApplication::UnicodeUTF8));
                    Label[0]->setText(QApplication::translate("ValuesDialog",
                        "Steps in t", 0, QApplication::UnicodeUTF8));
                    MinLabel[0]->setText(QApplication::translate("ValuesDialog",
                        "tmin", 0, QApplication::UnicodeUTF8));
                    MaxLabel[0]->setText(QApplication::translate("ValuesDialog",
                        "tmax", 0, QApplication::UnicodeUTF8));
                    Label[1]->setText(QApplication::translate("ValuesDialog",
                        "Steps in u", 0, QApplication::UnicodeUTF8));
                    MinLabel[1]->setText(QApplication::translate("ValuesDialog",
                        "umin", 0, QApplication::UnicodeUTF8));
                    MaxLabel[1]->setText(QApplication::translate("ValuesDialog",
                        "umax", 0, QApplication::UnicodeUTF8));
                    Label[2]->setText(QApplication::translate("ValuesDialog",
                        "Steps in v", 0, QApplication::UnicodeUTF8));
                    MinLabel[2]->setText(QApplication::translate("ValuesDialog",
                        "vmin", 0, QApplication::UnicodeUTF8));
                    MaxLabel[2]->setText(QApplication::translate("ValuesDialog",
                        "vmax", 0, QApplication::UnicodeUTF8));
                    for (unsigned i = 0; i < maxNumDimensions; ++i) {
                        Steps[i]->setText(QApplication::translate("ValuesDialog",
                            "1", 0, QApplication::UnicodeUTF8));
                        Min[i]->setToolTip(QApplication::translate("ValuesDialog",
                            "enter '-pi' if you mean -3.1415...", 0,
                            QApplication::UnicodeUTF8));
                        Min[i]->setText(QApplication::translate("ValuesDialog",
                            "-1", 0, QApplication::UnicodeUTF8));
                        Max[i]->setToolTip(QApplication::translate("ValuesDialog",
                            "or 'pi' if you want 3.1415...", 0,
                            QApplication::UnicodeUTF8));
                        Max[i]->setText(QApplication::translate("ValuesDialog",
                            "1", 0, QApplication::UnicodeUTF8));
                    }
                    functionLabel->setText(QApplication::translate("ValuesDialog",
                        "Function Parameters", 0, QApplication::UnicodeUTF8));
                    for (unsigned i = 0; i < maxNumParameters; ++i) {
                        ParameterLabel[i]->setText(QApplication::translate(
                            "ValuesDialog", "Parameter", 0,
                             QApplication::UnicodeUTF8));
                        //  set 1 as default value (casted to QString)
                        Parameter[i]->setValue(QApplication::translate(
                            "ValuesDialog", "1", 0, QApplication::UnicodeUTF8));
                    }
                    buttonApply->setToolTip(QApplication::translate("ValuesDialog",
                        "Accept changes and redraw", 0, QApplication::UnicodeUTF8));
                    buttonApply->setText(QApplication::translate("ValuesDialog",
                        "&Apply", 0, QApplication::UnicodeUTF8));
                    Q_UNUSED(ValuesDialog);
                } // retranslateUi

            protected:
                //  these members should be private and referred to only by accessors,
                //  but this is the way uic created the class and the derived class
                //  depends too much on them. so i didn't bother.
                QGridLayout *gridLayout;            ///< global layout
                QVBoxLayout *AllBoundsLayout;       ///< layout for the bounds section
                QVBoxLayout *AllParametersLayout;   ///< layout for the parameters section
                QHBoxLayout *ButtonLayout;          ///< layout for "Apply" button

                QLabel *gridLabel;                  ///< "Grid size and bounds" header

                /// layouts for the bounds sliders and labels
                QHBoxLayout *SliderLayout[maxNumDimensions];
                /// layouts for each combined bounds selector
                QHBoxLayout *BoundsLayout[maxNumDimensions];
                /// layouts for each lower bound selector
                QHBoxLayout *MinLayout[maxNumDimensions];
                /// layouts for each upper bound selector
                QHBoxLayout *MaxLayout[maxNumDimensions];

                QLabel *Label[maxNumDimensions];    ///< "Steps in [t|u|v]"
                QSlider *Slider[maxNumDimensions];  ///< select number of grid points
                QLabel *Steps[maxNumDimensions];    ///< display number of grid points
                QLabel *MinLabel[maxNumDimensions]; ///< labels for lower bound inputs
                QLineEdit *Min[maxNumDimensions];   ///< input fields for lower bounds
                QLabel *MaxLabel[maxNumDimensions]; ///< labels for upper bound inputs
                QLineEdit *Max[maxNumDimensions];   ///< input fields for upper bounds

                /// header for parameter input fields
                QLabel *functionLabel;

                /// QHBoxLayout for all parameter input fields
                QHBoxLayout *ParameterLayout[maxNumParameters];
                /// QHBoxLayout for every line of parameter input fields
                QHBoxLayout *ParameterLineLayout[maxNumParameters/parametersPerLine];

                /// parameter input labels
                QLabel *ParameterLabel[maxNumParameters];
                /// parameter input fields
                ParameterInput *Parameter[maxNumParameters];

                QPushButton *buttonApply;                   ///< "Apply" button

        };
    }
}

#endif // UI_VALUESDIALOG_H
