
//      project:      hyperspace explorer
//      module:
//      contains:
//      compile with: make all
//	author:	      helge preuss (scout@hyperspace-travel.de)
//	license:      GPL (see License.txt)


//      project:      GL/Qt interface
//      module:       XQGLWidget.H
//      compile with: make all
//      contains:     class definition for the extended OpenGL widget
#ifndef XQGLW_H
#define XQGLW_H
/*

#include <QGLWidget>

#include "Vector.H"

//class Q3PopupMenu;
//class QMouseEvent;

/** class XQGLWidget:
 *  implements a QGLWidget
 *  \ingroup UIGroup                                                          */
/*
class XQGLWidget: public QGLWidget {

    Q_OBJECT

    public:
        XQGLWidget (QWidget * = 0);
};
*/
#endif
