
srcdir = .
top_srcdir = ..

INSTALL = /bin/install -c
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
CC = gcc
CFLAGS = -g
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"LSystem\" -DPACKAGE_TARNAME=\"hyperspace-expl\" -DPACKAGE_VERSION=\"0.2.0\" -DPACKAGE_STRING=\"LSystem\ 0.2.0\" -DPACKAGE_BUGREPORT=\"helge.preuss@gmx.net\" -DPACKAGE=\"hyperspace-expl\" -DVERSION=\"0.2.0\" -DHAVE_GL=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_POW=1 -DHAVE_SQRT=1 -DHAVE_USLEEP=1 
INCLUDES =  
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS =  -lGL -lGLU
MOC = moc
OBJEXT = o
PACKAGE = hyperspace-expl
PACKAGE_BUGREPORT = helge.preuss@gmx.net
PACKAGE_NAME = LSystem
PACKAGE_STRING = LSystem 0.2.0
PACKAGE_TARNAME = hyperspace-expl
PACKAGE_VERSION = 0.2.0
PATH_SEPARATOR = :
QASSISTANTCLIENT_LDADD = -lqassistantclient
QT_CXXFLAGS = -I/usr/qt/3/include
QT_GUILINK = 
QT_LDADD = -L/usr/qt/3/lib -lqt
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
UIC = uic
VERSION = 0.2.0
bindir = ${exec_prefix}/bin
bin_PROGRAMS = LSystem
DIST_SUBDIRS = 

LSystem_UISRC = 

LSystem_SRC = \
	LSystem.C LSys_aux.C numclass.C 


LSystem_IMPL_HDRS = 


LSystem_HDRS = LSystem.H numclass.H Matrix.H					\
	

LSystem_IMPL = 


LSystem_UI = 


LSystem_MOC = 


BUILT_SOURCES = $(LSystem_MOC) $(LSystem_UI)

LSystem_SOURCES = LSystem_SRC					 \
	$(LSystem_IMPL) 					 \
	$(LSystem_UISRC) 					 \
	$(LSystem_HDRS) 					 \
	$(LSystem_IMPL_HDRS) 				 \
	$(BUILT_SOURCES)


CLEANFILES = $(LSystem_MOC) $(LSystem_UI)
EXTRA_DIST = Documentation

LSystem_LDADD = $(QT_GUILINK) $(QT_LDADD) $(EXTRA_LDADD)

AM_CXXFLAGS := $(CXXFLAGS) $(EXTRA_CXXFLAGS) -I../include $(QT_CXXFLAGS) \
		-ansi -Wall -ffast-math

subdir = src
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
mkinstalldirs = $(SHELL) $(top_srcdir)/config/mkinstalldirs
CONFIG_CLEAN_FILES =
bin_PROGRAMS = LSystem$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS)

am__objects_1 = 
am__objects_2 =
am__objects_3 = 
am__objects_4 = 
am__objects_5 = $(am__objects_3) $(am__objects_4)
am_LSystem_OBJECTS = LSystem.$(OBJEXT) LSys_aux.$(OBJEXT) \
	numclass.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_2) $(am__objects_2) \
	$(am__objects_5)
LSystem_OBJECTS = $(am_LSystem_OBJECTS)
LSystem_DEPENDENCIES =
LSystem_LDFLAGS =

DEFAULT_INCLUDES =  -I. -I$(srcdir)
depcomp = $(SHELL) $(top_srcdir)/config/depcomp
am__depfiles_maybe = depfiles
DEPDIR = .
DEP_FILES = ./$(DEPDIR)/4DMenu.Po ./$(DEPDIR)/4DView.Po \
	./$(DEPDIR)/4DView.moc.Po \
	./$(DEPDIR)/ComplexDialog.Po \
	./$(DEPDIR)/ComplexDialog.moc.Po \
	./$(DEPDIR)/ComplexDialogImpl.Po \
	./$(DEPDIR)/ComplexDialogImpl.moc.Po \
	./$(DEPDIR)/ComplexFunction.Po \
	./$(DEPDIR)/CustomFunction.Po \
	./$(DEPDIR)/Function.Po \
	./$(DEPDIR)/FunctionDialog.Po \
	./$(DEPDIR)/FunctionDialog.moc.Po \
	./$(DEPDIR)/FunctionDialogImpl.Po \
	./$(DEPDIR)/FunctionDialogImpl.moc.Po \
	./$(DEPDIR)/Globals.Po ./$(DEPDIR)/Help.Po \
	./$(DEPDIR)/Help.moc.Po ./$(DEPDIR)/Main.Po \
	./$(DEPDIR)/Object.Po ./$(DEPDIR)/PolarDialog.Po \
	./$(DEPDIR)/PolarDialog.moc.Po \
	./$(DEPDIR)/PolarDialogImpl.Po \
	./$(DEPDIR)/PolarDialogImpl.moc.Po \
	./$(DEPDIR)/PopupStuff.Po ./$(DEPDIR)/Surface.Po \
	./$(DEPDIR)/SurfaceDialog.Po \
	./$(DEPDIR)/SurfaceDialog.moc.Po \
	./$(DEPDIR)/SurfaceDialogImpl.Po \
	./$(DEPDIR)/SurfaceDialogImpl.moc.Po \
	./$(DEPDIR)/ValuesDialog.Po \
	./$(DEPDIR)/ValuesDialog.moc.Po \
	./$(DEPDIR)/ValuesDialogImpl.Po \
	./$(DEPDIR)/ValuesDialogImpl.moc.Po \
	./$(DEPDIR)/XQGLWidget.Po \
	./$(DEPDIR)/XQGLWidget.moc.Po \
	./$(DEPDIR)/numclass.Po
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
DIST_SOURCES = $(LSystem_SOURCES)
DIST_COMMON = $(srcdir)/Makefile.in Makefile.am
SOURCES = $(LSystem_SOURCES)

all: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) all-am

all-am: Makefile $(PROGRAMS)

.C.o:
	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" \
	  -c -o $@ `test -f '$<' || echo '$(srcdir)/'`$<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; \
	else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; \
	fi
#	source='$<' object='$@' libtool=no \
#	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
#	$(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `test -f '$<' || echo '$(srcdir)/'`$<

LSystem$(EXEEXT): $(LSystem_OBJECTS) $(LSystem_DEPENDENCIES) 
	@rm -f LSystem$(EXEEXT)
	$(CXXLINK) $(LSystem_LDFLAGS) $(LSystem_OBJECTS) $(LSystem_LDADD) $(LIBS)

.SUFFIXES:
.SUFFIXES: .C .o .obj

binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)

clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

pdf: pdf-am

ps: ps-am

%.moc.C: %.H
	$(MOC) -o $@ $<

%.H: %.ui
	$(UIC) -o $@ $<

%.C: %.ui
	$(UIC) -o $@ -impl $*.H $<

ValuesDialog.H: ValuesDialog.ui
ValuesDialog.C: ValuesDialog.ui ValuesDialog.H
SurfaceDialog.H: SurfaceDialog.ui
SurfaceDialog.C: SurfaceDialog.ui SurfaceDialog.H
ComplexDialog.H: ComplexDialog.ui
ComplexDialog.C: ComplexDialog.ui ComplexDialog.H
FunctionDialog.H: FunctionDialog.ui
FunctionDialog.C: FunctionDialog.ui FunctionDialog.H
PolarDialog.H: PolarDialog.ui
PolarDialog.C: PolarDialog.ui PolarDialog.H

ValuesDialogImpl.C:  ValuesDialogImpl.H
SurfaceDialogImpl.C: SurfaceDialogImpl.H
ComplexDialogImpl.C: ComplexDialogImpl.H
FunctionDialogImpl.C: FunctionDialogImpl.H
PolarDialogImpl.C: PolarDialogImpl.H
