#!/bin/bash

tilesize=984x668
for i in classdiagram.?.?.png; do 
    /bin/echo -e -n $i "\r"
    if [ ! -f $i.png ]; then 
	convert -crop ${tilesize}+32+92 $i $i.png; 
    fi
done

echo

montage -tile 6x6 -geometry ${tilesize}+0+0 -cache 24 -verbose \
	classdiagram.1.0.png.png classdiagram.2.0.png.png classdiagram.3.0.png.png classdiagram.4.0.png.png classdiagram.5.0.png.png classdiagram.6.0.png.png \
	classdiagram.1.1.png.png classdiagram.2.1.png.png classdiagram.3.1.png.png classdiagram.4.1.png.png classdiagram.5.1.png.png classdiagram.6.1.png.png \
	classdiagram.1.2.png.png classdiagram.2.2.png.png classdiagram.3.2.png.png classdiagram.4.2.png.png classdiagram.5.2.png.png classdiagram.6.2.png.png \
	classdiagram.1.3.png.png classdiagram.2.3.png.png classdiagram.3.3.png.png classdiagram.4.3.png.png classdiagram.5.3.png.png classdiagram.6.3.png.png \
	classdiagram.1.4.png.png classdiagram.2.4.png.png classdiagram.3.4.png.png classdiagram.4.4.png.png classdiagram.5.4.png.png classdiagram.6.4.png.png \
	classdiagram.1.5.png.png classdiagram.2.5.png.png classdiagram.3.5.png.png classdiagram.4.5.png.png classdiagram.5.5.png.png classdiagram.6.5.png.png \
	png:classdiagram.png && \
	rm classdiagram.?.?.png.png
